apiVersion: ENC[AES256_GCM,data:mxs=,iv:mbFJl8X9yZX6mh5fOC1KEbG0JsBD6GuHXOQe+OTT60g=,tag:kLlC0uiyWS0h/NVeQishDQ==,type:str]
kind: ENC[AES256_GCM,data:TH4EJ6Xz,iv:ea+PvcOgPzxLbCPdQpnmi2ZP9JWUCuxZ2zbmHYmroGY=,tag:m4KmRgwW13GWeg8gIswTWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VahjR4ksp26ZQfCS/UPs+HUzqW54zZ8=,iv:ud1Ls1n8OB9oMZ4y+Aghg2yf0k1Y3Io/jVQ8MS3R2Zs=,tag:9Is1R+0rNuhlKum7KjFPdA==,type:str]
    namespace: ENC[AES256_GCM,data:C6Gk8EBF0BwVLdoD,iv:lcHF6lgJgx8WBOcc6rlnAa26KqzWC5mFjDybWOR38B0=,tag:1UC9J0AlmZhlPVqecIooRQ==,type:str]
type: ENC[AES256_GCM,data:DH7NCxOQ,iv:SCXozfQJLA1tdN3Zs4EEZOoaCmgOndatcO+Yi27vi3o=,tag:dbDpqqtapyD+WKMbHrYvvw==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:hh1UjdIYcfWl156n109tSlRgrTO0CLuGi8YUYu5G7sAioInhNNNeyHtqOjQsOKG3prFAPPQRF9yGGqco76bg6yCVQkr9CWCf2S0EHSvq4sZdbtgy/NVUFR2IcWuCLKbL5XZVV/ynN+6bUExCFcnmlslsiN6pdRsvc16D/JQpFg9NcLeR/apxGY+J1KYMkaMs8zRCCPh81W19Fu0IaMnZfjI9,iv:YaK7CvoMLkXXu9hpAu0dKylAWSjpuKFvIauwqh9d+ag=,tag:wP/3trVt8IOlmNSEUaDuEQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeG0vQmVpRjNvcThZaFFm
            b0dTcVhMcXM4OUFsakdwWWlLVC9acHhqZFFRCmFlT2twMjRJbHF0S29xbVdhamc4
            Q0RDSDE5anhIaFBjL0JwM1FSYmtNY1kKLS0tIHpaTW9xRkx3Q1UzK0N1M2E3Y0JG
            NFpuaW1YaWdzSllycmxDRTJlQjNpV2cK9wAXg+8wvCDjwQh/Vd7YR7AOLwLXJ806
            skVfGMI7N8Vj3VY355dEt9+Og4XoLf/4y0+wjnAd6Vg4cjdlRNr04Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:27:46Z"
    mac: ENC[AES256_GCM,data:rSl8UPAwbsfL8Wkh6wSetkMrWLyijXRytjjZKXo58vqLE0WosClYrzIngx4rtkuA2LejGxAFfAp3OWLm0pBq8NVovtToT2CcS0a27qoGh6r6yS55QQaa/nlwt4nrfOQZYoadRRwiJqExdhJRNSZyHrEyqOJHyARb6A5yekQYkEI=,iv:xFqRSmQ7iPK7OHk3HGXtDJB87lnSyYhlWZRgtVmicFA=,tag:EnDmEuGp5vzJbYVF25FKxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
