apiVersion: ENC[AES256_GCM,data:Hf4=,iv:AmjPJbMvtR+attrKvhGxwK8vW0U+PxAj6+xbuof3zG0=,tag:1TWu9PEhC8sPE4j3+X61/A==,type:str]
kind: ENC[AES256_GCM,data:Ei+709dh,iv:m4Kwo2Up9M3dU4QiZG/lsgJ1qVAU16LrD7YOF1gYvIQ=,tag:MOGa4OKc/ljDM8MHU5mftA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+ybTwmXRdqEi1d0/Enm4OrfNGmSBlD4=,iv:zQm/osdYiuJZxjgMe3LghVRZKH80obw7LVkTHJKVKuI=,tag:N3pATzit3luviwFr5feKXA==,type:str]
    namespace: ENC[AES256_GCM,data:wIgxSE3X2Cw+XyE4,iv:amyAcPdYIU0uxQqBrjgQ8ykGx6PZXWKQPUddNeXqp+Q=,tag:fjJ80tT+IfSv+LVdZVf/Jw==,type:str]
type: ENC[AES256_GCM,data:aU3SbxdI,iv:coLBmAeRo1WqzPnjxBoqRbER4h/gZyzFb0M8TmQV+Tg=,tag:daHpVAi9Wis9OZ/C9Vsleg==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:VtofYw3wY+Kzkz4G6n1JIOGPxXfJ/6CelxBTx1tu0Xbv1SxE7Vbg40KJ7uknjnr5l5LW09850kf/KHfxc8psh3PPobRzY9H79vdsNveLkHFnhE+MuVnjiD/Osox6aNGDjNwb7Q5pnddF/XA0s1gFyV+OqkP14D+Lu/vkPemYrnzndB/KzmIoWZ8UIgBEyt3tFxQL6baJbd+q1Qc9R2FicQ6t,iv:Ic5nsUVq9d6cb8hFZu/SauoPCEwwWQVwKQZVyq553TA=,tag:9UTM3JVDSgG4uR7h3nJ6XQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYmIycElibjJoU1dXNHpL
            Um1lSTgwczZXKzVrMm04d2hVYXAxVElGd1hnCmxLWllPNG5vdnZmZzJHSzAvbGxV
            aUNEZ3g1N1V4Z2VEVml6WmpvRnZvbE0KLS0tIC92VktKdUhaL0FRMDVKUWRBSFV5
            NXZVeURMaHFqYjZJQUI2eUZRaUYvM1EKJCmoGRA4DEoiX+zCTVdvYXo8PVHHYfHt
            meE3hsMzJqusIECYPRysdmHfcHICZoK72fDuc2t/ZSIx1fTkOXpUXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:15:40Z"
    mac: ENC[AES256_GCM,data:viPimQJuYob8Np4ck5SwPAZ5M0HBP1/d5lTTfKi9fN1FTL+dHQEKIrLZ+vvdn8F7jnHhtyuSMo35kewYPpK6JkeXOXVYpEeYpr9wL1ub8aJ/hBxpYzIKnZfy3/ajgH9tKSspnBUezFlLQj1nc9H47YkB2GvEk+nOgOucRzGXw8k=,iv:yd1iNXUEEe7ufG/45DAFBR4hLrUalfOhK5pom36KPTw=,tag:H9X7udPR4nlPZImbS/Gv9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
