apiVersion: ENC[AES256_GCM,data:UMk=,iv:B2RWgU6sOl4zO1mtIwFnvI3J4nyW5QXpJeVvhgVSCuA=,tag:9IlhOhZOtChIWGB2vIs9Zw==,type:str]
kind: ENC[AES256_GCM,data:tR08tYok,iv:kpOdNPSBRPTo7utNKzXDohzsfH6lGFhSUc1lyvsEx/E=,tag:AjQ07wG2iMroVTu9d1AqrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mVfqWliIp8KusLSHeA==,iv:XFqiAEv0l2Atjm+cIqdSu0dJiScMbrbYU9EiVS32GzQ=,tag:W9faXBqAhGnH+CZsaqmBWw==,type:str]
    namespace: ENC[AES256_GCM,data:tvDgWo+ugdPlvPgY,iv:JVOEIaRtCk25oDsHBRNdKQLtkyVxjDsnJqqwVV2DHlQ=,tag:iJbWHDG8Pw36IdaFddQIOw==,type:str]
type: ENC[AES256_GCM,data:t3pi+f9Q,iv:br48hZqi/KxneftXV60+VYPtGQwLvPO7Q6uXwH37qAQ=,tag:2qbuaLbknH/TkejEyBpsoA==,type:str]
stringData:
    ARGOCD_TOR_SERVICE_KEY: ENC[AES256_GCM,data:qRk9TDBn6LEVQwWTHzdVqrf3KO7J54EtXWlvOeYfoGHaMhgrHD6ryHjTPMG7wz8+/1UCpgdFY3FN3ITxHQpBDLvoSQcrV7s04F07vpLV1a37gw1tLAO4jR+CVpvnuVKUccYAMoKDuW/xg5QlVLsgk0pSBeRxLlL6L3vdFI26MQ7T,iv:O45zEYvZNIyaWgPD1lXMO0ivJR1rNLBKigpu/dXvPX4=,tag:mr5bRhls6PJX1OQPci4UZg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFZhL1NPcC9IRzJtWFFJ
            bkZSbEo3NGZBeTY3UzdOcDZBcWcxVmlkQ1dNCmlsZFhOQ3hqZk9YNlU4SktTd0NO
            QllQRTRWcG9yS0JNRlhMeTBvSU84UTQKLS0tIEVOcWFqU1pranNHMmFjSGVXZGV5
            bHhETGIyRURYNTdUak9rTGpDOGEvUkUKaszpNIOh8EPcquAUs4Kcxq7xsZcAzWwc
            rb+yP41rq3Y6vaj+REDxdcywFW4FLQB7U9IrktzPcSKUDRFgj5Em8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T17:57:44Z"
    mac: ENC[AES256_GCM,data:A+wvo5gnMRJlRNOHhpU/ucbzmsJ+mEAXBymDoVMIDkErcwqRWG6e7rQmzM9ekgf2iHaSXf1YVlvdfjHUOaReQQpZSPfgIDoYFQgvVf/m6L/vE82LOx2yjv+pfRTn/nj2yksVyPDdB19AGDLK9jr4+CwX/0kQZGvyafFRrRVz6C4=,iv:1qZ+wZqSp36Lf8Tc2A8JCRScg0HaoZeL/KhUSQLlhUk=,tag:bkVBErrieycMWP2jcWd/pw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
