apiVersion: ENC[AES256_GCM,data:cJA=,iv:iwjNEla5o0hdAugobMwkT+MY6l51rw+7NmmXAhM99eg=,tag:kj6facO/0Qu+t6OXyjy8Hg==,type:str]
kind: ENC[AES256_GCM,data:+QaZ+BOn,iv:HrcqI3AsUEVGonZizvJN8g9yOjES7c2sFZ2h9jkRYy0=,tag:C8lt4LwRGo6l8+yHh7dPnA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r1cv37SKoLkfC2zmEw==,iv:Kh9UX3u1bVocLLsFgTHYF3orOU6P34PmdpiZVpLdbvE=,tag:mgY+lwhnp5kWKzklQ9rJMA==,type:str]
    namespace: ENC[AES256_GCM,data:kNUfuavfnzxY4fi+,iv:2oLtA34dbdch7GzLNbhIDDACR4NyUp909m8fbn2McI8=,tag:AmT6Y6h0wWsm1H2nIyACUw==,type:str]
type: ENC[AES256_GCM,data:lFFj9qKN,iv:kpMVahaMlmIp79QAbs/onLeWqnuqbqLoQe0JC4Dioog=,tag:mqEIsYbW6sbaloZsDzphYQ==,type:str]
data:
    ARGOCD_TOR_SERVICE_KEY: ENC[AES256_GCM,data:5cQPIUsUnL9wHNpwTp/MRLp0yCTx9zw/xbnhFFP+BVjkQZBor7ZSAjC5LEwB7DlZBgqGEQITaUBecKz8GVRXz6P/VaKeeLWqNXp9/nZZqONeGrw5sbCAKogQvpvCgyaS1veHsui3b9ZbOWV/PWcPDrfQiK2dRoo5WbCvVjonekE=,iv:/Fm1e4KJ6b5fP0dqUhMEwN2QThqJvwG+idlFh2JyyBQ=,tag:nvg56h4hF5+Fi3W0rjIrrg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZHRCMnpUWDFsbVhwdjJE
            RnRlbGlVWWdIYXBIRjJ2dkI3ajNOLzlvSTJnCjhGNmdFcnp2MDF0ZUUyd3FteGwy
            QWlBK2Nib1Vhc3VUU3F6bjFvbk5qS0EKLS0tIExsS3VQS0QyQ0dUYzNBM0w1eGFC
            b0NXWUl0cXhaUEFDci9OUldrUVgxOVUK9KToUQeOJgQgtzx+qW2FfNLgeA++n97d
            p7hPieEae7oZLqHhWlhf+SonfJE2Ek7o77SqbFMWkwxnuycML12hNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T19:24:23Z"
    mac: ENC[AES256_GCM,data:L4vNFQgtxW2Puu4V7Eww6gqaefBQSG6sOqOWCiM6bYS/Y8QGqWxOzYrRu2eLXvQZAA5h6da03zIGa/88a5K4FsCImPJvA8pPCRcxaVEuVxAOnSWps46Z5Tb3kSM/C5KvQkwFbE1uimExinzTAxr7gDAQCJwJF+jUBHYQed+qTaY=,iv:8UaocdCCBy8kTNawNC71nN3UuIKqZA9ZaGK93F2WRlc=,tag:+kGqS6KafSxDv71ik0xxWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
