apiVersion: v1
kind: Secret
metadata:
    name: tor-proxy-key
    namespace: argocd-proxy
type: Opaque
data:
    # Tor key for ArgoCD .onion service - base64 encoded raw binary
    ARGOCD_TOR_SERVICE_KEY: ENC[AES256_GCM,data:9dR2+TyPFcLi6TmO8nuFjGUOv9WBKEFy72ailIO3xNL2BdqSanX2Cw63DDOpqgO4NbSW910Yo5CxeBCow0hFcfTyCdzs687q8Jm9BWM8biA2b/dK3+SwwGyGTT+qDWRp9SC1wpUouApLLzxG/1JHu7a/VqMdIGrG6CCoF5J1aq0=,iv:rhYCnkLYR+nOZedB0IPXk1iagykwy1ErqWDvqt2Y43o=,tag:LPe0E1RtiWKo0JYYjeeflQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dGJxU2lmTkFrVTdyT1FO
            YjZrOURvQWlUd2FEZENwaW5ta2J2Y1VBTVRvCmVRZ2xjQ213aEZVejJaMW9KOW1n
            MkEyYTRITEpXc3hiRUNhS0ovOTc2RmcKLS0tIE5yTzBlWDViYXZ2ZU1lN3RSRXNt
            N3RlUnpDTDRxbkxkN0Y1ODZkc1NqNUUK/wRR+yM0vZyLtUEqzMjr2lRs1Uk/kOwx
            RghOKYLB3D2MfgkeWrmCl4E+q9ya54nLhYP+YJ8LP/Ko3XvOqoF47Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:CHQju5yR5No67hZj9AGXLXSqN0zC7ryOOy7i260F4m8xGOR0Jg/EZYUjp45zsjjJLluI61Zb1lvGztHlDirpLH1DWX51KSt7gTnHwphCVJQoOi0E7lgCsWXNVXozB8j3Q/neSw9BETH4BRociPZC1iAnG6fI68hCAuEPGfSYEHM=,iv:g7oXhkj/vkNv5AsBSQ+HE/phdo/OjIAaDNI7hpWE+VI=,tag:D43p+2YUsu6JwulNpKTQCQ==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
