apiVersion: ENC[AES256_GCM,data:BXE=,iv:onUO7I3k6pnOV79ws6uR5AyKHnasVe9mZ4qZLtjlr7g=,tag:1j4xvpy0y0LyRRzEtGVrcg==,type:str]
kind: ENC[AES256_GCM,data:alw3+1gQ,iv:gqYdW2UgXGK8XueHhf5UeUJ+AHpqysamOkbrABwEdHw=,tag:5vI5Ct9ZFb7IC+U2QYldRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ewqt1qPHdAJz5WDqLQ==,iv:qJD5Ww7Zm5I7/PU1mXoP8lUkS6S+sGZDp/G5SqLGi8o=,tag:1zX3GqZtEYYNFCQzsQ1WxQ==,type:str]
    namespace: ENC[AES256_GCM,data:n5Kpk2TShIsJqWXS1es54g==,iv:rbzTq++sWYOHGrOjgUhJPhk8VJqmIt5dCx/sD3GWR8c=,tag:AJ9ekvMcmtb51RibWjCbOg==,type:str]
type: ENC[AES256_GCM,data:Jw3KEx5D,iv:r1J/WFh0LVle+7+iuyPDOrvJatvH7AWM3nmaycyA0pg=,tag:Z94Xx4MrMOV5hA/nf1VxGg==,type:str]
stringData:
    ARGOCD_TOR_SERVICE_KEY: ENC[AES256_GCM,data:3gRMzqL1QA3MdJD1FpEDqCtl545PYyBJj1ri3gHzrHaT3ml5bZ+9ViDvD3KDLdFakDF6+/zdIvYNgZymsfLOb3Gb0h/L9HdhCUnFsfrOlp2qtZLOtbYfgkkuNCz4UZSmP+zVzFzUO/sX0CALiPIMGxKdicR2ozGv9gIRBblb9Hoq,iv:rz3PgcrNmqE3ddBLQq4PRDSf155SWV8tnxPxGPFWQZQ=,tag:Ei0ETMCRMuCGTMgSFYlGpQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcWxjQUtncHptNVpRUlRP
            YmQ5NlBPekI2MmRSREJNRFRLSlFMenVEamw4CkRyQVZ1WGo5b0szSytsejJXWUJ4
            Zy8wcjAwc3hMR3dEWEhhMjlCNllkQkEKLS0tIER3L1JCVFJsdmlmbGZtY2x6enYx
            WjY4d0tzWHJ6TjdLbzhvanB5T0crL0UKnTJWd3GsxiWPeO2I2zkke2kRmH8vmJ2+
            Fn63LzfhtUleGpAOg93nc5M8Dv0nFin0EpZJ9f0QnbDj1d5Aj7QRDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T17:53:49Z"
    mac: ENC[AES256_GCM,data:IAWO1lxe+DD2snBw+otL3imn92xjMmcYDT9jOGMvN7iJF1OY5GVHf6CXnu/c+Lj20ri295WhkB0AOyQWiQ5ADH/RYcCH+1BG64qhLyGTM1DpE0JsGWDutjKqsaR/k7mPJ2avGuLWuxzJ9bX7PK8PoXxefrbQrRltqIgD8tzihQs=,iv:/VHSSkoGPLZ4eAcpZMNXuYQhd62F2YaMHYUwx8A/GU8=,tag:3wp8sE4Ypb4fjCOXY/cp2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
