---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    makeitwork.cloud/dns-reconcile: "2026-08-28"
subjects:
  - name: argocd-server
    spec:
      fqdn: argocd.makeitwork.cloud
      protocol: https
      noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: cluster-apps
