#ENC[AES256_GCM,data:4gx5nMKrfKQ9lN2gB2cd3U1bMh6n0nBHPzvBKkvo2g53rr//BNKsFIieyAFKC1mD75NLPPU9Zjg=,iv:/q0/zHyYKRbjy3n48X9EVCDLCWvZoyHFFifdC/k/AnU=,tag:z3ihDB8DBbESxrVotU4quw==,type:comment]
#ENC[AES256_GCM,data:RlIvw+fVwhijsXt9rVQWJVsEP0L4/BuGnbHff9kp3xuS/gIcD6X39YwTJU4fwQ==,iv:s2/6rRpQeuLVRzpbP8hPNrQgnnkfo6oH0Ou3TluVZao=,tag:SR93ee9klOJWqKTVfjum7Q==,type:comment]
apiVersion: ENC[AES256_GCM,data:8qo=,iv:6RDskXHTbCfWjhkwYfAdcy9/rIX4h0LdsWYJp8/5qeA=,tag:iIQ6oBRjDVlmCKDw2GyhpA==,type:str]
kind: ENC[AES256_GCM,data:5b8lOqri,iv:lxiDCQxsS5qcJORpFwEu6NsV5o0AedcK02LLWgEfEQQ=,tag:zLYwvYgaeBTIK884S+dLew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:N4ew/78A2qu75+A9qW18zVsEgYg=,iv:AWdPJf/wVvw0EU1c4h1bw3t8eaz0wFjX0dgMoE/LdKQ=,tag:2JvUDpv38EOKiEH7TaKDAg==,type:str]
    namespace: ENC[AES256_GCM,data:EPJDhY7D9K8yZcoZ,iv:fbAKStsUqym/ktWqM/Vvb733upPydF2QHbPp1x4SN+8=,tag:ZJ71ujS5Yjc23rQPY39OlQ==,type:str]
type: ENC[AES256_GCM,data:uPPKWmk5,iv:A3kCjG3MMxu6BDe/RpOM5Y3jXI6pq06hKrcCaX3DTvc=,tag:n/qhGaqJwLgFer83mbBHfw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:fqDpak4fEegTmDtEn0aZmrXyT/YrjgKyfsSenKfSOhRtnIr0BjOSng==,iv:h31uxIi9bf4uV2rHymFcncBKdYg08jHimcjzLU8zE1s=,tag:O2PGxiX29Vrax6YxF4W8kw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQkdkbjhIajFZZVkxZHV3
            dHp3RnNrbDV0N0ZZclVvazVSZk43QkpqOUNRCmNSbEtTTkFKK1VISDA4TFhMUG0y
            ZGRtdUlxeDYvNkZza3U0c2dEUDZSTTgKLS0tIEdySk1HT2t5UnYwK1RQWFhwRTAw
            TWdxY1drTmxITzhYRHloYWhzTHU3dzAKFE9YzS6hdR8GeoNqgPq0Fy+E+G5agTGj
            9Iu2aNZAb05oKchjTz1ETHZlqxVYnn8eR/imTRYlwe4/E2BNQLB47A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T19:40:36Z"
    mac: ENC[AES256_GCM,data:wKZRCVTCmQaK7FSzOeWJUCMTPkf8dpKcIWjlRmyeNipAUXLGMQC3y1PJA2VfGJAk1YrS4LTszpo8hYNYii/ceDlaJEJEp5oawj9m8XKkYLp+WFqOd8w3cu8mO9W8K7F2sIyerGNX/pybz41gDHw3KOuqiqTi5O2MQ6ndurONT+k=,iv:OEzJX+4GfivLGGRKtuODvxS3ph/50hRnK50rDDMRxCk=,tag:XR8O9H4DROAqOFM/5Q6RZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
