apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:kquE/vcxvYT2hAuSRRxWzRXbnfZ+8Gsbi5O1Dh+iqcgbHy9qohBWjw==,iv:07ViW9wAqCDEzxULaMSYOfJx2S1WHE491FAiH+E6UaI=,tag:syhgHuQfvFev96k9GVKV/A==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZE1tN0RYRUw4YmdVWjlJ
            VS9Zb1kzd2hZdlQrZ05LeXpWUG1hNjRXNEZnCm1wMHNCSlZYMFJ2U3F1NFpDM3RG
            SkMvRU5MekRFUUlaQkI3cHpXaGExYUkKLS0tIFZVbW9hWHBVTXFiRGZjMnZ1R3hw
            dWx1b0xJbENScjdFdVBhUkFuV0tROVUKUMHNFS+ucvmqzSCWDqhthv4klxT0n2Ta
            FxHz0MBDpJTojZHzHXrLZU/ui9A0vWqHBYTZQ8SjjR7NWVeW1E/qGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:79kWQq0MPDIPbCyn9+GjA++lUz/b6/x1TIZyB+t/PjTe105gr12R14/YcwNR6ZYE+9cmpSTJGgWGLCqdz6A2e7DXTDiC0G6vLkONpSNjgiQ/aCukHsVSkvqAIbuku5mf5cEPupLKnsEloHJsYSsQ6uI7qvVAvj4eRV+Id0aynmw=,iv:Kh8VfGMe0CaaPhimLE4z+Ey3x+enRxL6Q1kDi/I7EZI=,tag:mAY97rZuNFJ5IRS8OqyHAA==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
