---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-cert-manager-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cloudflare-api-token-secret.yaml
