apiVersion: v1
kind: Secret
metadata:
    name: mcp-argocd
    namespace: mcp
type: Opaque
stringData:
    ARGOCD_API_TOKEN: ENC[AES256_GCM,data:X295O83VXrU0vw8rLNhBXNbHzLwFAIRcsi08OIzNvk4AIVoN/G/ouuWWTVLy3OKJ1emE2velp9g9M55KZ3RSbp9tey1QHM8AwSv3tOVNqm3/WWZKlFiqbBzBDBREFcdFGzL7n+zVnMX16eP8Kld8/y6lh5szxLv7raTLro2ts3GMTFKNabbjLWLj/bqI7EO381SI/xutnScM7dnH7dA0NbymV4S6zoOmO/n+XTVaaEaoNB6qRnkOizsJ2Ad/5MOYNAknQPzh6RugbihXIlDwyK+tvm6pbOlFwt9mUXZIJCou9Nd00f1QJMo=,iv:7BZedJf2KwUWmq4NtB8onChbR+u3E1KBpbbXVbH7VoM=,tag:my2QKMumAS48JFT2JVuoWA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeU5WYzRPOUVlUW5OcFdr
            V2ZiZXFaWjRFbU8vbnNEL2hNUTBBRlFYejBzCjRQNWszMHNkNmxPdkorVzloRFdq
            UU90NHNwNmpWME9sWHlWbHB1Q3NkbW8KLS0tIHp5NGttTkZGcGFJRDk2ZUVXRmZx
            eldEaEVWVDQzWjA1RDJnN21xTnNpTU0KygG263EpjiQje8ROtGRLE2NNk0tvSXys
            DiaUEtoDeQm8wQyUqUIvBWKAaZSt5upTv7rTZmUCsU11RkIMdz9xMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T18:19:55Z"
    mac: ENC[AES256_GCM,data:Wod4G4AQqwmzAjZle0DKjPq/lxKkmhI49XSeel+pbwQ1TROQ7ShfUdBdt94VSB4nKnJwRCEd/t1/lDLAOQFWDpdvl14MWNt4kzZRf+IetHRGe4qbfkwogZv5JT1VDxktvAevb5XMyg/h0cjtlob4k5YHZs8OZjGEQu46GkN5P0c=,iv:7WEWrNjIiwomTTa8u+DTFSIgmeaCKPH0Z/nFgDO7EiA=,tag:VXfDL4SLhhky+2V4czVnew==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|authorization|github_token|ARGOCD_API_TOKEN|GRAFANA_SERVICE_ACCOUNT_TOKEN|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|credentials\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    version: 3.13.3
