apiVersion: v1
kind: Secret
metadata:
    name: mcp-argocd
    namespace: mcp
type: Opaque
stringData:
    ARGOCD_API_TOKEN: ENC[AES256_GCM,data:RHTr4ZQ82SK1uyTmGmsTLvInlzpJr/taHjFboHYwAAQNQdUzq7QcZ/KwxTaY2tXzAsXDU8AZoxsSrOUoedIONo8WVqLJ3eVVdil/oDCjz//l55tFkoOi2AJLstS+UQwPM6GNDbI/qDC1JsM1TnXW59Wybwd3Xfqer5/NP0KfmNch/h6gT0e13ifafsZW8d5lZ0h6BuZAE2DoUX3Bfech4d9ldcNN/6BvQ6CbvOLkD+rjijniMzhD6IH6XeM4iDVAAI/BDq8WCWQ=,iv:sXbgZmP09E73wboFD1matv02puoifrIdmjXJyq7+axk=,tag:BCMPU0X9Y7zEYNunBt2AMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeU5WYzRPOUVlUW5OcFdr
            V2ZiZXFaWjRFbU8vbnNEL2hNUTBBRlFYejBzCjRQNWszMHNkNmxPdkorVzloRFdq
            UU90NHNwNmpWME9sWHlWbHB1Q3NkbW8KLS0tIHp5NGttTkZGcGFJRDk2ZUVXRmZx
            eldEaEVWVDQzWjA1RDJnN21xTnNpTU0KygG263EpjiQje8ROtGRLE2NNk0tvSXys
            DiaUEtoDeQm8wQyUqUIvBWKAaZSt5upTv7rTZmUCsU11RkIMdz9xMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|authorization|github_token|ARGOCD_API_TOKEN|GRAFANA_SERVICE_ACCOUNT_TOKEN|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|credentials\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-26T15:40:44Z"
    mac: ENC[AES256_GCM,data:no4Ranl29L/qg59UVHDLkILoKsrZVbA2IXGGDODEaSz5sqIvyYtz/BT/nPVElVtmYJ7T8qP3hT45Iy7NHdszHt7fk8iXXKpbm+izNFx1mpSfv/nflBzYcYfLETtLkfhT1U/UJlKqCsDWX2+KtmHzHq8/sl7gpznWap23A00xs3w=,iv:XPxPqRBeRmfVoBUm8ulehF30Jz7qLrfpj3zMgeyWMUM=,tag:K5DKLV3E1LlsFzBSy2egIQ==,type:str]
    version: 3.13.3
