apiVersion: v1
kind: Secret
metadata:
    name: mcp-grafana
    namespace: mcp
type: Opaque
stringData:
    GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:ajQAFW9Ycor+USte1wuleKpDi4AzEnNzsUU27Ee2lKi5T4y5JUJxyQoKtKaP4g==,iv:aJigMovpI4i9dHmbCJqSYjvm+q10vNyM36B1suiCvbo=,tag:LRSst66rFmTkGcsorIKcfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT0NMV3poaFRnT25Wa3Ja
            TXhPUG9ZREpxUi8yTm5mVEFmM2hFaDh5cno4Cm1ieVc4MFFTU3k1OWQ4YUNpcUFW
            dnhvM1JGZHNIV2l2NHZvQmZyeStVeXcKLS0tIDhIL25JZGdOdm1FN2gxd0ZXcjRp
            cHpReVcyVlB0bndHYnk4U0NCMVQ2b3cKn5WvtJYpqYDgcLAirqvymhibZCslhmMS
            EQFk0BsCYv6qnwFPbVYFqbmsCp0m6PRPUreef8welSiWlcmJx0594g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|authorization|github_token|ARGOCD_API_TOKEN|GRAFANA_SERVICE_ACCOUNT_TOKEN|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|credentials\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-26T15:46:40Z"
    mac: ENC[AES256_GCM,data:gx8uOH3G3+9iMIzUDf39y05aJ1X9wXLYiDyvYx4hxjdvMl8NOLBMnVBUgYpzZkczox6MJl/L52N4ryQK/nG+YH9+G5QRbYhNrCHcqkk1Fo5HZoC7qWxenkDWMk3umlm6JvCR9plyiI2iOrY+0DSmwU5eWNEBDHbhPCMLUIFW4do=,iv:N2r4C6MnXWHAkVEld7SKaXTsVFbzE4sZyCZyWn3XTpw=,tag:m1RYtvxPVfOHXSXxBmE2Tg==,type:str]
    version: 3.13.3
