---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-mcp-gateway-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - makeitwork-github-app-secret.yaml
  - makeitwork-github-xnoto-app-secret.yaml
  - makeitwork-github-secret.yaml
  - makeitwork-github-xnoto-secret.yaml
  - argocd-secret.yaml
  - grafana-secret.yaml
  - parallel-secret.yaml
  - apify-secret.yaml
