---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-mcp-gateway-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - makeitwork-github-token-secret.yaml
  - argocd-secret.yaml
  - grafana-secret.yaml
  - parallel-secret.yaml
  - apify-secret.yaml
  - mcp-aws-secret.yaml
  - slidespeak-secret.yaml
