---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mcpgroup.yaml
  - kubernetes-mcpserver.yaml
  - argocd-mcpserver.yaml
  - grafana-mcpserver.yaml
  - aws-docs-mcpserver.yaml
  - terraform-docs-mcpserver.yaml
  - makeitwork-github-mcpserver.yaml
  - makeitwork-github-xnoto-mcpserver.yaml
  - remote-proxies.yaml
  - vmcp.yaml
  - tunnel-binding.yaml
generators:
  - ksops-mcp-gateway-secrets.yaml
