apiVersion: v1
kind: Secret
metadata:
    name: mcp-makeitwork-github-token
    namespace: mcp
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:hjj0knXC2OaZVhAsghPoB//Nzyi1McbZ/Xjvlhg8i5CZ/vYm1LMiVg==,iv:RA+9+Vbp3eKwCvRNFVVPXzv0rfPYxiIS5eDJBPdglIk=,tag:t2TN3B0buDN1/RHICibfwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwS3NNb1FHT1p5bHZQNUpz
            d01VREtxR1NOMkJUWmgrUnZqdU5QcHVDMVUwCnJCSzF1RkJpaDJhaGROTHpmT3pQ
            Z21mclRkamVaektHRExSeUplREFkc1kKLS0tIGhlK3Jka0pGUTh1WVYwNU9kZmhH
            ZEgxcnNGMUZSck1TeDJXemQ5NENIcFUKKZgsRuy+TIcJCn43NR3xYf9wEyVG5iuk
            XRXACmZG+NPcXfiFwKt+yirLQmU2qgKPtWh+Wij7wh3pkdVyANNXkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|authorization|github_token|github_app_private_key|ARGOCD_API_TOKEN|GRAFANA_SERVICE_ACCOUNT_TOKEN|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|MINIMAX_API_KEY|ZHIPU_API_KEY|credentials\.json|auth\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-27T02:50:07Z"
    mac: ENC[AES256_GCM,data:8Fc+N93ZvGwxcPclF66VDAHJiP4S7Zd7A6Tda1o2dQ0T072iXNtUQcc/VeWU+JJB9vO4inBcbCd52YpylfxdzDjb87HW8iQ869Nyna0rJBnwqztwkZIEYRB9ZlVCUYYozaLJPtVhGiO9KV1Du7aj4grQLOOyshJBO7jDY9FF8KQ=,iv:/VlTQX3sgHB8TfUQhktZSnP/mnyk01Qwa61MEu8ggjw=,tag:2YTrTG+z/AiqMwqzSpfWgw==,type:str]
    version: 3.13.3
