apiVersion: v1
kind: Secret
metadata:
    name: mcp-aws
    namespace: mcp
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UALpm/+Y9pOqaZJy+UUH7rRbV1A=,iv:bAX1JPZYUpQ8Umi6kbaSYgf0Zk7mZ1cQLSBYvFcMt3o=,tag:IE6FuQ9n7qDhRI1NEWcrrw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:V/GQ14iQ57sHlF9HDSqE9NK8Bj9KNDPnURNWbGvqCgOnY4tn4mKpew==,iv:7LHSMaPJLxeFUZbKcmGcJCU7fGg9b66F0FRMUVQmzL4=,tag:oPz/lBFA+4jk/MSVkDWCgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMVhrTmxwUm5zc1B3czYx
            YnoySUdjQUwybUJlY0I4bnNsY0NiR0FQblJjCkdEdEFFamhNQ1FKWFQ0WEFjbmdp
            V3N2T2g2dk1YK3BRemV3dGJHZ2l3UXcKLS0tIEZJSkR1VTZmVmlyRWRuRGRoZ3VF
            YUZsdEN6Q1l2SE5xcGJDMkQvN1ZLa0UK8MtRikIqvRIQu18T8Oc77nen8rKoH7RY
            xsqJFu18fD6bsQdRBkCIv3jTOG2dNz00hUABjP3CrSRxfBna6QwDDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|authorization|github_token|github_app_private_key|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|ARGOCD_API_TOKEN|GRAFANA_SERVICE_ACCOUNT_TOKEN|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|MINIMAX_API_KEY|ZHIPU_API_KEY|credentials\.json|auth\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-27T21:51:06Z"
    mac: ENC[AES256_GCM,data:t+SKj+n2p1ST3DdJkmZ1cez/3P8h6CSms2Y7ugvNyY4V2KKri354Z3Hh6ZQ26l94PRQz1RkvAl6g67xXXpHzTRvglUOmubk/2FEv21FAupJdk+A6kGS4SKaz2DALoZtPHdEjYVSFlADbySWpen7t7W8IDPdNIa1nxSHy7JQ8j2o=,iv:w4xPwO8HFIDguqO3temTdpc6Um4lplgIjJCCFQTvoos=,tag:rCby/n3XWvmhsKntcWiQSw==,type:str]
    version: 3.13.3
