apiVersion: v1
kind: Secret
metadata:
    name: mcp-parallel
    namespace: mcp
type: Opaque
stringData:
    authorization: ENC[AES256_GCM,data:0JxdX643LTrv9gh7ExGcKfszWwI1AbigkUf165CfictmL3NuLH5qf/5fYX4+TSQ=,iv:kFaC2rkqKUeNRiBBPTVcuPhbmL08Z9ZtgFwo76SMyXY=,tag:5zsT1lOz/k3M8oegLHwRvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NHAvUjBtMVR6cVkyQ2xr
            a1FwVWd3T1d0Vlo2cTJlNGZnWlNOUXBweVdRCjBFbFlmRGJnM3ZQRlExbW9VUVJK
            T1pUSzhhN1pQMm5yYWxHVUlLeHZSQmMKLS0tIE1lVDVXdDR2WE1PWE1kNW1IN3V0
            WGdheHV4MTh5clRsZXJZM2N6czhYd1EKjSspNhUH8op6lQlJS5p5q9acMTW4R2yh
            BexlrpAMM4ly5YBIvtJ2Javi7wlCkYqtkBbfciWn5rIpfcWe2tLCrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|authorization|github_token|ARGOCD_API_TOKEN|GRAFANA_SERVICE_ACCOUNT_TOKEN|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|credentials\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-26T15:16:41Z"
    mac: ENC[AES256_GCM,data:QIjdw/s5YmYya1bf+QqUfGi4KLOdRTKg2J/v5t4c3cGgWI7UdqkRfnvo7+R4zOuW24J9dURcTr/pZycBIxTw9TYkWcOLstlOYMffToj3Nipgk4+nd2AqVH08jEgRvlpr60OyqRxiITeIx2171xCbiNEiKRRLNFcXPBu+B6ODYtA=,iv:Ljofaw5F7i7Ow5FQnGlwChS01WuvXQZ5fct/VRAFfBQ=,tag:7cRTQ+wcDj6c0R42dQ8UMw==,type:str]
    version: 3.13.3
