apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kustomize.config.k8s.io/behavior: merge
    name: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:04:49Z"
    mac: ENC[AES256_GCM,data:bs8Nl/j47y1o4rJe7ZYKIFYENjRBY5+hjFBPbQQKBKEG7E6UUYNNwEgSOEwOGLNQyLypO0v5IYz9Vm+XOUrbSdjdiIqKbd5hdBPyod0h24K+qixZkUQDZuWuMrFjy6EBCdKSnr76ioGjsx104v2TtG729vpox+REq6Oh/9biyvA=,iv:ZwRRy1XmmUK5Z8D5Cc4aD6NDtXrgOzCi8rlZwvtfO9k=,tag:27GDxWAExEzlwTFqpqHszQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: v1
data:
    daemon.json: '{"registry-mirrors": ["http://registry.docker-registry.svc:5000"], "insecure-registries": ["registry.docker-registry.svc:5000", "registry.docker-registry.svc.cluster.local:5000", "image-registry.openshift-image-registry.svc:5000", "image-registry.openshift-image-registry.svc.cluster.local:5000", "10.217.5.181:5000", "default-route-openshift-image-registry.apps.makeitwork.cloud"]}'
kind: ConfigMap
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kustomize.config.k8s.io/behavior: merge
    name: docker-daemon-config
    namespace: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:04:49Z"
    mac: ENC[AES256_GCM,data:bs8Nl/j47y1o4rJe7ZYKIFYENjRBY5+hjFBPbQQKBKEG7E6UUYNNwEgSOEwOGLNQyLypO0v5IYz9Vm+XOUrbSdjdiIqKbd5hdBPyod0h24K+qixZkUQDZuWuMrFjy6EBCdKSnr76ioGjsx104v2TtG729vpox+REq6Oh/9biyvA=,iv:ZwRRy1XmmUK5Z8D5Cc4aD6NDtXrgOzCi8rlZwvtfO9k=,tag:27GDxWAExEzlwTFqpqHszQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        kustomize.config.k8s.io/behavior: replace
    name: arc-runner-set
    namespace: openshift-gitops
spec:
    destination:
        namespace: arc-runners
        server: https://kubernetes.default.svc
    project: default
    source:
        chart: gha-runner-scale-set
        helm:
            releaseName: arc
            valuesObject:
                controllerServiceAccount:
                    name: arc-gha-rs-controller
                    namespace: arc-systems
                githubConfigSecret:
                    github_token: ENC[AES256_GCM,data:ExR35kIiAPcYd4JNoDx+Kimcos4m88ZAKw37irEtXgkvc3jjjsttEw==,iv:KW7aY84oJAEsLJVpXLIDDR9tR5LPxHSWyPIVcYYFvh0=,tag:kbfc7awq/e+xpCv1tktZQg==,type:str]
                githubConfigUrl: https://github.com/makeitworkcloud
                maxRunners: 1
                minRunners: 1
                template:
                    spec:
                        containers:
                            - command:
                                - /home/runner/run.sh
                              env:
                                - name: DOCKER_HOST
                                  value: unix:///var/run/docker.sock
                              image: ghcr.io/actions/actions-runner:latest
                              name: runner
                              volumeMounts:
                                - mountPath: /home/runner/_work
                                  name: work
                                - mountPath: /var/run
                                  name: dind-sock
                            - args:
                                - dockerd
                                - --host=unix:///var/run/docker.sock
                                - --group=$(DOCKER_GROUP_GID)
                              env:
                                - name: DOCKER_GROUP_GID
                                  value: "123"
                              image: docker:dind
                              name: dind
                              securityContext:
                                privileged: true
                              volumeMounts:
                                - mountPath: /home/runner/_work
                                  name: work
                                - mountPath: /var/lib/docker
                                  name: var-lib-docker
                                - mountPath: /var/run
                                  name: dind-sock
                                - mountPath: /home/runner/externals
                                  name: dind-externals
                                - mountPath: /etc/docker/daemon.json
                                  name: daemon-json
                                  readOnly: true
                                  subPath: daemon.json
                        initContainers:
                            - command:
                                - cp
                                - -r
                                - -v
                                - /home/runner/externals/.
                                - /home/runner/tmpDir/
                              image: ghcr.io/actions/actions-runner:latest
                              name: init-dind-externals
                              volumeMounts:
                                - mountPath: /home/runner/tmpDir
                                  name: dind-externals
                        volumes:
                            - emptyDir: {}
                              name: work
                            - ephemeral:
                                volumeClaimTemplate:
                                    spec:
                                        accessModes:
                                            - ReadWriteOnce
                                        resources:
                                            requests:
                                                storage: 50Gi
                              name: var-lib-docker
                            - emptyDir: {}
                              name: dind-sock
                            - emptyDir: {}
                              name: dind-externals
                            - configMap:
                                name: docker-daemon-config
                              name: daemon-json
        repoURL: ghcr.io/actions/actions-runner-controller-charts
        targetRevision: 0.11.0
    syncPolicy:
        automated:
            prune: false
            selfHeal: true
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:04:49Z"
    mac: ENC[AES256_GCM,data:bs8Nl/j47y1o4rJe7ZYKIFYENjRBY5+hjFBPbQQKBKEG7E6UUYNNwEgSOEwOGLNQyLypO0v5IYz9Vm+XOUrbSdjdiIqKbd5hdBPyod0h24K+qixZkUQDZuWuMrFjy6EBCdKSnr76ioGjsx104v2TtG729vpox+REq6Oh/9biyvA=,iv:ZwRRy1XmmUK5Z8D5Cc4aD6NDtXrgOzCi8rlZwvtfO9k=,tag:27GDxWAExEzlwTFqpqHszQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kustomize.config.k8s.io/behavior: merge
    name: arc-runners-scc-rb
    namespace: arc-runners
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:privileged
subjects:
    - kind: ServiceAccount
      name: arc-gha-rs-no-permission
      namespace: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:04:49Z"
    mac: ENC[AES256_GCM,data:bs8Nl/j47y1o4rJe7ZYKIFYENjRBY5+hjFBPbQQKBKEG7E6UUYNNwEgSOEwOGLNQyLypO0v5IYz9Vm+XOUrbSdjdiIqKbd5hdBPyod0h24K+qixZkUQDZuWuMrFjy6EBCdKSnr76ioGjsx104v2TtG729vpox+REq6Oh/9biyvA=,iv:ZwRRy1XmmUK5Z8D5Cc4aD6NDtXrgOzCi8rlZwvtfO9k=,tag:27GDxWAExEzlwTFqpqHszQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
