---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toolhive-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
        - .spec.conversion
        - .spec.preserveUnknownFields
        - .status
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    chart: toolhive-operator-crds
    repoURL: ghcr.io/stacklok/toolhive
    targetRevision: 0.46.0
    helm:
      releaseName: toolhive-operator-crds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
