apiVersion: ENC[AES256_GCM,data:AmY=,iv:cjBaLfiaGkp3yLjB0nLQVJL4lb/rht0kWSacHfmxL9E=,tag:sibUHudrhZrjZNmEPe6RjQ==,type:str]
kind: ENC[AES256_GCM,data:nb83Rp1WyV7I,iv:0YnEw6rVCLG3B/RDphjeSKNVcrnj2CbGrIjQQT3h0ZM=,tag:vn3d/4oPrTOfciKDRxGl5w==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:NA==,iv:RaooVtqNLBcFkjSnil7A/4MWeDAMCs1Omry34yxKkLc=,tag:OMtQO5aNfi4N711cxafeBg==,type:str]
    name: ENC[AES256_GCM,data:Wts07zSkDlgtErg=,iv:KbWt1jFjKU01zkcvb3M+D1stVC/02RTxPtVyCon/pcg=,tag:O4ACEOsb26+Dtn56fBG5GQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT2t4bWNXK29naGVVNmxt
            V2FheGlTRzA4dEVmdjFrZ01WUThDdHpVU0E0ClpnVnN6MVgvUFdYL1ZJNjg1ZVdT
            QW9GN1FJVUY4c2l2dHN1d21XT3k0bzAKLS0tIHFRSnlWUGRXa0U1ZU5oQWJ6dTVv
            aWdvMlpoTFdGNG9EcWRQeUxjd3pOaDgKl1e8ZbLcKafhRwIC+YLd2omWCBOTDQvG
            uybQaQPtc5Yc+XDaB8DEQCD13h/Y9uZlTytPgDGVqujZnrrdaZDknQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T22:43:20Z"
    mac: ENC[AES256_GCM,data:s29YOAGoW+DEg9ofR31+uaas4FraWzrfnacTJN6Kl4//GW0l0msgslb1Ae2Xg3aao9BdD+6lw80rCgTa2SZLA2h5FBTSj7sscVq5A6HQnJ/I9HXZgWKfKo9C/eB3PqdT9XtNNnVupjIr99ieV7ds0Ow9zgFwcF/tW7NnyLNueNY=,iv:sknyKPv2MLHckv4k1STP5epOSy0mu0Abti863yC/4f8=,tag:bi5w3C7eA3DmTLmIKD7Nlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Cw0=,iv:9IU4iLIQWaqUlv39bCe9q4+SXnBd0e33dMfT6JuFD8Q=,tag:ujnsplMMZXbohKSFwXwEjA==,type:str]
data:
    daemon.json: ENC[AES256_GCM,data:j6qqvtS7AZz20UsHTrhksZc6SDLapwirGOEkhvjxcXHeTusT4tWyNDtpUNkFVL2lWiLWkJnQ9fgLpNOWpNTjy/Pjag7PfZiLWEU5nzFnEIzvicOSyI1pMJVaAzgufPxkfnoaFcqgh42IHoSfLqaq/hzyuznShobuuubvSrFhbi2xEzqAAEAxSfn1yGTCnm6HrGLBV0y6bYN8A5fwu5q6Wq5oftcDjpWoA1tnbAFnnxpACZ/FoIPt5i7u+hqJ0aW5Ut8dyaOJ8lEpa1p+mWpN3bgCAD4gW9botyrddQI0fS6d9oRBT+j7yE1Sjmn4hKmBLBo4vwV+BsHx+2Eex3G94vGSAOWdVHpv3ZIECDw0FNxpbsmggwMTtXSMCXDz5dg6ItQhPGMX2VwDOJ1F2W908aIf5PJHqZiEUhP5q7/0NsjgVKvK/4T3JvVaOvtE80CrjofoENIj0kYkhFEoptlDpabKWkt81jYeJN9IGCEmV0agfYaDwrHcPduOVKWOJg==,iv:D6ZQwJ60q2NvBZmDDFb0rgWTyLEN60pxIP++Y9WvDoA=,tag:QLboQLjD712AZo0NOaPmjQ==,type:str]
kind: ENC[AES256_GCM,data:3t58a7mj5FQC,iv:u3SmR82NsxDnxHZIZf8d+qrUmrRDQdK3zzP+fC5XJjs=,tag:pKgV/ALL03NMIPqA3mNNwQ==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:fg==,iv:ACQzSJ4S/5XTHbldgioxb30FHEwpOfTybZhNLQCEElY=,tag:pMjS3nhpUBbAwyBwskT0Zw==,type:str]
    name: ENC[AES256_GCM,data:7dqK+jKnDETTPLcwhda6YJJhUfI=,iv:NKwz3m9j3bOQITWWKW2merjGM5iqOF9shiSO8CXwXII=,tag:xH2BSGj1Fq2dwZDcyaXO/A==,type:str]
    namespace: ENC[AES256_GCM,data:es9ZcpQoIZ1aRTw=,iv:c3H7tALr1IpOYljmRKbxrL0vFyCOXC176JvVoLdMpNE=,tag:ygcdQZlXQXnec3lIOaZW8A==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT2t4bWNXK29naGVVNmxt
            V2FheGlTRzA4dEVmdjFrZ01WUThDdHpVU0E0ClpnVnN6MVgvUFdYL1ZJNjg1ZVdT
            QW9GN1FJVUY4c2l2dHN1d21XT3k0bzAKLS0tIHFRSnlWUGRXa0U1ZU5oQWJ6dTVv
            aWdvMlpoTFdGNG9EcWRQeUxjd3pOaDgKl1e8ZbLcKafhRwIC+YLd2omWCBOTDQvG
            uybQaQPtc5Yc+XDaB8DEQCD13h/Y9uZlTytPgDGVqujZnrrdaZDknQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T22:43:20Z"
    mac: ENC[AES256_GCM,data:s29YOAGoW+DEg9ofR31+uaas4FraWzrfnacTJN6Kl4//GW0l0msgslb1Ae2Xg3aao9BdD+6lw80rCgTa2SZLA2h5FBTSj7sscVq5A6HQnJ/I9HXZgWKfKo9C/eB3PqdT9XtNNnVupjIr99ieV7ds0Ow9zgFwcF/tW7NnyLNueNY=,iv:sknyKPv2MLHckv4k1STP5epOSy0mu0Abti863yC/4f8=,tag:bi5w3C7eA3DmTLmIKD7Nlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:yPMaR9P/iycVfAj8yQAEhjA377Y=,iv:sIi3DIasgUCRJ+jDycsE1XgA8O3X4PqUg+Vw5hwMiX8=,tag:nzAgLbZKh1vMKM/BF2L/mQ==,type:str]
kind: ENC[AES256_GCM,data:OcMFZdrIz5hcN/8=,iv:doedfT4c8U487y5J4Pm7Dy5r7GhJYsEjQ9Ty059+0r0=,tag:WftLVXw1ldY1sW9tknbWzg==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:zw==,iv:RK5kFUV3MiYlBZ0GCLKUwXroqkEcOZU7fNGONWBJjFM=,tag:dzFWA5rW48eI6vdCkH5VmQ==,type:str]
    name: ENC[AES256_GCM,data:DbX/J2JEl5iDDhDY5Mg=,iv:JGGx65zm2X/8PtiIrxHzWhk7W5nj9Q9a7F6Ix9pXz+o=,tag:xBLgUmTa7JhUOHHNUnhbtw==,type:str]
    namespace: ENC[AES256_GCM,data:9XE0b/7i2FFQf3vqTDxfeQ==,iv:0InQgVdHlNbXh9aQoL6CGZU9GPyTwyCcWScm7/erbX8=,tag:NWSdLRbZhnOCXtr1tt1+0A==,type:str]
spec:
    destination:
        namespace: ENC[AES256_GCM,data:V+euF3lWlKt0fKk=,iv:JWacTuwPoZHIa9Z/N3eIz7Db1xsHwCt43XPqyvugw1A=,tag:+Qthifi8VtRHgmCLEB1srw==,type:str]
        server: ENC[AES256_GCM,data:saE7Br92Gv0OJMzdA6cmQBqFxBBsGZ/2nVoIP4gO,iv:55PooRM1FwK5zCMPXPS35r2fEeGFk6E2Md/+Kb4HJS0=,tag:OVRwxla9ygZSM+8HimgWpQ==,type:str]
    project: ENC[AES256_GCM,data:jiCP40tzXQ==,iv:XEsg/fRp/pfUIvyjNqGY3MpO8VVDXOEKAnfow3gwLcY=,tag:Mty2MYGZ0mhLfudj5UDdfw==,type:str]
    source:
        chart: ENC[AES256_GCM,data:HJoCakzeAQd41rqbQgKPmmmhB2I=,iv:uCFlc6vL44eKlpDYtKns14SCE2gaGnjB7Bx6BSGSdVM=,tag:DdmJSQnkjmDzZGqkardASg==,type:str]
        helm:
            releaseName: ENC[AES256_GCM,data:krVt,iv:wXsyFeOtKyV9oKB7zX2WcHZr7ozkxzj+Nt+ARo7I6hE=,tag:z63q1piKBD+DXKwHYdPXDA==,type:str]
            valuesObject:
                controllerServiceAccount:
                    name: ENC[AES256_GCM,data:kZmTT9+Tposig0su5Vm1h6Q/UjVd,iv:V6sFgh1G60OXcrW5a5oDQanvdO77LyqeSl7n+H8rci0=,tag:nRd9GrAzKAdpZc/3DPnu7w==,type:str]
                    namespace: ENC[AES256_GCM,data:EpmrY+XfHeu1ck0=,iv:wC+TKhYjgY98W/ZKT0OIkbqk2KXehHByBsns8sL6NUo=,tag:0X34Yi7kQ6XpxHQ9fDH4BQ==,type:str]
                githubConfigSecret:
                    github_token: ENC[AES256_GCM,data:6OJAyT2cj3FWNpBIL/gNnGKIXlizAcUzMlcWktDNzLWhKlCGpI3JJA==,iv:/XRrtFCw8j48orpkdbHdjbpESImd2hCMH8N4O0V3f0Q=,tag:mfsTfaxIfPmuNfFooypIyQ==,type:str]
                githubConfigUrl: ENC[AES256_GCM,data:FUS40I6XVQlVW4eZvOp4ZQ4izLgQy7fLMK6HNUd4UcliPA==,iv:ZV4tRKFfv4/nveHw5mZDQ2W6twJy7nc9cx1R059EIZQ=,tag:3tdVg2QfLj4tEITBT3wQwQ==,type:str]
                maxRunners: ENC[AES256_GCM,data:ig==,iv:dy/ke1byM01WPqas4oEyvyq2ULvWMyKLaNg0GWtG+Nw=,tag:YOHbqAe3d9ME4Emt7omUpA==,type:int]
                minRunners: ENC[AES256_GCM,data:Ow==,iv:SrSgZPpVv4CisGV6LELlVhlAxdbh6rNvSD3NBVqJKsQ=,tag:5I5mQQCcGzV2A8DDboX6TQ==,type:int]
                template:
                    spec:
                        containers:
                            - command:
                                - ENC[AES256_GCM,data:MDoSbrmzn/A8r4OSPQmgWYQWTw==,iv:cBFh1OzFV8aLK7UNon8rHvQIwVpsqXMx5tq0mMzBCEU=,tag:jXd/tInPVhB/y7zw0k3O8w==,type:str]
                              env:
                                - name: ENC[AES256_GCM,data:Rj/xKrKsYpiXetw=,iv:GNODarr/asJScLKamDqxj/fxGB7je82wC72DHwdoiVk=,tag:uqXhUXbhu3MANGxnKUvXEw==,type:str]
                                  value: ENC[AES256_GCM,data:uWUCVjQ9wLthUc+k5kv8ma42+RW1/o5Z9HPJ,iv:G4Z0iePJQcyR81ydkGPpibXI2y/HDmNaxul0JbQzHTg=,tag:I93eBP14O34QlWPXRIquPQ==,type:str]
                              image: ENC[AES256_GCM,data:Kvz/5JVOwBQeOhxRuO7VHY33mwI0qkotGOJ64LzfByRjy0VDSg==,iv:JzCPemV/ZZOdQ7CI733zHOHN3wCwhS6ZgFjK1NNT9QI=,tag:ZRNZj5jp+wfvFkn5ZjZf/g==,type:str]
                              name: ENC[AES256_GCM,data:JcDRMbTc,iv:oFgSS9z2ECTPnltYnPHLVDByfU6KX5jxKlHTlOQHk/w=,tag:7/8K/3RGIEmwb1Tu2wFi9w==,type:str]
                              volumeMounts:
                                - mountPath: ENC[AES256_GCM,data:colztSMasaQFQU+iY896XihS,iv:nC4BumHTBcgovTSGhmCxOco9Zr41STDcK3sgJinK+/M=,tag:wUbE+SLujxkbJphxSQAy6A==,type:str]
                                  name: ENC[AES256_GCM,data:5IVvhg==,iv:kyyoEg0okncNroJmPoI6eiiHU9lhmC+ozLv05et8tcs=,tag:SKepmuqr/rf0wahuc2x5wg==,type:str]
                                - mountPath: ENC[AES256_GCM,data:5YfmE8lColA=,iv:g3KJ9ip3GkMGkFHfPISMHOCKgYnIv3jNpGPm/ugaXZA=,tag:QzrJCzvXJgNpZCkpQWNjag==,type:str]
                                  name: ENC[AES256_GCM,data:PkATa2RzFNVH,iv:afNtMoWXIkTMVh2/lrgFo2pLRaqI/ABzz4V1SozowWA=,tag:0W9eb5bJSBKPiXuosjJc9A==,type:str]
                            - args:
                                - ENC[AES256_GCM,data:D6n6aP/58w==,iv:HHI0WeSMS2UdP9rwi9/x7rzj7cp8AhwfL3hmnXU+GDQ=,tag://S3KQ2vLAHtDUE9YbkJZA==,type:str]
                                - ENC[AES256_GCM,data:Y9+NNtYPay/O5mzSGFLE34sj07ogqUbw/bvWSa8/P+8whg==,iv:NcP1OMXuV3CD97cSGD+F1ZKfUoslFfvnt8uteHCFchs=,tag:LQBYqV8iwYAoA2X64bsRag==,type:str]
                                - ENC[AES256_GCM,data:Xy9R8PIP9oJxtU2aNlvk50LVcDfGIJy0qSnS,iv:lIwTLvWz4CVnEJ/3gTkTc83/s66GTynKxZhIuCqlkW4=,tag:FzVwiEPDFY094TQWGeFHiw==,type:str]
                              env:
                                - name: ENC[AES256_GCM,data:vKz23oxpO4FDNVBAW940JA==,iv:IGEpGGr46P55hixeywh29GgVCtDXgGC/miIUnlDbvpI=,tag:hzdPHgYA1TUlTF++r9LpCQ==,type:str]
                                  value: ENC[AES256_GCM,data:mnl1,iv:vt3QUyRM9uhbexyyMhNHrQI4fCpHNaPJtgpcenaoy8k=,tag:zUl+5j9npxyAXUxvXurljA==,type:str]
                              image: ENC[AES256_GCM,data:BXuJjf8YQmD9zRg=,iv:6n1wbF9KWRW6sX1uLcn9RSSOcaY5HmsdqhOSKDPPgNc=,tag:rKkm+ipPn41d+51cPsNMKA==,type:str]
                              name: ENC[AES256_GCM,data:d+mUpA==,iv:PsgxQ98KpqhaeicEWWXvs8aTifUNc5CPZjD09+2xEMs=,tag:rw4Ves5GM9oCYdNNpMMpMg==,type:str]
                              securityContext:
                                privileged: ENC[AES256_GCM,data:lR1wTw==,iv:LzwiivHM93F2Kb+ishbaKAGI+yJFwdQMLyybvgr6NMg=,tag:bescRbRFroOhP2XWCGJP7A==,type:bool]
                              volumeMounts:
                                - mountPath: ENC[AES256_GCM,data:v5Vyb1USeivyBdqkZkNQ9pzU,iv:uF5WUM2pJZgRcBVsyGd5Uswu8WYYKWiWLmCW4L1pWvY=,tag:nD+VXkVxb0XZNxcJC/xVfA==,type:str]
                                  name: ENC[AES256_GCM,data:x7wpeA==,iv:lr7rZuFZEU8gecsqnQiy8UFjvsSia1etutnUqhHeZ3c=,tag:G+QBk6V9BkokBtNU10JdKQ==,type:str]
                                - mountPath: ENC[AES256_GCM,data:XZF0dmJ7dtQu2mQWJxVE,iv:1X2ukedbU166sa8hprlDiFtLqwEFJAPNfjFrD83kRFA=,tag:j8J9CtcJAnnbKAM8jloPFw==,type:str]
                                  name: ENC[AES256_GCM,data:5cKpDe1Y7NE+s8ma5/k=,iv:C4Nt6XC6wYCl+bZR4w6a/HOvExoAtsk/T00n4YhjaN0=,tag:bl+txA6rI63hXfPwQxNFOQ==,type:str]
                                - mountPath: ENC[AES256_GCM,data:wqwTwUJ2E7I=,iv:f7+kxBdf0eMjHRk97XinBHZCBNmQ2njFJGUVqOUxDmM=,tag:yK3aX6eYYDWAnOyHvlPBVA==,type:str]
                                  name: ENC[AES256_GCM,data:E1/GavSiwN/t,iv:ySfQsbPImOiom1/jACwK3LtNe/UPV53x4iFNVnh0xNU=,tag:oyxLJbv0vdYmsNZzIwxGsw==,type:str]
                                - mountPath: ENC[AES256_GCM,data:EuRl0UtjBkItMOhdeMd9yZBs8jLa2Q==,iv:3Ih3yXfy2IvlpdPkv+Lqi/ie+SswXEWf7odzfLR8QxQ=,tag:6w8k+Kb8NKD8L2TWw9Bkpg==,type:str]
                                  name: ENC[AES256_GCM,data:FDJ02JJzS8g/jxqamfU=,iv:elHhQP86NTnbaWFi6tZsjspzvZFDCo+qAcVGcbOAZYc=,tag:7FPCSWSlpdPpfyi4c/fgvw==,type:str]
                                - mountPath: ENC[AES256_GCM,data:M+OIU+yEGePIN9gISF51AKIdpL4YwiY=,iv:kQq51nhXXEbw0Xx9wV6Oag42ISsYCa7il9+WyeGc8aw=,tag:vQjGkygU1RD8KTW+gGBBHQ==,type:str]
                                  name: ENC[AES256_GCM,data:MRvqZSvnM/cEyso=,iv:8JNNk+gdRbLpTn+6F6i1f/K5VjbhmzKnQJFkRq6q5rA=,tag:xZPclP0mJFj5c3QUbnOltA==,type:str]
                                  readOnly: ENC[AES256_GCM,data:o5GTpA==,iv:8oWkTP0u6yH9rFpb6OeTCyDZ51WgnC2oG0LKXPaSScM=,tag:pnPJDiD5nbNq/36Nv+7cVw==,type:bool]
                                  subPath: ENC[AES256_GCM,data:4BzR6PNnjU2eSIU=,iv:r+d6uuEb1Wc/vo3zzswqNth6M6cTn34Ymw8IRuWQeuM=,tag:8tIU+R7gSbFMb5/FGDrygg==,type:str]
                        initContainers:
                            - command:
                                - ENC[AES256_GCM,data:JVQ=,iv:5HcMGyLPg5r90esp9s/fTrDSAClRs2RESXF00Q0EJkY=,tag:zjZUtimiUyywJv65X0aUhg==,type:str]
                                - ENC[AES256_GCM,data:by8=,iv:6C3fM721SQWvkAThuAsTDnJmyD66b1W4yzIpSSg+pwQ=,tag:pyXw2+BCo0YGT0DnOZ+EKw==,type:str]
                                - ENC[AES256_GCM,data:uVk=,iv:PCH4UMCdm4I1LYCRPxn+5FW3V4OoobKtD3fzVW8zzEA=,tag:o65IOlOGN6BsojEdAIqnug==,type:str]
                                - ENC[AES256_GCM,data:xblL4Y6yIJt9ZJSwSLo0uuQ/h/HgbG2H,iv:I3sN0TgGnF2vdmMeKW23cSs3r5F5n7yDA6hg+/MfZ64=,tag:qZrzaiedUWl//EWZ9rSifw==,type:str]
                                - ENC[AES256_GCM,data:H7EJ12sowGnhRyzFM/H3ksX9Izk=,iv:idywdOcOofc6sdSZDTLYuuv2jg5Cxhldz8fY7swbA8U=,tag:qs6jUnv01fPUs4modOIVXg==,type:str]
                              image: ENC[AES256_GCM,data:el2QQW+RVP64Ez1lG5LLpj9dfEKseYpiZ6IKGdj9lqXAXayi/Q==,iv:6ko/MHynCvl9ybiU2cELcZmWzy6dly7RRYP1f5j07Y0=,tag:8XY569vIagtvqwOcWKFMOw==,type:str]
                              name: ENC[AES256_GCM,data:bU7M1uHMEmNZkRMu8f8qrJA1JA==,iv:YisLMv+Zig/8/ELRisU6mFIGyeCHyn4yDCqTEnBywTE=,tag:BClQICXvAw/Vw4eMk4rCSQ==,type:str]
                              volumeMounts:
                                - mountPath: ENC[AES256_GCM,data:N5VStr6XgI28sCqhvklcGXtArw==,iv:z0XWMLm/CQKd9x8p54gVEtGPfQTUYOhWgvTC3092GT8=,tag:YOObVR+aGnE2RtFxI5Nm8w==,type:str]
                                  name: ENC[AES256_GCM,data:lt1jJUT1y8iHrle/x/I=,iv:VFS417chx3lZBSrMLHzddpI+15Q7fB7pIk3tmS0T9CE=,tag:sVq0ikIEaSfAzAx1JbQFGQ==,type:str]
                        volumes:
                            - emptyDir: {}
                              name: ENC[AES256_GCM,data:G4EK0g==,iv:LaC0D3NyMeZ4NUCBMbpttT3QUFUMLestyntcHMfPXoM=,tag:9wnjvFYxqujkZB1pI+TxhQ==,type:str]
                            - ephemeral:
                                volumeClaimTemplate:
                                    spec:
                                        accessModes:
                                            - ENC[AES256_GCM,data:hD4ULFkZBBK2HMxnfg==,iv:b+ffBLkcX05S+OZFkQSVfqakFp7aiXY9E5qzOZbKrJY=,tag:riFodtbhN56zOpPB3xhQrA==,type:str]
                                        resources:
                                            requests:
                                                storage: ENC[AES256_GCM,data:6H6/Kg==,iv:eRn6mvjDDRQzFbTYkXlOZpPc9J0kTR5LFzqE240/SNk=,tag:39qFNJIb6dotXYYrWY0n1g==,type:str]
                              name: ENC[AES256_GCM,data:+/O6uvTQGu5in2g7Ka0=,iv:7GbW6dazsxE3OqwKcI9oTS7Pe/q41IvaLkkcfbuAeYw=,tag:mHc7zSyJzRQoFw+n0fh3Xg==,type:str]
                            - emptyDir: {}
                              name: ENC[AES256_GCM,data:oXDZgyotOKFZ,iv:+kmA+TDlkRdTMAIwSMvSq9PerEt7Y+8gSGt5oifyCxM=,tag:0aU1LYKH3dOzPdskKb+ReQ==,type:str]
                            - emptyDir: {}
                              name: ENC[AES256_GCM,data:8jZI0h5dvZmnrX0Fd0Q=,iv:rYV2iPGpcbw/OWbodyeEOb6mV2FH0Nh8K84x1kqggLI=,tag:9Cy+pvCI6cHY5ih0HUmKDQ==,type:str]
                            - configMap:
                                name: ENC[AES256_GCM,data:/YziIgmRdpOTvG/NGcWG5vwlyDI=,iv:cevKVTU2H64lIT5FOvnvmG9jAOSLSwYzMlywmSvXqrw=,tag:uc5pDQJ4opvDSLg6rplnUA==,type:str]
                              name: ENC[AES256_GCM,data:Sqb80zR6clxVZF8=,iv:oMCX2C9YoLTlo/stX6FihfrFg2YjPIQrJr9Se2z8p10=,tag:0KcMsnXYsRFfNYpJLzzVKg==,type:str]
        repoURL: ENC[AES256_GCM,data:tIGOMFxH+y7tUow0MKCtNtMP/sYH15kb1e2lED4pa8IAFSselLF84vyLX4W1y37k,iv:bG0h11IaMQjCVB5lJT+2dXaLpCjuupTc3R60HaNPFDo=,tag:juODF6fUDpg5hKw+gbhOyg==,type:str]
        targetRevision: ENC[AES256_GCM,data:OuHfPPmn,iv:hnm2K0CT9rcF9J7Zk5betO4JlILPbQrnno6mN4aAhDo=,tag:6xfEdLjcvb4gGGHNguBjmw==,type:str]
    syncPolicy:
        automated:
            prune: ENC[AES256_GCM,data:WwZvd6s=,iv:AeoDsfbDkDIvvaz9g7gTXDrc4gLjrIN7h7sVb3ZPWLA=,tag:KeZ9lHxvChhVQgnL2jpxfQ==,type:bool]
            selfHeal: ENC[AES256_GCM,data:jzppyg==,iv:obuJ6G2IHZ31lKbDDvUxQROUVfhZV+xohexwETiUA6I=,tag:abIz3yzNoVB4oP3xNM4ADA==,type:bool]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT2t4bWNXK29naGVVNmxt
            V2FheGlTRzA4dEVmdjFrZ01WUThDdHpVU0E0ClpnVnN6MVgvUFdYL1ZJNjg1ZVdT
            QW9GN1FJVUY4c2l2dHN1d21XT3k0bzAKLS0tIHFRSnlWUGRXa0U1ZU5oQWJ6dTVv
            aWdvMlpoTFdGNG9EcWRQeUxjd3pOaDgKl1e8ZbLcKafhRwIC+YLd2omWCBOTDQvG
            uybQaQPtc5Yc+XDaB8DEQCD13h/Y9uZlTytPgDGVqujZnrrdaZDknQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T22:43:20Z"
    mac: ENC[AES256_GCM,data:s29YOAGoW+DEg9ofR31+uaas4FraWzrfnacTJN6Kl4//GW0l0msgslb1Ae2Xg3aao9BdD+6lw80rCgTa2SZLA2h5FBTSj7sscVq5A6HQnJ/I9HXZgWKfKo9C/eB3PqdT9XtNNnVupjIr99ieV7ds0Ow9zgFwcF/tW7NnyLNueNY=,iv:sknyKPv2MLHckv4k1STP5epOSy0mu0Abti863yC/4f8=,tag:bi5w3C7eA3DmTLmIKD7Nlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:gn4qu2K1OLwvlEHzMDEVx+nP4EE3UvthaXU1vw==,iv:A8zsDZucOvcS7BGDBpp0sLxEhLcU2wzXbjSw1241MsI=,tag:1pF+9OmS0sgd3ST1kin32Q==,type:str]
kind: ENC[AES256_GCM,data:WhwTL/qU+//9IvA=,iv:nIwS/phzbACTLbfyDMX3fsSHwBnsL1NWVnHCVIUMq+Y=,tag:s23QfubSGUCdL85uA2/lfQ==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:gQ==,iv:0+QuF+ZN7J8mwJ0woyM2dxVIc1tkh2N6GTeBI/ZmJO8=,tag:DPm45vdv/OiWj0ozQF2j+w==,type:str]
    name: ENC[AES256_GCM,data:Il96YZ9oo8Leq6/xoAGIWXry,iv:YXXb/B7JXZI20W13y5H7kiY6Yk90qOJjZBbNimjShc8=,tag:txaV0Z7TMRtNdNEAY36Rcw==,type:str]
    namespace: ENC[AES256_GCM,data:0RNrqFy0HNSvDmc=,iv:hkzLIEbJmU9/NH6LtZnBZjssvqRHC4+YbU9muZfCVok=,tag:4ce28By/aNx0jMnSu9KZNg==,type:str]
roleRef:
    apiGroup: ENC[AES256_GCM,data:C5P9BQvlUg3L1lWTvOE1gwmhyoOIeTeBVw==,iv:A19Vv/22LUJcESbRt19xwtF05Q/CCJNyQ8nLOxGhqts=,tag:sZc971ZkKh46kzCMGAphtg==,type:str]
    kind: ENC[AES256_GCM,data:ioiir1IarpTzRic=,iv:ch/lHMZZ+chwXKFfbcXC3z1HtwJsweCw938ToNtF29k=,tag:2YJEaFILbdA1+mKc17Exew==,type:str]
    name: ENC[AES256_GCM,data:p2Nb8cF6E2jeMBGuHRX0KVGF65z8AeGl1Lnxap2/og==,iv:A1byAqQcnJUt9O5J6MVBslKSDw3YOOaT1nA+TiEGlhU=,tag:stjcgwQ/2r1TeZXW4JvEmQ==,type:str]
subjects:
    - kind: ENC[AES256_GCM,data:yTiEIu2Abw56lCCSpuc=,iv:DMoemiyCYAOQAZX44PSOp0HnAqMVB5j7HzbA6EcTf64=,tag:CAfTfVMLODGCY+Es4owsJw==,type:str]
      name: ENC[AES256_GCM,data:3Kex8QexZMkMhrxRpdd4H6OpKYmpHo4n,iv:6VdSHTtzFnmioloXeMVygKX7lfYqNeZECh8fjipcxE8=,tag:KcW1D53a3o+RMZLo8/OjRQ==,type:str]
      namespace: ENC[AES256_GCM,data:n2L4Be2cuObZ1sc=,iv:jts7vL6MYJCwYGYWKxdLlCCKvlwugqV8TlIgU2q4+QI=,tag:M/XTQJnOqs5aR83gqvvVNg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT2t4bWNXK29naGVVNmxt
            V2FheGlTRzA4dEVmdjFrZ01WUThDdHpVU0E0ClpnVnN6MVgvUFdYL1ZJNjg1ZVdT
            QW9GN1FJVUY4c2l2dHN1d21XT3k0bzAKLS0tIHFRSnlWUGRXa0U1ZU5oQWJ6dTVv
            aWdvMlpoTFdGNG9EcWRQeUxjd3pOaDgKl1e8ZbLcKafhRwIC+YLd2omWCBOTDQvG
            uybQaQPtc5Yc+XDaB8DEQCD13h/Y9uZlTytPgDGVqujZnrrdaZDknQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T22:43:20Z"
    mac: ENC[AES256_GCM,data:s29YOAGoW+DEg9ofR31+uaas4FraWzrfnacTJN6Kl4//GW0l0msgslb1Ae2Xg3aao9BdD+6lw80rCgTa2SZLA2h5FBTSj7sscVq5A6HQnJ/I9HXZgWKfKo9C/eB3PqdT9XtNNnVupjIr99ieV7ds0Ow9zgFwcF/tW7NnyLNueNY=,iv:sknyKPv2MLHckv4k1STP5epOSy0mu0Abti863yC/4f8=,tag:bi5w3C7eA3DmTLmIKD7Nlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
