apiVersion: ENC[AES256_GCM,data:mUA=,iv:G+lOqndn0sV/YNdY+YjXD0qPKr+1+1CLDHjvkehnbXY=,tag:kn/I81ZP5aF8ZdS1stNk3g==,type:str]
kind: ENC[AES256_GCM,data:Qggne/4ZSEx9,iv:fP6cnyos1irkO+O5AVI4C0zjqQWU4RgYIRD4gQVjEzg=,tag:WbapzvzT/xIxk8bzpO1fYw==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:CQ==,iv:xePwD/XQt/Vd7m8LyMxdjyhdgO9mmk4J3bPWjwzwZLA=,tag:3k2Ph5rX0Vdy4ac3wp3QMw==,type:str]
    name: ENC[AES256_GCM,data:9Bc3G3T67U+iuzY=,iv:CNHK4poxJ/sNRfgMvcuZeB+MNGOFfv5vJdGN39rtnQU=,tag:TWHkZWyWCz2tcKaUe5sZbw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRnhRVlJKalBzNXBBVUxR
            U29BdUcvNkozdjdmL3F6dkZCRk5PM3VjZDEwClM4S0VNcG1rYXB1bGFkTVVjZmhZ
            UVZjSTd5bXA4bklBLy9hSk5JSjVMMGsKLS0tIFlqdWs5WU1CVU53QmxLM3RnQVpy
            OFhuUWhCUnVqeDhWZ3YxRE9jZXBnSkUKnKzFPVjsghMHHor4NsAlK/UhdxkJ/aAO
            Y+OrdyB1c6Lpj7ou3y2pn13pS8QZ5uKNGBcziCzFF3cvsN7UDug7xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T04:18:32Z"
    mac: ENC[AES256_GCM,data:sAlvQ2ZdkuwHxW0Hu1EiJpqQSSaWcbuLdD2FoQQSNgSWs5oaYzn3SIdvtZ/kjAhTqPv/Y1/sxDqIscmJB/Ef7ivNr8A+lzC2sil6j9X7/9EpcwItDOV2gn5wHBRX1Wj0TenkhYWThAmU4cfud0UA8sjbITQ6UGNGoMueikZrL0E=,iv:JgpwhRyTdxirzdbKEqtZbYJmL4kVPXW5gLs03+LwVX8=,tag:dwfzCAAljx44E+zRffDLKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:PrE=,iv:/wB5hV9Y5dQiUmMDIubWLRBHD6oG4qudKsX981jni1E=,tag:V/eZrq9W3mUY+/uBRAmZ6Q==,type:str]
data:
    daemon.json: ENC[AES256_GCM,data:MOwMcaxE978swlb8TgvO3rDxAmP7KHylNgJG80pAfGe6skqEVrG89pqyx/YCwi09yeKt4RGwAMiszNvheWbSLhdlXUktyo/sWZSIVqAS68EYgtQfiwJO6PKpfWeeqzvg/ME4cpranitFv8XPCdAAK2SU1ciQB9WEWY2YJ6XfVcOip2+n4WgdnCEjbhwXRXQr6xdZklTI5N8pZw97nbJq3GRY/ojw+YWfZuw0eaRBLJuHZZzcwmsjEryhifkM80qlWzq8+TDNCl1Gakk5icg9DNJqITt67dTwtbNWFSPGkvnqNVgpWoF6PMyeWq5Pnd7IclXTf2AzMtUZRIOKZNycmtTUs1HhZjVHj0W+FlKVdXADwDgRJ8gfLomknKl5G9RHx3lk1fYjAcr81F6E0tIrdk0A7ebxjZC88frn9FhJJ89awX55Bm7Iuux90wqwqhSQL1cM95Q0o49P42E5GP8bMlay+90NpjkIuHdtRv4Ffgnk7e2907NFNtt/k/bwIA==,iv:jyPCq8YRnYdES8w94X1oUr2eV3lzPgnImOXI/OBxm4Y=,tag:gzpAqtUTgUOLevn20N/eEQ==,type:str]
kind: ENC[AES256_GCM,data:RUUBWDDCGwB4,iv:bj+eCyGo7qkMDANYsG9C4JHWH3gLCxswuV7rky8UrV0=,tag:2vR7mh0rE76OWKnb7ghXKQ==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:Bw==,iv:vh/whz0J+H2ByeCy7Nk87YmlirbqVvU7X2zRuWEZ8bs=,tag:S7AQUOlVkFUCjFr5iE6rhg==,type:str]
    name: ENC[AES256_GCM,data:jW6KDi7s3QKX3QAfwYz9M9XYMRo=,iv:APMZSLj3n57w19YgSZ7Q2kl0OlAY6zPvy7uP1DtaGlc=,tag:IdyuoTD1fpxOdmYu6ZSjmg==,type:str]
    namespace: ENC[AES256_GCM,data:NSWcQeVUOaNTG/E=,iv:32FGW2BhMeK1u8gkU26LBaNBU1DPX+9cINw2cgp+kHE=,tag:KirYG0o/iPETokqpl5PsHA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRnhRVlJKalBzNXBBVUxR
            U29BdUcvNkozdjdmL3F6dkZCRk5PM3VjZDEwClM4S0VNcG1rYXB1bGFkTVVjZmhZ
            UVZjSTd5bXA4bklBLy9hSk5JSjVMMGsKLS0tIFlqdWs5WU1CVU53QmxLM3RnQVpy
            OFhuUWhCUnVqeDhWZ3YxRE9jZXBnSkUKnKzFPVjsghMHHor4NsAlK/UhdxkJ/aAO
            Y+OrdyB1c6Lpj7ou3y2pn13pS8QZ5uKNGBcziCzFF3cvsN7UDug7xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T04:18:32Z"
    mac: ENC[AES256_GCM,data:sAlvQ2ZdkuwHxW0Hu1EiJpqQSSaWcbuLdD2FoQQSNgSWs5oaYzn3SIdvtZ/kjAhTqPv/Y1/sxDqIscmJB/Ef7ivNr8A+lzC2sil6j9X7/9EpcwItDOV2gn5wHBRX1Wj0TenkhYWThAmU4cfud0UA8sjbITQ6UGNGoMueikZrL0E=,iv:JgpwhRyTdxirzdbKEqtZbYJmL4kVPXW5gLs03+LwVX8=,tag:dwfzCAAljx44E+zRffDLKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Pl22MeDRIArRvFcXQCulQAL/A6w=,iv:FanhmLV8xjMsx4cBoFqnyuzrRZnVTYYBgain8nr/uLI=,tag:RjGhJ/Q22M/VwlaRAUxYdg==,type:str]
kind: ENC[AES256_GCM,data:npm17tKrUFDqlrs=,iv:HrGE7A1nxu+h8K511hB/00ulm95DFj7dVIHX/BcDVjs=,tag:F7Cmo3TtZflz0x/Zmosekg==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:8Q==,iv:a6H3dDuAglx1HV/P77L6knU3Hgby0493MGVPYNPh/gw=,tag:+tsZU9E364J5bjbqVo7p0g==,type:str]
    name: ENC[AES256_GCM,data:O/cnCUKx7dAjPbUElwk=,iv:8lC0ZCuZmhQCFmEULcLx/mdZxEY0ilepM9jNBD6H6cs=,tag:bQkZ6ZXXygdmZgo16c/6Iw==,type:str]
    namespace: ENC[AES256_GCM,data:4BA68oJOfXB5znJlK3HjsA==,iv:3cIMgsR0mQd15/PZnnBEG/+3LcnSp2rE0O1A3vYp3V8=,tag:lRmy4EvY4WVFnApfx5jYLg==,type:str]
spec:
    destination:
        namespace: ENC[AES256_GCM,data:o7ghnAgJoQHN+zk=,iv:l5iMk7OhOGuHTTCtafxDhm8ynbkcwlIuZeGyR2RHgFs=,tag:Id2ar93Rtt0s5Iz5nxswYQ==,type:str]
        server: ENC[AES256_GCM,data:lp1VLidZFkvXK+sFL51ma2VbzF88pGorWBW6OsiW,iv:rdkLC9ARjs/KmLuu6DebU1oqEyCy7Jay/u9ezlas2X4=,tag:IQcRboCZQMiEkA1T0mYe0g==,type:str]
    project: ENC[AES256_GCM,data:mrR3LI0vaA==,iv:rGCt2fV9E2kn2ntCgJNbgCXyoMwRgbk4nJjweO5msjs=,tag:kSGa2bJ/a15kcx9n6vMNBA==,type:str]
    source:
        chart: ENC[AES256_GCM,data:5dcQzejKYNk35fq6kg6N42KSISs=,iv:I05RyfDT3mAp2yDhwKUgdfCXdMzKjQ11ekjziRIdLWo=,tag:I53XGsp65xnbV7ETjC/RgA==,type:str]
        helm:
            releaseName: ENC[AES256_GCM,data:5DN/,iv:KBJ/+9ReADnU8u3NUDzmeLaO6dk0sba7LNRWH5TPBjo=,tag:7rZkLdB920OOVcA6eAcsAQ==,type:str]
            valuesObject:
                controllerServiceAccount:
                    name: ENC[AES256_GCM,data:Z0OJk2cbXNo0ypnsctRpthUqKj3k,iv:dMQqNHJxHqTZV3aIG5BSa4II3FoIJs6Acxoqm6wOvxo=,tag:4UuR8ryEcGfd0BB9uuy+BA==,type:str]
                    namespace: ENC[AES256_GCM,data:OQQONymOgcstXBg=,iv:OuYosxdK/kb1v07q/wrjYm1I/8nrk956PD+L3vFK40Y=,tag:USw80qyIFH4CQK+kid+vcg==,type:str]
                githubConfigSecret:
                    github_token: ENC[AES256_GCM,data:qEHPLcBmyx66Tg6VfAGbnGibrPBgSgwVT8BA/iqO+mcxJrfczf96Og==,iv:BKS/WNeXRAYrpZFbR9uSz50jZBGpTMNW4AqJ/mtVdYk=,tag:bPkxcFPqJ9KlmScHCkQ9hQ==,type:str]
                githubConfigUrl: ENC[AES256_GCM,data:kvsl0PfUnImQbe5Avf4she6benT7lb2SSsUjejcT43OV0g==,iv:k3+X5w1F48exDAfSNq3SSvJoOUQKh7XMxo0xlowAXeM=,tag:ym/bDSTdiNfbfOxVxJidLg==,type:str]
                maxRunners: ENC[AES256_GCM,data:Ow==,iv:ZEhSXpOumdXsrjFNjShAPvlVPehBJKK05p979gPPQMc=,tag:Z1IptpFYcA+VeVJw1Phj3w==,type:int]
                minRunners: ENC[AES256_GCM,data:rQ==,iv:f+xFQ+V3RBul3fjPFYlLxZ2HKjD23RXy+Ri/AP11BGU=,tag:OqhGlgB1deycJoR0A2Xiug==,type:int]
                template:
                    spec:
                        containers:
                            - command:
                                - ENC[AES256_GCM,data:AHuhZSuY86uDyz4sVkwEYN51dw==,iv:bN0houOSnACJb4wzJ33tYG/+N5Y3G/uvN3S0VwpDORk=,tag:3B6ULvE2BiYrmGObJN6O2g==,type:str]
                              env:
                                - name: ENC[AES256_GCM,data:u7HBEWYT1HFxdb8=,iv:ysXHOtA2PF8xJgRVu3JiROVkvBWlyPLNG4XXevX73n8=,tag:ny28957oy18926wJeEsVbg==,type:str]
                                  value: ENC[AES256_GCM,data:H37FZr11evxvRNtxI8cOoQdRA6p113vpcXut,iv:qRUHFVkrdIhs795LECnrl1I9LRVoFn55kDej1kjAs2c=,tag:9UsLKzz35DHqohl1+nMpog==,type:str]
                              image: ENC[AES256_GCM,data:ZXORpRqF4EHhgzNbP8Xy68os3PhHwTUOC+0SoJw2YQ5Q3CnHaA==,iv:IAHQ1ri94CLzT/A8ir/PWHu1kcz4k8/a9+GjAD9W8pY=,tag:8bbE+0UvHRIfDoRSNm3E1Q==,type:str]
                              name: ENC[AES256_GCM,data:oH2G0nWG,iv:dDyjKFw+LOyhLHgs0Lv4wGH52NgMlrQ2UMooSgLCE6A=,tag:AMLUqUIgXCneVvsg729dPg==,type:str]
                              volumeMounts:
                                - mountPath: ENC[AES256_GCM,data:vcISKpuI91nYgFF9mCQm7Ql8,iv:Eq5xZJKPmyDPalYyZ/ibdqqdS/UjqeEn/srJg10RoGc=,tag:pqynIHovS3VFHuXWR6/iTQ==,type:str]
                                  name: ENC[AES256_GCM,data:VtjtDg==,iv:Zf8d1J2m0U7sdvQJlEx3P9p3GygIa7ZEqJjSTkDkg0g=,tag:afcvapQM7Abg7GzqzS3CkA==,type:str]
                                - mountPath: ENC[AES256_GCM,data:Lxqig6/GsSE=,iv:4gUmJvEI+k+VqMYx8qSC93S4n2U0hfoCIurWu4p2Aq8=,tag:hwjMQsG4q5cc47m6wBd6Ww==,type:str]
                                  name: ENC[AES256_GCM,data:PnveozBIRx2p,iv:4GusEUNLOkv9xOsiPgW4HjuxE2EG6Az3WJwu/jQc7bg=,tag:FXvGWu8CygjKQWLqKPzbeA==,type:str]
                            - args:
                                - ENC[AES256_GCM,data:LqTfx6MG8A==,iv:pC4KjcrAsMGq+vL0eskcNVdBm/C9z1A6dqFlA6irxfo=,tag:NLwAMyytGzeojmYY0wtt6g==,type:str]
                                - ENC[AES256_GCM,data:FJI7G6tWwB8F2rwu8qoesXfRtgfRK1YUQML7Vx8IP5qqkA==,iv:x48A7BUkOAjhl2Ie3KzrzaQoQ/1PHDDxh6Iam5NthU8=,tag:J/uTy61AZMvSm0znoUR4cQ==,type:str]
                                - ENC[AES256_GCM,data:E46hVrjUxEzUt+5AgPElqubvIQSXCL+WBkip,iv:AgDFYytK+ZMsavGrMV8qDbWoA7BxkaqqoLKbE0Q52R0=,tag:OoGACoWreyGqC8zTkPkLKg==,type:str]
                              env:
                                - name: ENC[AES256_GCM,data:xBddt7rLZQZ1lwDkuB13SQ==,iv:nBJGPJSprYZu4KTSHxuCgS6dOKge1+JRXuj4rAfITUY=,tag:99J4G4I8+2GzPGg4JX4xCw==,type:str]
                                  value: ENC[AES256_GCM,data:vLJg,iv:BAqWHE6yJDpPQyRCxf5MeuexLgvZj9lDpTHhp1JJm1Y=,tag:bUWcSDIwGFXdcUq8CLDTeQ==,type:str]
                              image: ENC[AES256_GCM,data:6oIs4vyx5vibHj0=,iv:bc+pLQUXcSncjuVTW1eSaxD/AnHUAAUBxlZWQF7EmA0=,tag:TtSTeeCxmyJQIQcFTFs1FA==,type:str]
                              name: ENC[AES256_GCM,data:5QXZSg==,iv:6DpUk9KWSFonCOVBRWR2C/xOtC/U0fDsiXR5ZQbHqnk=,tag:PRNulQjcJrND3xJm9H9C/g==,type:str]
                              securityContext:
                                privileged: ENC[AES256_GCM,data:8WcEOg==,iv:k2kt33n0yLorZX1h/0VAiKzGKsD1ULaICRMGdzPvEiU=,tag:5WtxL/j3Ow0X35Vyo4nlQQ==,type:bool]
                              volumeMounts:
                                - mountPath: ENC[AES256_GCM,data:PieehPyTIEZ6uwrrUzt81l7s,iv:yrTSmrKB3Q3Tm76mKeemEDs0jzGc5Qz2igU7pYEVH8o=,tag:cUmn8aZag2y7ALFOv1JyKg==,type:str]
                                  name: ENC[AES256_GCM,data:YqIPHw==,iv:TEiO3JIX+ba5GRs/yy5oLo01LQJVmHB4IDW3VOHY090=,tag:IHg7+6veShPmbd5xzAARRw==,type:str]
                                - mountPath: ENC[AES256_GCM,data:dVb/3zRKL/GqFHE+uC2h,iv:8MWvaCbWJ1HifeG6GQc6gGOC6o21xqllUDlENMlo1Fo=,tag:MNS09GHgCoRTAk7FoKD8GA==,type:str]
                                  name: ENC[AES256_GCM,data:zOIroed1AKTOEiMzJps=,iv:2nQ0w6SHvEynZ1JzizLDnmZ9Eiayq2npVBVSiWqYqx4=,tag:SopJkmtaYrwZW6jLbqvq4w==,type:str]
                                - mountPath: ENC[AES256_GCM,data:wrvfjbgawxs=,iv:vINT4ZFflZ/VV8Q/DVejfDxAlymO1bqOk2umW0STyE8=,tag:EVqkyPWZBVNniZD1AwYATw==,type:str]
                                  name: ENC[AES256_GCM,data:pnXQd5tWvpOS,iv:NuCtEMgfMor1L3NAQB0YKWAM7IKBcu1rOTth72v1do8=,tag:1N1FLG+TYLN0mkrclKPzIw==,type:str]
                                - mountPath: ENC[AES256_GCM,data:hhtgEdMjb+c9KvJuNxIYt5k4p2guew==,iv:joKn7ls+CFUkRqXUpkoU/xPRknxzls8SniofLR+1iLU=,tag:ReAt6GOfWCRLkjDwl8Kxog==,type:str]
                                  name: ENC[AES256_GCM,data:WtBToJDPyCuWSfvDTlQ=,iv:m3BDXqKytDpkuiHWkOQuSV9nY9vg9HbJpEME4E9MSEw=,tag:/GZjEo50ocOIZRbg2O5oIA==,type:str]
                                - mountPath: ENC[AES256_GCM,data:zM0OEG9hz6qUBPsnoG9g3f6x2+G2Ks0=,iv:BGuoVZTKUweZw9XnMWKjsl1U25gutayJ2Q2uSW7exeI=,tag:5OvGDIPrTnvc1PYVeuZnuQ==,type:str]
                                  name: ENC[AES256_GCM,data:wKiwwXT3z6J3C+I=,iv:CkSW3EPZs7JV/uv3amj5/je8QRb3PN7Jp1scBx7o2YM=,tag:aBtMTR519A/rV5DHVqurCw==,type:str]
                                  readOnly: ENC[AES256_GCM,data:o2Sfiw==,iv:n1CS5OHn2dQHYRlCpnW+trHjhOIe1Zaf9lt5YYGaPI0=,tag:ZIgms0v6GrzhFFtWe8mURw==,type:bool]
                                  subPath: ENC[AES256_GCM,data:PVPl6wX1WkRLhA0=,iv:Z7TQt5IeSjSbJ5C0JQ7TGuiXS+vQCMymkUbQTkJpLNY=,tag:CKkKQGJkIMcYDpgUrXwcJg==,type:str]
                        initContainers:
                            - command:
                                - ENC[AES256_GCM,data:Y4o=,iv:HPvmGekWsljIN6GJDDOBM65XDquGHaontRVDgjqBJ0I=,tag:z30MeD/XxBKhheaQYrbF6A==,type:str]
                                - ENC[AES256_GCM,data:yJc=,iv:ml7Cd76tR8z+Lj1PcYRo1IisW5h3yotI5/1QOh7ld38=,tag:Hnd4tPm82fnE9c+JW1Ek/Q==,type:str]
                                - ENC[AES256_GCM,data:eOw=,iv:VYC+SDQ5uF51CQbqZZpGEA2PfWR9Iy+ctzToviqhOPU=,tag:pz1k/wGNKTur1oBxf/sttg==,type:str]
                                - ENC[AES256_GCM,data:BXz98eo66Ac6tCrNJaYS7Es1EgIs44rp,iv:Ft9XG/v1vmZ4PoCntIqWqCbyzrKjVXrDWKvlD9xmjCw=,tag:GOpfLsyWdrN9Df7vqzRMWQ==,type:str]
                                - ENC[AES256_GCM,data:N8wwUH0uX9lA4zbOSLQxP3tNyds=,iv:w3hFbZaMI/Yyqa4Zg05BDx2zpkUQRlnGow+rZgApyFs=,tag:X0KwipQXD5iKGe9fF3sHLA==,type:str]
                              image: ENC[AES256_GCM,data:DrQHIk94JlHCQc/GSvDjOMx4qWSKSyS2xlnpnQelosHAeo5UTQ==,iv:oKPgeIi3TBAKYzrNq8SVU+tvVkCb0XIq+n2dhEz4ZPQ=,tag:+vCUbNJxa21HQto4Lw2Q+Q==,type:str]
                              name: ENC[AES256_GCM,data:eDd1CKOLSLe63RQxJO/uiOvugQ==,iv:HWbR4q5zWeIVbbD4wByy1GrbWPpf2SSyavPUpbg0F4w=,tag:y2QpDh6P11SJ6dSShYENsw==,type:str]
                              volumeMounts:
                                - mountPath: ENC[AES256_GCM,data:ONrJClPH/Wn8nfD9SRjBjIASBg==,iv:zaW1MDZ8hukIhfoRkDIAYRJDoL5IK+ogVpojgihCU5U=,tag:TONZYp64Gst+N3wd+degNg==,type:str]
                                  name: ENC[AES256_GCM,data:qkc+5wX4sVOCcJcZ7rU=,iv:1j8LssehNOtaJtP+WJblwJBe3RFnxvd6leS35m6Ouj0=,tag:AN7aniok0WdZn/TpivL8dA==,type:str]
                        volumes:
                            - emptyDir: {}
                              name: ENC[AES256_GCM,data:fn82SQ==,iv:+Qg91Met7FFcaXJgV136Mh0koKmLslylja353/UhhmE=,tag:Kygr3WsimM/6GYbrRMm8vQ==,type:str]
                            - ephemeral:
                                volumeClaimTemplate:
                                    spec:
                                        accessModes:
                                            - ENC[AES256_GCM,data:/bhN8ORGFE/CGga6Dw==,iv:KIjXVjaCJIu5GrFP2GWQ2Zjc1klhgEm5KbWVvRKF3ZA=,tag:mi5ZsmLmURK7X1V0t0gPiQ==,type:str]
                                        resources:
                                            requests:
                                                storage: ENC[AES256_GCM,data:YInWzw==,iv:4/Sxeu1ZSA005C4Co24O+gmx3MYxRx2edhSU6Mmcizw=,tag:ckS0Xt/dYRVSbHAtDeKp+w==,type:str]
                              name: ENC[AES256_GCM,data:3ETh96TTj3Cn7/EZIvY=,iv:6Acw2TJryM2keYQSas69+0dLnWGPucKZvtIohnuYtOY=,tag:f5BNUF3OhRkeAf8vVefwMA==,type:str]
                            - emptyDir: {}
                              name: ENC[AES256_GCM,data:CZoDb8zvDJuE,iv:d2yVTjnWTOUBN1mUqMoBFVs6IQf+XJqoOcwWe/DRang=,tag:j8L3ncm4ThH5ZtIXOy7uag==,type:str]
                            - emptyDir: {}
                              name: ENC[AES256_GCM,data:nT0C3TH3hdwvKgnGkHA=,iv:ye2gWFOKdVJv3uFI6Lu60V8o9OhSUZXmEoKiNzjT/P8=,tag:EChH+RaN9c/xaBggrGfueQ==,type:str]
                            - configMap:
                                name: ENC[AES256_GCM,data:ouxItvJDgX2GLblEgk2rAA71d8k=,iv:R/oQjtNBi4BiRuO+5qmA7MhesVJvisjwY2I/LlJY1Wo=,tag:jvPvKIP6ZIX4u+uc3mhSIg==,type:str]
                              name: ENC[AES256_GCM,data:hd98qP/4la6Ij6M=,iv:o2vN5ur7+/vFEyMSWtAsEfY9nBGyLz2Khq7y08bZZrM=,tag:6y2supZJvFXZmFy+74pQdA==,type:str]
        repoURL: ENC[AES256_GCM,data:ng/MDQJHMLYcWsb8dH1H8BG3yXQ0EF5zUqrugqlLV8LWhx1/cQgqkiT+cBr1kC3O,iv:fD1NdbyUKh+oxeANOH9sjwHzBT8w3U+XVJ34GC0eLo4=,tag:jBoqDM9WXkz8lO8LLWRp7A==,type:str]
        targetRevision: ENC[AES256_GCM,data:4LsT+P0t,iv:cFyP+SlC8o15ilV1WP/uxJAtJ8/NJG9h0NmI/mSW82Y=,tag:nUZOujQP61kTxLePLn0HLg==,type:str]
    syncPolicy:
        automated:
            prune: ENC[AES256_GCM,data:3zSfMzE=,iv:d9BQ1LyJDfnHxo8G4Hl3H36cA9umdSCOXaF8Vryg4Fo=,tag:hjQTCWu41lm6kcSFU+XmCw==,type:bool]
            selfHeal: ENC[AES256_GCM,data:DsVPkg==,iv:CHvHvosBsz+2hy91jmFcRxiuv+slO1RaXnsuWbQQPfw=,tag:1YIW/cWFOwCwEMXJboJD3Q==,type:bool]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRnhRVlJKalBzNXBBVUxR
            U29BdUcvNkozdjdmL3F6dkZCRk5PM3VjZDEwClM4S0VNcG1rYXB1bGFkTVVjZmhZ
            UVZjSTd5bXA4bklBLy9hSk5JSjVMMGsKLS0tIFlqdWs5WU1CVU53QmxLM3RnQVpy
            OFhuUWhCUnVqeDhWZ3YxRE9jZXBnSkUKnKzFPVjsghMHHor4NsAlK/UhdxkJ/aAO
            Y+OrdyB1c6Lpj7ou3y2pn13pS8QZ5uKNGBcziCzFF3cvsN7UDug7xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T04:18:32Z"
    mac: ENC[AES256_GCM,data:sAlvQ2ZdkuwHxW0Hu1EiJpqQSSaWcbuLdD2FoQQSNgSWs5oaYzn3SIdvtZ/kjAhTqPv/Y1/sxDqIscmJB/Ef7ivNr8A+lzC2sil6j9X7/9EpcwItDOV2gn5wHBRX1Wj0TenkhYWThAmU4cfud0UA8sjbITQ6UGNGoMueikZrL0E=,iv:JgpwhRyTdxirzdbKEqtZbYJmL4kVPXW5gLs03+LwVX8=,tag:dwfzCAAljx44E+zRffDLKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:UOE+IgNjjXkOWipCnKkwDGWwO2PjsHFYIYcOPg==,iv:sTnJpBJDCsAuc7pWDEkNQ+HuYum6eI2DoJ99TQhPOpg=,tag:fy8gikIw1kfXBpE+ZZSxrQ==,type:str]
kind: ENC[AES256_GCM,data:gAjD2A+ifk6ES5w=,iv:ZRkyTwdH3tEwC4mbQ4QnPTMQZ8Uep5Cv7u6BMBxkUkA=,tag:b30e53a3dtx8F7AjYiBG+A==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:HA==,iv:NRGNsIWDHPpfco516z4M06vEEgPSmImuRJYvfWH8Rr0=,tag:u6CcLRVJ0c6mU/urrtigJQ==,type:str]
    name: ENC[AES256_GCM,data:ZyeDbrJ82o2Sxd9iF0WxFTY5,iv:tHeYjnSUpeMNwRZ6+3wD2AbxlfV8ZZcttOGkd/sPJH8=,tag:Eo+rs0fjRtVK410ZH6290Q==,type:str]
    namespace: ENC[AES256_GCM,data:xL9OuYzYHylLW3o=,iv:SfFYWUw62ayialnKCYXsa/axQQ9HH0GPzbKcqDnTHk4=,tag:TchrsasJI44ySHYzS55swA==,type:str]
roleRef:
    apiGroup: ENC[AES256_GCM,data:Z0KWebsk8l7wcGugE7BCT3FMUDsfq/4rVg==,iv:z7OvX5W5CZj4kaaqEEVhvsoILOBCqcCJ1B8THaM5jfY=,tag:ViSDRd15IEQx7ghS10+igg==,type:str]
    kind: ENC[AES256_GCM,data:RoAB+70d/fh84pU=,iv:MuFzOh9/9qRYYugiQLdLOvHUusEUzqacE7LK9MUr6Is=,tag:7O/MlT5gs8ESTOby6mPflg==,type:str]
    name: ENC[AES256_GCM,data:CvDTw41DOeVA0DHmld0k/mM/6IB3+Pfp8O03lJYd5A==,iv:cTtL3EyA0HPvwUZEga1oTD2ZcRtKh+VBReBma1kZVTU=,tag:nF+TK+3p9I52IHO9UNW+9Q==,type:str]
subjects:
    - kind: ENC[AES256_GCM,data:esEyAc7AfB42h94xbDA=,iv:+c2MiWf1qh6NJdHtIG24yDk8n+J/tNky4DKVxx7vNiQ=,tag:BAT3UuhguoDK8ymVD4679g==,type:str]
      name: ENC[AES256_GCM,data:Ym2XCI+599wlbhYNgWyviHPaX0R14VMc,iv:OF82DFHCW9Vy8kDIsFfNAWQ23fvH5X2W6l13GJGR4pQ=,tag:g+Pwa0ebHlMqkz6gZ5oFhw==,type:str]
      namespace: ENC[AES256_GCM,data:MP/9w9ppwifOWMI=,iv:sWG/ogOC1YruC4uD22s+CA6XMHI4wRX6yW1HaXYsblg=,tag:PWK+XcVQsocQK9lOtTcrpw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRnhRVlJKalBzNXBBVUxR
            U29BdUcvNkozdjdmL3F6dkZCRk5PM3VjZDEwClM4S0VNcG1rYXB1bGFkTVVjZmhZ
            UVZjSTd5bXA4bklBLy9hSk5JSjVMMGsKLS0tIFlqdWs5WU1CVU53QmxLM3RnQVpy
            OFhuUWhCUnVqeDhWZ3YxRE9jZXBnSkUKnKzFPVjsghMHHor4NsAlK/UhdxkJ/aAO
            Y+OrdyB1c6Lpj7ou3y2pn13pS8QZ5uKNGBcziCzFF3cvsN7UDug7xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T04:18:32Z"
    mac: ENC[AES256_GCM,data:sAlvQ2ZdkuwHxW0Hu1EiJpqQSSaWcbuLdD2FoQQSNgSWs5oaYzn3SIdvtZ/kjAhTqPv/Y1/sxDqIscmJB/Ef7ivNr8A+lzC2sil6j9X7/9EpcwItDOV2gn5wHBRX1Wj0TenkhYWThAmU4cfud0UA8sjbITQ6UGNGoMueikZrL0E=,iv:JgpwhRyTdxirzdbKEqtZbYJmL4kVPXW5gLs03+LwVX8=,tag:dwfzCAAljx44E+zRffDLKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
