apiVersion: v1
data:
  daemon.json: '{"registry-mirrors": ["http://registry.docker-registry.svc:5000"], "insecure-registries": ["registry.docker-registry.svc:5000", "registry.docker-registry.svc.cluster.local:5000", "image-registry.openshift-image-registry.svc:5000", "image-registry.openshift-image-registry.svc.cluster.local:5000", "10.217.5.181:5000", "default-route-openshift-image-registry.apps.makeitwork.cloud"]}'
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: docker-daemon-config
  namespace: arc-runners
