apiVersion: v1
kind: Secret
metadata:
    name: arc-runner-github-token
    namespace: arc-runners
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:+9A1Z4eqTEAF3ZdU1WiwPpeh0kAmtPewVDElVnaayJc4f4gtzocdWw==,iv:p6blbfUU0y61dHU7pMsA+8ylEqlfs+IiK86DTNkvxFM=,tag:HkoWhbdnj5jjzTdnw8bR6g==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxS0U2QndvazFFQ3FKdXph
            aWNyOWRjSHluMTBxQW1PNmE2MlFsaERsMXh3CjJ3UkxhWndTMlU3cmhINnBjQUxn
            S3VYNXk0SG9pWTliNU1HWnVkaFM1N0EKLS0tIHRLRmFjazJXc0REWDV0dzJGRm5L
            WHNKcjJxcG96MkE2NDFIK0FVdE1tVDQKEgyWOAJkA+gYvz0I1iFzDRpWcRrSAqVV
            3YKXiR3lpieppa8zh1UFU0MWCwRShflnSkdgvXYl8A5NTVzzzrnnkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:5qAnuYIGLQIfWmGZny5XQke2YA6qTvHbInSKcuxkV5lMBy5tie6h/zgfNyft7SiaWzPi6doIAia7LJoLANvC+0Rh7N4Ka9Cm+wrYY8KMAyjjhlk9aE4qTnLFAo8A4mwvtHspufoqd7LuHwA5D5UCLnEVz0lhSAN2YgKiczAUC80=,iv:z4Tg1Ad9cPEyLrOWP2XSnSOJWx6gXkOhpb6S3bc7SrA=,tag:ut4/CXZKXMDNQTeqrHwRmw==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
