---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imageregistry.yaml
  - imagestream.yaml
  - dindrunners.yaml
  - registry.yaml
generators:
  - ksops-arc-secrets.yaml
