# ArgoCD Application for ARC runner scale set
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: arc-runner-set
  namespace: openshift-gitops
spec:
  destination:
    namespace: arc-runners
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gha-runner-scale-set
    helm:
      releaseName: arc
      valuesObject:
        controllerServiceAccount:
          name: arc-gha-rs-controller
          namespace: arc-systems
        githubConfigSecret: arc-runner-github-token
        githubConfigUrl: https://github.com/makeitworkcloud
        maxRunners: 2
        minRunners: 1
        template:
          spec:
            containers:
              - command:
                  - /home/runner/run.sh
                env:
                  - name: DOCKER_HOST
                    value: unix:///var/run/docker.sock
                image: ghcr.io/actions/actions-runner:latest
                name: runner
                volumeMounts:
                  - mountPath: /home/runner/_work
                    name: work
                  - mountPath: /var/run
                    name: dind-sock
              - args:
                  - dockerd
                  - --host=unix:///var/run/docker.sock
                  - --group=$(DOCKER_GROUP_GID)
                env:
                  - name: DOCKER_GROUP_GID
                    value: "123"
                image: docker:dind
                name: dind
                securityContext:
                  privileged: true
                volumeMounts:
                  - mountPath: /home/runner/_work
                    name: work
                  - mountPath: /var/lib/docker
                    name: var-lib-docker
                  - mountPath: /var/run
                    name: dind-sock
                  - mountPath: /home/runner/externals
                    name: dind-externals
                  - mountPath: /etc/docker/daemon.json
                    name: daemon-json
                    readOnly: true
                    subPath: daemon.json
            initContainers:
              - command:
                  - cp
                  - -r
                  - -v
                  - /home/runner/externals/.
                  - /home/runner/tmpDir/
                image: ghcr.io/actions/actions-runner:latest
                name: init-dind-externals
                volumeMounts:
                  - mountPath: /home/runner/tmpDir
                    name: dind-externals
            volumes:
              - emptyDir: {}
                name: work
              - ephemeral:
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 50Gi
                name: var-lib-docker
              - emptyDir: {}
                name: dind-sock
              - emptyDir: {}
                name: dind-externals
              - configMap:
                  name: docker-daemon-config
                name: daemon-json
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.13.1
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
