apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ansible/awx.yaml
  - ansible/certs.yaml
  - arc/arcrunners.yaml
  - grafana/grafana-admin-secret.yaml
  - grafana/certs.yaml
