---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/grafana/grafana-operator.git/deploy/kustomize/overlays/cluster_scoped?ref=v5.24.0

patches:
  # Drop resource requests/limits — single-node cluster doesn't need them.
  - patch: |
      - op: remove
        path: /spec/template/spec/containers/0/resources
    target:
      kind: Deployment
      name: grafana-operator-controller-manager
