---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  # Ignore fields on CRDs that Kubernetes mutates after creation
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
        - .spec.conversion
        - .spec.preserveUnknownFields
        - .status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  project: default
  source:
    chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.13.1
    helm:
      releaseName: arc
      valuesObject:
        metrics:
          controllerManagerAddr: ":8080"
          listenerAddr: ":8080"
          listenerEndpoint: /metrics
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems
