apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind-systems
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZkU2SlBMd05hWitlVnZQ
            cGIxNURpRlhkZnBjU1FpSGZaQit1cGR4YkhvCmN5bm1wZk9qb2dTdVVaeGxQSWVK
            ajdoeVdjV05aMGo3dW9wY0Y4NG9XODAKLS0tIGh5Nm5PZytkOUh0Ym9LQmhsZStR
            YTRDdGYyenlFVDJyQVRlaDRVNUhRN3cKbYt2kYBE9JT021+lZ75CEGFc89+zhZcj
            QGsurd6egPwCEgoKYLEEMwalRbk4TAqK4OeYjRjRNsG8k2I0ipSr9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T22:24:30Z"
    mac: ENC[AES256_GCM,data:3C1fziZsm8VNE2/4bz+PnSerH0qEGizo5Tn3zlha1Ee52OYy3F0EDWCO1Cr77b0NaTFhw45I75EmUpnSyFiDlem+g8ZkipYX/FtMYMKV9MO8RndTYbgRYsj6KkjnRQVOy9vPDi9FF3hF83y01dJ5Nq8NX3ATP1Or5lrtbvZ/0qk=,iv:7ceIeyEMOqC3yrrtDZYsKDKf2O/PAUkr0EFXuugbnKs=,tag:wh8ZNDTU0tUUmuonHPpSlw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind
    namespace: openshift-gitops
spec:
    destination:
        namespace: arc-dind-systems
        server: https://kubernetes.default.svc
    # Ignore fields on CRDs that Kubernetes mutates after creation
    ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jqPathExpressions:
            - .metadata.annotations
            - .spec.conversion
            - .spec.preserveUnknownFields
            - .status
    project: default
    source:
        chart: actions-runner-controller
        helm:
            releaseName: arc-dind
            valuesObject:
                authSecret:
                    create: true
                    github_token: ENC[AES256_GCM,data:wrUyaYP//kIu+ZNXBkmzo8NZUtSAxklqWkfYa6q8QCnSHf7wX9q8uw==,iv:3dO9Ntm4OKSLZrcSvR+DaD9UgVtSQTyOacuRzfqpv5k=,tag:ekxApSCnRLr1/WMVP8UsrQ==,type:str]
                scope:
                    singleNamespace: true
                    watchNamespace: arc-dind-runners
        repoURL: https://actions-runner-controller.github.io/actions-runner-controller
        targetRevision: 0.23.7
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - ServerSideApply=true
            - RespectIgnoreDifferences=true
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZkU2SlBMd05hWitlVnZQ
            cGIxNURpRlhkZnBjU1FpSGZaQit1cGR4YkhvCmN5bm1wZk9qb2dTdVVaeGxQSWVK
            ajdoeVdjV05aMGo3dW9wY0Y4NG9XODAKLS0tIGh5Nm5PZytkOUh0Ym9LQmhsZStR
            YTRDdGYyenlFVDJyQVRlaDRVNUhRN3cKbYt2kYBE9JT021+lZ75CEGFc89+zhZcj
            QGsurd6egPwCEgoKYLEEMwalRbk4TAqK4OeYjRjRNsG8k2I0ipSr9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T22:24:30Z"
    mac: ENC[AES256_GCM,data:3C1fziZsm8VNE2/4bz+PnSerH0qEGizo5Tn3zlha1Ee52OYy3F0EDWCO1Cr77b0NaTFhw45I75EmUpnSyFiDlem+g8ZkipYX/FtMYMKV9MO8RndTYbgRYsj6KkjnRQVOy9vPDi9FF3hF83y01dJ5Nq8NX3ATP1Or5lrtbvZ/0qk=,iv:7ceIeyEMOqC3yrrtDZYsKDKf2O/PAUkr0EFXuugbnKs=,tag:wh8ZNDTU0tUUmuonHPpSlw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind-systems-privileged-scc-rb
    namespace: arc-dind-runners
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:privileged
subjects:
    - kind: ServiceAccount
      name: default
      namespace: arc-dind-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZkU2SlBMd05hWitlVnZQ
            cGIxNURpRlhkZnBjU1FpSGZaQit1cGR4YkhvCmN5bm1wZk9qb2dTdVVaeGxQSWVK
            ajdoeVdjV05aMGo3dW9wY0Y4NG9XODAKLS0tIGh5Nm5PZytkOUh0Ym9LQmhsZStR
            YTRDdGYyenlFVDJyQVRlaDRVNUhRN3cKbYt2kYBE9JT021+lZ75CEGFc89+zhZcj
            QGsurd6egPwCEgoKYLEEMwalRbk4TAqK4OeYjRjRNsG8k2I0ipSr9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T22:24:30Z"
    mac: ENC[AES256_GCM,data:3C1fziZsm8VNE2/4bz+PnSerH0qEGizo5Tn3zlha1Ee52OYy3F0EDWCO1Cr77b0NaTFhw45I75EmUpnSyFiDlem+g8ZkipYX/FtMYMKV9MO8RndTYbgRYsj6KkjnRQVOy9vPDi9FF3hF83y01dJ5Nq8NX3ATP1Or5lrtbvZ/0qk=,iv:7ceIeyEMOqC3yrrtDZYsKDKf2O/PAUkr0EFXuugbnKs=,tag:wh8ZNDTU0tUUmuonHPpSlw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind-systems-anyuid-scc-rb
    namespace: arc-dind-runners
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:anyuid
subjects:
    - kind: ServiceAccount
      name: default
      namespace: arc-dind-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZkU2SlBMd05hWitlVnZQ
            cGIxNURpRlhkZnBjU1FpSGZaQit1cGR4YkhvCmN5bm1wZk9qb2dTdVVaeGxQSWVK
            ajdoeVdjV05aMGo3dW9wY0Y4NG9XODAKLS0tIGh5Nm5PZytkOUh0Ym9LQmhsZStR
            YTRDdGYyenlFVDJyQVRlaDRVNUhRN3cKbYt2kYBE9JT021+lZ75CEGFc89+zhZcj
            QGsurd6egPwCEgoKYLEEMwalRbk4TAqK4OeYjRjRNsG8k2I0ipSr9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T22:24:30Z"
    mac: ENC[AES256_GCM,data:3C1fziZsm8VNE2/4bz+PnSerH0qEGizo5Tn3zlha1Ee52OYy3F0EDWCO1Cr77b0NaTFhw45I75EmUpnSyFiDlem+g8ZkipYX/FtMYMKV9MO8RndTYbgRYsj6KkjnRQVOy9vPDi9FF3hF83y01dJ5Nq8NX3ATP1Or5lrtbvZ/0qk=,iv:7ceIeyEMOqC3yrrtDZYsKDKf2O/PAUkr0EFXuugbnKs=,tag:wh8ZNDTU0tUUmuonHPpSlw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
