apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind-systems
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWFpBNnI2YU9HdGNFempJ
            VkhmMTFxejVHTzNMd0NlWUZoUklKdTE1NFRrCm96MmZLQ2dDekViVHVGTDgrdXIy
            VzRDRE1OZVhZbExWUFBPQ0JvSWFuWk0KLS0tIE1YdmJLM3FJVG1yeHpDdldoQWRi
            bXVHWnRtRGFWa2I3V0ZFS1U0M1VGdHcKxz7owqYLTt8zVZq1fMPZoVHlBCcLTnmk
            4klto7G9uz7KSP/1JBgD7eEAHoD4Sd58Y7WxVCwx+19N60+S+5FB9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:41:08Z"
    mac: ENC[AES256_GCM,data:dkL5RifXmV8Si9UrUvrp7OGfau/SM2aUQT/HolwI3s+MUCTWeMNjJPoDw09bJqwvvLAO3+qFJf0RXpUba5jwOw3u/xs8LslyxiN1Y4UejZAAxWa6q+s3wiIrImWezrVzqZOkFnJab5sLI9d6lNRxM/WT9MUMYsUpw6C3pXpzuhk=,iv:4AnY+2eV9T178+HiXD+CVfR3qrE6VpQj9vn1bg6GZBY=,tag:rYkpsoIhmmtDx2LP+F4Prg==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind
    namespace: openshift-gitops
spec:
    destination:
        namespace: arc-dind-systems
        server: https://kubernetes.default.svc
    project: default
    source:
        chart: actions-runner-controller
        helm:
            releaseName: arc-dind
            valuesObject:
                authSecret:
                    create: true
                    github_token: ENC[AES256_GCM,data:Sk/av/IAjUkAoXFezCjl3c9x9h3r6pyWH6lFQ3AKpgpB8nt4JhRsXQ==,iv:lQvOvxqXsYNjbTz9SOxrjtrPDuLUy1vChq4FGzAMYrA=,tag:LWTQ4z/ZnWAWhyqysooFRA==,type:str]
                scope:
                    singleNamespace: true
                    watchNamespace: arc-dind-runners
        repoURL: https://actions-runner-controller.github.io/actions-runner-controller
        targetRevision: 0.23.7
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - ServerSideApply=true
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWFpBNnI2YU9HdGNFempJ
            VkhmMTFxejVHTzNMd0NlWUZoUklKdTE1NFRrCm96MmZLQ2dDekViVHVGTDgrdXIy
            VzRDRE1OZVhZbExWUFBPQ0JvSWFuWk0KLS0tIE1YdmJLM3FJVG1yeHpDdldoQWRi
            bXVHWnRtRGFWa2I3V0ZFS1U0M1VGdHcKxz7owqYLTt8zVZq1fMPZoVHlBCcLTnmk
            4klto7G9uz7KSP/1JBgD7eEAHoD4Sd58Y7WxVCwx+19N60+S+5FB9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:41:08Z"
    mac: ENC[AES256_GCM,data:dkL5RifXmV8Si9UrUvrp7OGfau/SM2aUQT/HolwI3s+MUCTWeMNjJPoDw09bJqwvvLAO3+qFJf0RXpUba5jwOw3u/xs8LslyxiN1Y4UejZAAxWa6q+s3wiIrImWezrVzqZOkFnJab5sLI9d6lNRxM/WT9MUMYsUpw6C3pXpzuhk=,iv:4AnY+2eV9T178+HiXD+CVfR3qrE6VpQj9vn1bg6GZBY=,tag:rYkpsoIhmmtDx2LP+F4Prg==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind-systems-privileged-scc-rb
    namespace: arc-dind-runners
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:privileged
subjects:
    - kind: ServiceAccount
      name: default
      namespace: arc-dind-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWFpBNnI2YU9HdGNFempJ
            VkhmMTFxejVHTzNMd0NlWUZoUklKdTE1NFRrCm96MmZLQ2dDekViVHVGTDgrdXIy
            VzRDRE1OZVhZbExWUFBPQ0JvSWFuWk0KLS0tIE1YdmJLM3FJVG1yeHpDdldoQWRi
            bXVHWnRtRGFWa2I3V0ZFS1U0M1VGdHcKxz7owqYLTt8zVZq1fMPZoVHlBCcLTnmk
            4klto7G9uz7KSP/1JBgD7eEAHoD4Sd58Y7WxVCwx+19N60+S+5FB9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:41:08Z"
    mac: ENC[AES256_GCM,data:dkL5RifXmV8Si9UrUvrp7OGfau/SM2aUQT/HolwI3s+MUCTWeMNjJPoDw09bJqwvvLAO3+qFJf0RXpUba5jwOw3u/xs8LslyxiN1Y4UejZAAxWa6q+s3wiIrImWezrVzqZOkFnJab5sLI9d6lNRxM/WT9MUMYsUpw6C3pXpzuhk=,iv:4AnY+2eV9T178+HiXD+CVfR3qrE6VpQj9vn1bg6GZBY=,tag:rYkpsoIhmmtDx2LP+F4Prg==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: arc-dind-systems-anyuid-scc-rb
    namespace: arc-dind-runners
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:anyuid
subjects:
    - kind: ServiceAccount
      name: default
      namespace: arc-dind-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWFpBNnI2YU9HdGNFempJ
            VkhmMTFxejVHTzNMd0NlWUZoUklKdTE1NFRrCm96MmZLQ2dDekViVHVGTDgrdXIy
            VzRDRE1OZVhZbExWUFBPQ0JvSWFuWk0KLS0tIE1YdmJLM3FJVG1yeHpDdldoQWRi
            bXVHWnRtRGFWa2I3V0ZFS1U0M1VGdHcKxz7owqYLTt8zVZq1fMPZoVHlBCcLTnmk
            4klto7G9uz7KSP/1JBgD7eEAHoD4Sd58Y7WxVCwx+19N60+S+5FB9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:41:08Z"
    mac: ENC[AES256_GCM,data:dkL5RifXmV8Si9UrUvrp7OGfau/SM2aUQT/HolwI3s+MUCTWeMNjJPoDw09bJqwvvLAO3+qFJf0RXpUba5jwOw3u/xs8LslyxiN1Y4UejZAAxWa6q+s3wiIrImWezrVzqZOkFnJab5sLI9d6lNRxM/WT9MUMYsUpw6C3pXpzuhk=,iv:4AnY+2eV9T178+HiXD+CVfR3qrE6VpQj9vn1bg6GZBY=,tag:rYkpsoIhmmtDx2LP+F4Prg==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
