apiVersion: ENC[AES256_GCM,data:yp4=,iv:xp0Mhd9ls0zvb1Zxr3pVLMjzOfFPh7za+Fg5IYapISI=,tag:VmIicXra0oIwTDWAs3iKTw==,type:str]
kind: ENC[AES256_GCM,data:2W2yVGwvaqsd,iv:UKLNO9hsaWXRWb9j8CKIskSpjd6b+W4n0dmW703juPs=,tag:oa8pQXVwbBDesd2noKyQ4A==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:3Q==,iv:rVuQy8PvgyugITe1DBf7GxWifwTlFTI7BY3I5YYvUUg=,tag:y62/LoRe805E+dPt1Ljksg==,type:str]
    name: ENC[AES256_GCM,data:yRnqaaYehSpoyhufUjnV5w==,iv:/FaoNgXTxSzHsL4a8pWwdjamjcC7Y7VM3TSfI67sV2M=,tag:OTW90QGshacHySzoFH+2lA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQlJUZlNqL3NsekJhdll2
            WEgwc0hrQVRuN3RsU0VuOE9oR0N2akoxd1ZVCklSZVljQ1dyYlZzV2lEeFFhcmdM
            aHpYYnlmRVBKV3dxcHJPR2hESUdORmsKLS0tIEhvV3VhNHNkdHJQR0ZzaEZ4T3dj
            TGhYNHF0bFZSQ3BpZ0k3K3FROW1iSFUKfB60U64wnqa+KABtaYz7vYd/FnL3FLYK
            JxpydQfT76DkSe4b2DU0GCmrs0H6Fo3k8Vr+3HJMPB4Bkng1hgvfPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T22:59:29Z"
    mac: ENC[AES256_GCM,data:K4f1QamxnFALSHghGmTK2Apiq+GxEjOzLTUTXOyHvVcDO8C3Qf2qt68thniyOno1hm2fB7b3UbZqI1sQX4sCM2SFHE9xwzdvHiAT42XWxlauHNPxpBgZBf9Vj0KBeG2dptpKdSPZyNgM/i7WTncayhvTV7Uc+ZKidpYmYmQhaYM=,iv:y7oVb/uV44k7Ph80nnFOYwo7O6CATa2CzTqgYaNfseQ=,tag:1hNIaCFeOZy+90WRNL32YA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:RMoOgO1KaZ/vOck2J5+JYDxgofw=,iv:7RoniLup/Ix7ii36/l7dSOPR6F3UeNxMs/YUX5aMEZQ=,tag:UXgviv6TnD3v1vZ7jJK0Jg==,type:str]
kind: ENC[AES256_GCM,data:pZ8SNAgBKIVE6iY=,iv:zlk30M9Mxz7yby9zRM74D82Ag2vRb7SsbD8wPsi9jyA=,tag:RQ8SPypUCi/wuQcwYBYxhw==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:sg==,iv:N+M9gYR/GmCJ11Opy8X59KbdRJv6gqCgy6i4Y2q2CD4=,tag:4EbZEFY3Qt8ulmnyPlUApQ==,type:str]
    name: ENC[AES256_GCM,data:TTvhp4Zh/rg=,iv:7cELwW8SloqKLsT42aFFUpsJNUDXb5oSvx5vG9zLIRc=,tag:7bVLcjaJgvEKhtv0ls+w6w==,type:str]
    namespace: ENC[AES256_GCM,data:xbRr62T0wxdfGd/Ig8e/kA==,iv:/ILUpuqKGpCWOz/volR61DMLK8BSZrQ4ipqyPMwZOL8=,tag:aDoTSjq7Hjp71vcaqr5oWA==,type:str]
spec:
    destination:
        namespace: ENC[AES256_GCM,data:EWjdhQiPOfWTRKXHnXe7TQ==,iv:EOsFpwJ2WQ7wqhJoNCISACehKClJUfoPT0fiyXGW0hg=,tag:4Aaaxy47XzxVM39P818u4g==,type:str]
        server: ENC[AES256_GCM,data:IxqpWN5PkR2CEw4fR6C4IHdWdWLAsdRG39WQb9NN,iv:XgtCqIj6ZtvvLA5YzANL4nCiWk3OUBViafT0c/ync0U=,tag:L1cK7Rp3Se1iNz2DnPEdeQ==,type:str]
    #ENC[AES256_GCM,data:rqrPOApAILrNgDEY8NezgGilt4Ix7u/qToJtzCJ4A87w4Gp5KjxcYJ91UsI/ah7qstV9hSmkR2/ceuSc9Q==,iv:PDdOysEk6zNIUHXr+f/HDyNb+2hFH0qruNsF44Mpqyo=,tag:jb5K0rYBdpItx5X0HIYELQ==,type:comment]
    ignoreDifferences:
        - group: ENC[AES256_GCM,data:LZ05EVHuLPeCKNScPcCD9raYt7k=,iv:+lh9qANneCw7gWLm3kt9zQNmfQJuiJZ9mg0JRgPwmG8=,tag:1ZShyZCBvR3csBGOXbN0IA==,type:str]
          kind: ENC[AES256_GCM,data:xvHZ0h2zqe8qH0mXGztiOywHZ9YpcTNv,iv:s9lX2hA20lWfubn9QzvVCFw0GoNLTi/uPKH9jQvvoo8=,tag:Ax8nV4RhyCDBhlzug2auCw==,type:str]
          jqPathExpressions:
            - ENC[AES256_GCM,data:8stpt9jFrhI0qlkx0scx7Qz2d72l,iv:RMvSjS7L+SJ9YrCFjoFYHyh5LfOuTOOMdu9/4SzjErc=,tag:RnpBth0v/G04kT769CyJxQ==,type:str]
            - ENC[AES256_GCM,data:HnbYI8/lwZ0VJLWjFVoF6A==,iv:Am9nUJce/RXgFqralX09cu2DMMrdoWzgrWcu48VzL40=,tag:rZLv8uJ4tiApYlgIsW4HxA==,type:str]
            - ENC[AES256_GCM,data:pypIOTIxZ/DoILnLIDfRgNuKlUK1EsmPaUye,iv:DSyfSCnqwY4Kmhc5YxoKRCy4RModhXbZ7EegXUkR7SE=,tag:IiS3JGCpSoK3rJpXQpxEmg==,type:str]
            - ENC[AES256_GCM,data:GjIXQC67EQ==,iv:v9STJYz0VjBh8TDZ5vrjOR4Pqo0DA/YZUdegLrJgEpc=,tag:UZ2PedJI/wyrbVD4vkeL3w==,type:str]
    project: ENC[AES256_GCM,data:A6GkpogrNw==,iv:OzHmljktG0urykCss82tjYbxvxADfT1sBzY2mwzzwUk=,tag:WtddKteQdB4IG30nHl2VTA==,type:str]
    source:
        chart: ENC[AES256_GCM,data:PrOocz17nw4U2fmxUAB1bFg7ZN7F4/O1Mg==,iv:p82CrbCtc6BLThwbOh9oeOjQlustHAyhwlD5i8zFiSM=,tag:WP5XGOP/SSQa/wqgIXvmcg==,type:str]
        helm:
            releaseName: ENC[AES256_GCM,data:OrAKJA0UrU4=,iv:QW7yqnnnlt7SL/Yfnu6dhY9ooCG6lZ+1KmgscEFCjeM=,tag:mrIGoAtwdETGAZKnTfKEag==,type:str]
            valuesObject:
                authSecret:
                    create: ENC[AES256_GCM,data:3i6UOQ==,iv:WrfZhh8ZjMccVvu2rHje+Nws/5au8gW/MFvuG2Lv6Qw=,tag:7ACaMhfGYYeieW6dJLVb7Q==,type:bool]
                    github_token: ENC[AES256_GCM,data:fh5HAKaovNNiycpyFx9arT/pzarAANPwREqu7qHBGnk1Y+qMWjETnQ==,iv:C8shH8tT0N/8thsCAPk8QfyNiHzAkMzGcZLv6ihlG+Y=,tag:yaSlvuWYZUns9nSwEnCodQ==,type:str]
                image:
                    repository: ENC[AES256_GCM,data:wXQ6Lirgg3nqHEELWpPAlER15qVxD+O/b9B0JctNGj7Oz6DzPboOdLHAUqHtjA==,iv:3bDein31YFLi6n6CBDh3IePJN1LOm6gBzP1PjT9fyuo=,tag:II9rDlb4R5qUuQUbVuaIbw==,type:str]
                    actionsRunnerRepositoryAndTag: ENC[AES256_GCM,data:ZlRjnX/ie7Klky3/YWXL9SQ+wuWnjq1cG0mEGBw47jSKWemL1F2TqoTP,iv:VNOl8cl2M/+jWygUHlHQ7m8PCKNfg9c8BKObKA2SzoQ=,tag:lybyYbuDWBdiL2szsqb1/Q==,type:str]
                    dindSidecarRepositoryAndTag: ENC[AES256_GCM,data:6rTJDhDq7EaFHH3cQx5hG3bT45ZQ/sT2BLa+o3M=,iv:oUfwZ7kZiPexOXkjzQzvyccrqw6QYgVsogj+6juEchw=,tag:CK9MARxVSIzorGtfKg3zUw==,type:str]
                scope:
                    singleNamespace: ENC[AES256_GCM,data:vucymQ==,iv:lKFvC0VbSAAdUMbeVLvvy/+MHluDJQqInuD0uh3tJaM=,tag:0nflD1xKGAg7Uhf84RkXhw==,type:bool]
                    watchNamespace: ENC[AES256_GCM,data:6McrfZ270rkc7yBccDsIkg==,iv:5IylfmICTw15D6fHurtW0aRoYZQTnnFw0dr6NxJu2k4=,tag:KcjTsv8aEBP/0LrY85AmoQ==,type:str]
        repoURL: ENC[AES256_GCM,data:G9+/PK7Fi9nyj8+GzkVnpj5qLu8fb7n47HfsP8jzq7UGl2Z5HNBkmegPYO5eDykNCzcHcyutLpqzMcxiPVGgtbEm5xwk,iv:D2oyFeZM/nG6XNTEQxSUqtvVuMryCWpyu7X1atF12dQ=,tag:d4RfFMjKbrZRb5xGlC0+Og==,type:str]
        targetRevision: ENC[AES256_GCM,data:jh3IulHo,iv:jbO5/+BrmbBMWI8L6HsbFboeVJ0j0oQZGjHooRbUrGo=,tag:jAheU8US59XPDVfkgpPmtg==,type:str]
    syncPolicy:
        automated:
            prune: ENC[AES256_GCM,data:8cCztg==,iv:hZHUkXllq3KZbdXpACaIa1kkMN357wRov2I9vPiThlU=,tag:GXsanxPvuyINuuEuOAE+AQ==,type:bool]
            selfHeal: ENC[AES256_GCM,data:M7SN8Q==,iv:AJJBiznTJUc5wk5gzNmiHv8lmyh4MBJYG/4efMHqUUI=,tag:tRJzuMWH6zFElnfHfVzIjg==,type:bool]
        syncOptions:
            - ENC[AES256_GCM,data:rRcW+LdRoSymDm1oDsWKKMOTW4U=,iv:7f3ZQhPYk+bsOrnFvOmMuALYBXvojS1ka0C9WDO1qjs=,tag:55cSs+XkcufaDAFW9w76Mg==,type:str]
            - ENC[AES256_GCM,data:SqU2JSkcP2g5ogHe1utQ2Br/6w8hFAGZT+KIn4s=,iv:t0zoMztE2MHQsPEdkkQt75hBAsOaqBUzANB9qC/b8g0=,tag:BEH3hCF5zVb9mlojqX7gZQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQlJUZlNqL3NsekJhdll2
            WEgwc0hrQVRuN3RsU0VuOE9oR0N2akoxd1ZVCklSZVljQ1dyYlZzV2lEeFFhcmdM
            aHpYYnlmRVBKV3dxcHJPR2hESUdORmsKLS0tIEhvV3VhNHNkdHJQR0ZzaEZ4T3dj
            TGhYNHF0bFZSQ3BpZ0k3K3FROW1iSFUKfB60U64wnqa+KABtaYz7vYd/FnL3FLYK
            JxpydQfT76DkSe4b2DU0GCmrs0H6Fo3k8Vr+3HJMPB4Bkng1hgvfPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T22:59:29Z"
    mac: ENC[AES256_GCM,data:K4f1QamxnFALSHghGmTK2Apiq+GxEjOzLTUTXOyHvVcDO8C3Qf2qt68thniyOno1hm2fB7b3UbZqI1sQX4sCM2SFHE9xwzdvHiAT42XWxlauHNPxpBgZBf9Vj0KBeG2dptpKdSPZyNgM/i7WTncayhvTV7Uc+ZKidpYmYmQhaYM=,iv:y7oVb/uV44k7Ph80nnFOYwo7O6CATa2CzTqgYaNfseQ=,tag:1hNIaCFeOZy+90WRNL32YA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
