# GitHub PAT for ARC dind-systems controller
apiVersion: v1
kind: Secret
metadata:
    name: arc-dind-github-token
    namespace: arc-dind-systems
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:/CAHOBTQzlAzXitQ774Lz5PN15rmAQfElIuQhGQahMk2jpu5RJloOw==,iv:qm+EWVL8A+Nliubcg0oGtcv6CtmPnY2zmCcg1gBghhc=,tag:+ou0tzbnrdx+T2p3e9dy8A==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QkJxV28xTFNlTjJoWlJZ
            SnRlcHBxMmpiR1lpRHhzNUhlekM5aWtDVWswCkg3aWdiRXlYUHpPcGJjN2Z1bTc3
            c0JTODE3NXlabVdxU1c0Y1BwS3JwcXMKLS0tIGI0Q282djJWWHA4eUI2YS9yV3dD
            VTVxVnFyNTN3Z1k5RFFISUxrcVpjd0kKDE9oMCekM73/8xra527MH1LZFN+5Rvtf
            cGYiEGae+AYSHMto24CEbstV5KtB0CsbQPecel2ocG8fPEP2dkRfBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:jL1sKPEgnxDUKBUYpEnFQZdoLzqtrBS88jNLaIWoUdd/SeyHpjUIKOn6BO9k8AGSB7VAgJZqb0TdprYEVxx3kfQRdD757xWGCgHP8476jI8Zh35UqmUbsujcfrXORKHrhVZrdLUS9lvPj8+1uOlHlktQUCrXLKPT1ppFIcHi6nk=,iv:oRGcGiZo7f06QplODRbhH0GaEgIeCA2a+FEh8JAp7SA=,tag:hdhGO71JA/OSatPv6bckpA==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
