apiVersion: ENC[AES256_GCM,data:l80=,iv:92JMdN2sfc4u/oCQDq/od4AVgIxdLCx5HDZNYaxQ61w=,tag:32zwczMKTxCPofdhz86ygg==,type:str]
kind: ENC[AES256_GCM,data:Zdb6wxUJ,iv:5s8o9yOPDT1qrQxyqFMeQZBmQzLqTdYp1n0eZrk2Fk8=,tag:LoazWMzmjwaAq7Ym1WYq1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oWJk2FybStjwl+LV7iNr+yWjTBQgmkpJqPg=,iv:bUvnQ30nIgwDk3UNobZkO53AYAPKJ5djynX5c7kJTt4=,tag:K9Y1SrauVWgX+2sc+07xpw==,type:str]
    namespace: ENC[AES256_GCM,data:tB38M3QaaS1Z36ToSORR0vnsr40dOf+Zm94=,iv:q5j5o958DImY00oOt4REPZd7rFLCUvIkvkNGbM+Qarc=,tag:Y0QPsWgAxWjpErkqpcgYNA==,type:str]
type: ENC[AES256_GCM,data:ohmSIUwX,iv:k+ePpRquohQJ0h8TEDIyGCTNbeOOkgHLgcMj98pXlQk=,tag:NF8ehKDEbKXSIKpOMQKJpQ==,type:str]
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:2t37VbL4d5Q+TyXXBZ4JPsDE6RgRezIsknsKXHUgoIoLKRgYBkCt+A==,iv:AbapfpAGlV3dQd4seXynKz8R8ZMgoCO9yi8I2tnBKO0=,tag:VLbihG1Sl32/RJ9QyDPtMA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbWtDNXR6N21BZHZZV0cy
            ZFFkY1R4dDRIODBjK0JCUlVra0t1b011V0RVCjZFczJhdmVpbVRlU1hrZHpPUlli
            TGRLY3pzTWJibzJBY2ppUEtFTlhOLzgKLS0tIHZVTmd4ckZZdE5SSjNJNzk0aCtm
            NTVoRGM5N29hamQ4YkVxZVBhMytyR00KzGRVzBjm2vCBuR8L8gwmk7O0qxrVIGuM
            QXVDrmIhuwPYcWsY4SedaPciExystPrBwNDWx08DUj0Vwkt7IrOMrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T18:04:05Z"
    mac: ENC[AES256_GCM,data:pxUua3wqvooaQXFAlykeCS0dabvgw4E91k/ZiFAjDfRlUOYxoqIMMvrFddgoNihtLV9/VNCrvMQcvUwdoVy5nPYhFW0XS71mdZG2WzaT0IqlVV/4welsERUmo4CmImzVRXKXUAiwHbXMbx1ESxO8wIaCOVc/PEoz5edWw1PjlYE=,iv:khyaVn54h2/zHA2UFb5P0bIJbER8xuQJhRD+ccJN6tA=,tag:zfggA7WA1JT+PIgw37G74w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
