apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-credentials
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:zSq5DmP+DWrXHiza0Ki4/S1je6YZGA1oG6nSrlHmp56l6aSdsLEB/Q==,iv:7y5BzcFGxDSaaw0NJB5MxXAGWi3/sQZJcWtgc72JSnA=,tag:M7yHQ5YbsaL3STxKWKxNaQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RFozVmRlWXQ5NG5MUVkx
            NjEvTWpzSFluRit5RXkxN3JvQTByK2xYdkZvCnlYVlgxUFhMVGVFZjBJOFFZQVJL
            R0N3TFJ3L3EwRTVjSUVHbjYwbkVIbWsKLS0tIE9nd2Q4c3Nsd1B6T3ZkaFp0Qzdx
            N1hnem5VTkw5TTZZUk9mNy81MTAybzQKW5r9MJJ6qxyS7mWNoD6PSL19Ncm6SZ9u
            m8KdBqQ2Krfsg/QiCn91tEZZvtdckGSOfxeYNZsBrDXRgNFyo4KWBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:FQ3vjAMbIkMOlvIHr6flHE8ff3nbUXEQpdq1XPh7x6HYoY/F5OJ7c3Lns1UZRiecdut2AA9Bduld+fFxfw1W5d7uCjOQSdXF99XC/sV+iAtpzWiRsPQTnTUWYFSrUV8z/aul7TSxNGfQaZFawcygBXVjkTdnQHYq/jLeouGVJpU=,iv:8fWPPjFIed0UYOFPm7/ZYUpg0gj4QF03jHcOQdfteqM=,tag:z/Np14ikz/3phxBM+7COyA==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
