apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-credentials
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:zSq5DmP+DWrXHiza0Ki4/S1je6YZGA1oG6nSrlHmp56l6aSdsLEB/Q==,iv:7y5BzcFGxDSaaw0NJB5MxXAGWi3/sQZJcWtgc72JSnA=,tag:M7yHQ5YbsaL3STxKWKxNaQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:QXiz2QcEAeI4qibPZrRbzXKJ2PJzlhfpHFClzQK5EIUO3wgQvvUS9hTAphOdSrOoDOoUNiAQfB542b5sYMwgiLEqywHSFiW4i3qOdxSTH8cBheedm9/L2FhqqKeQKNgYtThKvFwcluFwUsWAvaO2Y2sqQ8LhIdu+rrS39yATJmvRaIRVNVajCAvhb0DDCnIk3Ok8EOrreNqEBp3HZ3I23/U=,iv:6dsGyW+/f25FDLrNKW6NOULuheIq9WM58E5mV1fpRpc=,tag:X1tI9hfpfUxxSYgbvt5/cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RFozVmRlWXQ5NG5MUVkx
            NjEvTWpzSFluRit5RXkxN3JvQTByK2xYdkZvCnlYVlgxUFhMVGVFZjBJOFFZQVJL
            R0N3TFJ3L3EwRTVjSUVHbjYwbkVIbWsKLS0tIE9nd2Q4c3Nsd1B6T3ZkaFp0Qzdx
            N1hnem5VTkw5TTZZUk9mNy81MTAybzQKW5r9MJJ6qxyS7mWNoD6PSL19Ncm6SZ9u
            m8KdBqQ2Krfsg/QiCn91tEZZvtdckGSOfxeYNZsBrDXRgNFyo4KWBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    lastmodified: "2026-08-28T20:48:00Z"
    mac: ENC[AES256_GCM,data:bf1fba9aDgnnh8VXqg3+FIHg7rncRp6HTsQ5eWGvd0JRgb4zbqWceH6LlueQuD6EhXnxui4J1qmTctcVmo0AzP8WgfYQBHK+uxHHIpcWPfv6wiDSfKsKR2A8ECW5NhW0cIExbNoMRtQ+dp1VWXoT0fa7TQTE3ZxO8VOljwOMXD0=,iv:+jYV5UQJGwmmimDzSNywGQMf+P+kHUmLsA7T8Z7kt3o=,tag:cUWrmUNaSPF3sECINQO7Sg==,type:str]
    version: 3.12.1
