apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-cloudflare-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cloudflare-api-credentials-secret.yaml
