---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  source:
    chart: headlamp
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.41.0
    helm:
      releaseName: headlamp
      values: |
        config:
          oidc:
            # OIDC config is provided by the operators/headlamp/oidc-secret.yaml
            # Secret which exists before this Application is reconciled.
            secret:
              create: false
              name: oidc
        serviceAccount:
          create: true
        clusterRoleBinding:
          create: true
          clusterRoleName: cluster-admin
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
