apiVersion: v1
kind: Secret
metadata:
    name: oidc
    namespace: headlamp
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:b/RWN/cSdwc=,iv:/0BkklPXCiwDtcy6IIgc3ZZma+WMeDVjF2mM119L3Ls=,tag:eGvQE7d4/ogsKplLGLoaaA==,type:str]
    clientSecret: ENC[AES256_GCM,data:pkr/0YYdyHalp+jzlFa3BDAXCLYDps0/J/N3ICk+O45sQnq0Cmmgphc+vVxcCHxCJUOAD48G6mfgwvSdtRiN2w==,iv:3KRDS+SMYSfWLlL/Q/CwsmDixVmliTCpY3AxiX3WtCQ=,tag:SEbj3VeiacpR975lBA1m8g==,type:str]
    issuerURL: https://argocd.makeitwork.cloud/api/dex
    scopes: openid profile email groups
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdXk4YlRqZW5xdTlNMzN1
            M295aFlRTFhyTlByZjJTQUtPSDZuNnBhRUVJClF4ZWhjQUViVjZYOTJzQU5IMDVM
            d3B5OWZ6M280Zm1PQXFuT1A4VGMvcGsKLS0tIEk2Sk9paFVUaTVYZ2xMTldwdWFG
            U3RyQWdsL2JSU3NaOXFkdWx5NU9TTGsK5c3H5WUjUNuQkv4OEe2UygRSpF2RjnRW
            lANaaut2T6anLCWj1Fl6buGoLosEHFROYF77qCLUMMEOu/rUTyIrTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T03:23:57Z"
    mac: ENC[AES256_GCM,data:jOC7YmhEfmO8Jp/0ZMxhovHRu9+wRalBDOS5g8RCQmiz3nS9HoXbByZZsF7TkKd4lIj1mKqf3B7xJ13jDdV3T7+fcUaZ1F6v3Xz3/5YkTqjZHNcSkz0HxjZ4RekZ9O+xWLuyFXXaSVbT+nPuLPiva8+2VWGhEsqJOPyLbdsG6sc=,iv:eYO1cedcAajmZVLE5hqg7vN4oE8TYKoUrvwVQvHbXeY=,tag:Xcj2BlG0YU5lnBUEca6vOQ==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret)$
    version: 3.12.2
