apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: headlamp
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:KpDxUsoRQdE=,iv:V3ZbGfbfu+LtMhUcjEslwouiNUlsIv0FBz4FVXemriE=,tag:PIui9KnoC+o7G7Cl6oOwAw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:TXBMWVAEU7OLNJx6mrZcK3rbLlTB9GL5hTAAXTwwzSa9xTXLU8l/MJ51g2YcbmSWu8bNGa5mi1bExzkvSGhwXQ==,iv:xKDnl7qCPM2ttNWW2OU2a1f4FNzHDz+loLLKuBdN5+g=,tag:CT1vk4kf0sEKdXy9CUVgbg==,type:str]
    OIDC_ISSUER_URL: https://argocd.makeitwork.cloud/api/dex
    OIDC_SCOPES: openid profile email groups
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU0wzYlpJZnNlMnVxdTc2
            RDNuYTRvZ2J2bGZVL2NTdEsxTmdLMEhLM1cwCmcvUmNmZloxb0ZDZVVkbFRTcTI5
            Y0Q3eU9kMk5CL1lScVQ5MUl0a3NQR0EKLS0tIGFsajNjcjNtbGNzWk9DQldGeWk3
            Y2FhOENiWW1aNy9WbER3eXIvNXhXRnMKzdWk5njxD8yiSjhv5a1jZ9giCZWTnNpK
            jvqHY7FMWuQMowlEwkbpgUeEbcf4kabl5clCr4w7mh0doYWt3u/7SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T03:57:26Z"
    mac: ENC[AES256_GCM,data:/3YRM68bw/3U5LqF6N44kHoONeGPTvickVVaoKOf+LiPCo91juSE/23q79ppDwjLROUaVf67peZoP+m/F/qM+0hGBTnunzgn3DencYeb640YEcuoJnAkrwMqQvcFjXKMBVFjeV5hN97/hY9FOPtgyEhHTQPSOkQvm/XDhhJXGeo=,iv:ghbaV+s9zgWRm+CsJVdLjNNijTyVaFXtaDT3aHRJBb0=,tag:oUSJ5Dwkd7V+HGyDxvdoOg==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    version: 3.12.2
