apiVersion: v1
kind: Secret
metadata:
    name: oidc
    namespace: headlamp
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:w+qM4c5E3OU=,iv:btkRfecW3ZMDsTTH3EjWa2fpfsQpVNc8ZYar9JYMUAs=,tag:/KjwfDGXD+6/ayItQ/9r7A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UthDZifTlKxWnU0quMZ1b2HzNDlXxZ30osNe6AqXMVLoM8eCfNsyaKwEbr8QGXPLQIEOn/bPTysNJz+jXLofpg==,iv:p35y3ZbM4ngYEYwoMlFG6i6vuENVrREcUK6MmbpfZD4=,tag:5b2LBxNBTikBa04ESyqcmw==,type:str]
    OIDC_ISSUER_URL: https://argocd.makeitwork.cloud/api/dex
    OIDC_SCOPES: openid profile email groups
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRW40aTZXUzVRMWhNYkNM
            WGp6YU1LbHFBOWNjOVp3NXlIeWx0dGtkRzJJCjZ6cXhjMS8wTUJ0ZmRDbWdkci9L
            cU94RVVuUER1UW5LZFBiWmtHbkM1bVEKLS0tIDl2V0VPZldENXRqY2YzNHhCMURh
            MWZNek5VSE5tc1ZaMWdNWXpWUHVIRU0KHu4tZxxeEcCkCZm15+UepKSSWzVsWRXs
            UF2O16ZNXkB8QBDqzw4ND8oUw1pR05dbNFyQ6B/8vLe2KJkIJw1jEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T03:39:56Z"
    mac: ENC[AES256_GCM,data:a6NVrsEE9YTbD1rGlrp/Bu7EjGpw2X9TM2iE6iuGtD7zNoxTewjevjtny5ra4tpIXhRCHHLdaza7nw/xxHA93qpBXukc3M3p7eqFkf+ML1+kx2JPFbTfXIgCguDDF9hRcDQMDnWWCGM40p7h5GHqZj4CvY14dI+R7RZr4Czo/QY=,iv:+pULSyr4V08e25SIaTGyl7xRsFzRVlEUnmbdxKgOvVM=,tag:KYUFRZ0swVnQqWLsbgftMA==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    version: 3.12.2
