#ENC[AES256_GCM,data:KlBjV+QAysfCA5IhkPgMD1+JxYA1f9TirA1yfvg4W768ImjTOjnhBJ1ihCLY9fkBVtk=,iv:AkdEYDOxgb5EzrKh7naUZjGatIA93YzdOnDtsesdGFg=,tag:MjjIdmqeANLcM5AaAbMLUQ==,type:comment]
#ENC[AES256_GCM,data:dp2HVFpJItj0CSIGgVVq2cYZ0C75pNXJ/AbGzFPJSQZzjCkzq0ZZXM61UUKKn9ftNQ==,iv:9lz7C13MzdjeAWFC6YfabBVBsC7M/dKPLlSrC7AYmSc=,tag:ZAbtY9CuI676pWc93YiI9Q==,type:comment]
#ENC[AES256_GCM,data:eg+ZOpVnOS98aximBNYGecoCcSETGt3xC3yoi7rTALfV2DLzpquP6lp9NhG4y4Sr,iv:yux4QAO8wzxzgdldE0GIGLVUAKKTEA54lUx36tIfeU8=,tag:dDR1VNPYk3ftUahgX+VHug==,type:comment]
apiVersion: ENC[AES256_GCM,data:NJQ=,iv:PlDZa7RNLA5qSZOzoH48jwh8v069v21/3smNygltyJY=,tag:23tfSA2woS41uySVKn0qsA==,type:str]
kind: ENC[AES256_GCM,data:kTpyJCoA,iv:e0yep/CJBmCBoUyrvrRauGrejZHSKhT0fR0HVCCnZW4=,tag:WvR+N0D2CpqdhTXqW5Ep1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fOz2ELuCGLGqKNKE+w==,iv:MbOmbehtcQ882Tldr/2cEfpLh2Bsw0A5SMfiBR54YWI=,tag:nTTfMMumH0VlNofP9bMBxA==,type:str]
    namespace: ENC[AES256_GCM,data:AsTFPuzttUT2fQp4IZZNRA==,iv:gTonwFIKfYsR8fh4ENlUk6M+tki8HY5bgtekFg03XtQ=,tag:JpInvioXdgKWwmWv/FyIQw==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:lAK3fQUd,iv:iHLJCJIbmiUj4Tn5H2SnppKCa2J8/yOQrf6To1scc6c=,tag:a4QY/6igO/ZEjkJs8nreHw==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:zw==,iv:jJMHRcMFg8Qjqs+Ny1SkLxDLpnHN6g+tliW2vtQp9aQ=,tag:LBp6vtOvKIgaF9OQruOV8w==,type:str]
stringData:
    #ENC[AES256_GCM,data:t8QUrNRqqam32H0BJ+bs+R7W+Bz/on8TZNMfFEd0PL2xljUUi8NKojBPEQ/BRxHKp5qOIi9ab/T/1PktQZmIYr8ER1Wg/u7nublr4N4G3znncblOSX+M0F8D/o3RuMih,iv:WhlH41qOMYjp/tzONPZoyD5O8m/p8QyfTAt/r/hbhMo=,tag:2IcsaQObHbdfPx3CC+HCTw==,type:comment]
    #ENC[AES256_GCM,data:cP7c6hAPoj6OW7HLpdi23vCJmV/oFNeGy8nAXE/w/NLnpeG3XjgQCk/0wmMn2UvLvdW7VrL6zxuKfJWHLNMXfafTfM7gjjsjKDyZv5kMHpsI2uYUH3+kuOuRDJfTNYmscmDoYe2C,iv:TecnYwJQgEAbbnUJcneEFJ571UJXElOHV9mjKZORqaw=,tag:app4Cgr7znrBcTVrrpiGIA==,type:comment]
    dex.github.clientID: ENC[AES256_GCM,data:lszuIZi+fACSkA22r/rWtKJlgQA=,iv:5j4ZIoJuX0IQE/Yk0JAIIbO8GUgxRz1tYbzLgIoz6hw=,tag:AvmVznBITElCflyYbZYwqQ==,type:str]
    dex.github.clientSecret: ENC[AES256_GCM,data:f/CIHwUoTLDDsN/zp2xeVWJw/vNdVE3sw2A1JrafSxzzdAqZTUq0Sw==,iv:Xi3NkSY8YtVRcURcKpfLFB+zqs4GyRTgB4Vj3IjxTJ0=,tag:vi1/QWUEyaarlRexp079Mw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaDhCZVlQNHlTS2I1ZFBX
            dUhoZG10Ykt6ajBtWnlKeDVkbVFTT2QyYnlnCjZ0RG5UUWRDTy83MXJMYVlKQUxo
            TTRBdmxORHpTTFZFZGZhcit0TXBycUUKLS0tIEVWblljSEpvSDZvZGcwYzZQWU1N
            MXdVQmljVVAzdkl2NmtwSlJ0VHl5RHcK8mwt+11CX4qJE0banJVcuQ8RBtuXcuaA
            nmk5NepXlMnk/reM/BgpylvX5xkVZvrkBk1cwSeFRRSeLCUMIKDhyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T19:24:14Z"
    mac: ENC[AES256_GCM,data:YkuIa0Skn+2eSQNpaebqQAdGNtXC7tBiTbjhW7Lz6x+ubazUroGFE7q4rYbYd2tPAguNg/mGe2x0hIxMeriLGdaMAZiNDzGcEcCJxdHTLepWcZiaj6bP/RUfCyodrUICKdGjvXgYRV1/yC+b8hmiFX0DH8sU3O5saWJjy20GaWc=,iv:KHS62ImuEURc3KrCqHUwOQJt0StvTKXQ0YvhxHHEG5c=,tag:K7zu2ly5X1jurThZGmncEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
