apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: warp
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:M/pTr8V0r2cPKMWGmhYyC+iKzxGVNi9RPqGv4LIHgtkv7YE9NrpAf6pnXk0UvMS7NJ/n9FmstmKg4o0PssXKVui8UMP6YQ5ICJ5+zh5HzKVgB03IToLL9X1VNC7R2/N8g0ZlaCY15WEEG2Z4d8NrEBNUg996wto4qxFqfe9A7eGrastB4SCsJf78wBzAT8Ijf034lZfvkgP/MCoL15sOF65a,iv:ZTiQNFNbap5QpKJpOtnodZNI65Hcqe3hRGfaPlr0tgU=,tag:Sn+NXjC8bQbvM0+gg2XFUQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRkRNMFdNbStUYnJlN1hv
            Yk9BM3Rmem9hdThmKzA1T2ZzeTRuaC9ZbUR3CklhMmFQWDFTTkswUWVEL1BmVGVL
            NFVlZHJOcHVBUVdtano2Z0Irc1FkcFUKLS0tIE5oRWtEOCtEdldTT0hpVVFFS2Zp
            Z25iaE9iVXlsdkJPNHBBQ2EzaUhLMmcKggOgAciYQNd0mdyr+/uLbkNMGtpW1pvz
            oehgATvwvvfv0IAtDBPCeaTGo0nTDrD6PIOagOxquU4fZxuqPWpA8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:JV56nUEmFFIdUin3Wv194mDwGB1y9OUoDSIXhHoVZ+irmV/hjw4Rs8ZgfGU7V4HFgTzbly6JfUfdwxrcpYcLF+DRcOOWwJfq2Wh4sv5tvCnjYO1nEIc2pGoec7V8Pfxi8YI0T9eY/2HUAUxxoMorKDBjfnf+mixAQlrYwuC+1Bw=,iv:NG6KHogFTZiZkhTgrpOWXVDMESOH+CZscFlqZudFgUg=,tag:Sj53Hh2bymMnB/YV8oIb2Q==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
