apiVersion: ENC[AES256_GCM,data:M7U=,iv:qNrbDE8qbpTn6DklcQJmIh448hVcg9w6ebkcTKSpC+E=,tag:tR7oufpNBHwYdloBDmIqMA==,type:str]
kind: ENC[AES256_GCM,data:oVq2V2Hc,iv:Ar9wiiYgYqsUXe39ucKIsKWT2Q+niyMqcMu6wBYEmCQ=,tag:APvSXkvRrJBzpI3iPfyIQA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:smZ0qJcJHSidVG5wWauRinL0G0XnnBk=,iv:t2ZQclneE2Fez0Sdwm5MVAwP4+22e3KKJXRJt0rs0l4=,tag:rg8zLVQVDc1YD+VF8iemBg==,type:str]
    namespace: ENC[AES256_GCM,data:6wnIXQ==,iv:uubtt3RcxMPb24sG7bX6ajXeTsXj73ywcVaDPerVNkM=,tag:sKKfXn4Zs0sPQ9+o9nxLlw==,type:str]
type: ENC[AES256_GCM,data:8Kk0BGOA,iv:w758aLzCb5tOsIDiaL7L25pgdNk1xbIGSDaf4jSYyzw=,tag:VmOu8PglscyAcOokKte7jQ==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:Uq8VTq5OryN7MZdNks1bVu+0Qg+pfirg7TlKwT0SfWH3XmxQ6as5XQCN/QtPDYbVbnqw8OMr5OBQIKc8iwOWqI3XgnAyIk+JO3tlTOxZmJPpjiAtaYvFPFB+cUalGuCIU2/6SmKwMdgdWEEGYdQVljl1K1EzU4HL5v/37H1BqRa3liNpH9g/8NvstATPX5k/ry2Yyo9sY1BcJdvOdiDJQTev,iv:0mrIon1pJSX0incgm5J32rvnOCcnlqgKke0TTUxzfyM=,tag:9+/KR+3xZAqdpyGsWr4Apg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWXpaRWlSQzdMODVqUTY3
            RDFYL2lKUVFDSm90eHA1NlAxRlc3NGVkT0g0CnRZVjhzSUtiMlRvRzlUNk94a2ZI
            T1M4SHpGM1FGZ01ZSTZIWnVVemdFbE0KLS0tIDV1U3BIa2RZSmVmeXkyaHVHam50
            cnJXMWIxZUZLeXE1eVBQa1BtY0VkOGcKRsN7NYDPrfH8UQha16YxdP/1CvNAjjGl
            hXRPImXaSGpGKqypWCvSsFqDvIVKlQRHLWhHCZCXsX4YotWo21e/iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:40:30Z"
    mac: ENC[AES256_GCM,data:vj8hEdP110axS1PZ0LZBQe3Db7S5NYx1PHbgZMja9erJ12AthE6S88kXxRwAWyg3tSXMtPdvbDiHkVVMTj4fTMNbNZIVZyUbsUoLQmBF3uoMafN9dpsZ/0h6DGTbTg8R1UCgj2HBk5CnMEWchjnaP9WdoJHv5ELNIyT36wEri5k=,iv:vnLBPUSwVsilE4Q8w4v6rfW6RQLvcILy4JgePp60n1M=,tag:KNO/7zX3gfkMDt4OfW13Bg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
