apiVersion: v1
kind: Secret
metadata:
    name: discode-bot-auth
    namespace: opencode
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:cft9exKqU0dFSiG7zqpoLIyFBZUyGzjtkF0cmaqcg7lWnUUp3i+4L5RMKBqAy2PBkoAbR5Y3Y3kq/juwgzEpWVnYExx2r/Tx,iv:COuB4sf6S1Y4eRHKXlj3Mk4oIqbaqV+kaJoB7xjLIZo=,tag:Pjz/WgeEyVH/R9d/wXE6Hw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSG9zRkhPSHRkZTFtamhS
            SVNDSDhvMU9GdVd3SHRCZS9NZ25YMG4xQTFRCjJoQ1hvMUlCYU8xa0EvTzc4Y1RL
            c08wRlJhVkZ4dTE0RCtxVncxdTcrbDAKLS0tIE9kbVFPOHJhY2FYelhCY3hNRUc0
            bmNvSHhOK3VvTzUrOWMzc3ZoR1NaS1UKMGzmC34ZECbJl+7UpJLoPt2F2hSRO8PR
            2WZZxR6/Pen+QuxCocwFcGC0lEt/LAezaN1Cgg3/xwiW0JAsD+4TfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T01:27:42Z"
    mac: ENC[AES256_GCM,data:hDa0xX/L6BKIKo2XA4c9sIh6RNc3tDLWOKskdh0NTnTJ+9P234WtPLkOVramjJbeRPxBcg5Dy2+yskc0Z/eL0pjUhFfzLQG60Ug6Lmb/IOAEiNlAgUN3ul7rUyEKM85ivMFeBdUqD4F+nVwu5LkIcbzl5rfYPwsuIHJnvR5nlXM=,iv:GGVpddhFDO7Y+oyyHSi5YlYyxL8JClWl9X9P3UhdB9M=,tag:iCIu25JjdeyTzZGgYVu0nQ==,type:str]
    encrypted_regex: ^(DISCORD_TOKEN)$
    version: 3.10.2
