---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-discode-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - discode-bot-auth-secret.yaml
