apiVersion: v1
kind: Secret
metadata:
    name: awx-github-oauth
    namespace: awx
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    github_settings.py: ENC[AES256_GCM,data:qfzD0+H/JNSqe6Bp4HUkVL3vre2hgWnINfhLQZvvVjHp0mGlIAE8bE/+K1909d7H/VQtQokmOa1xIHmJOftl7uBSTIzO3y+vzvUr175jSiFBn2X7oKlfMBdHIFCDLO+CwC1JGU8IP/JfnxXzkzPCGx6O0+gk6HYaxYVmsDGENf1XBxpg77dYsGVpQZepOAw5vSHoWC/m58HKfF3CNEUz3hWfoSOenZKPBOIAUAVoxbVWafJp4/8iXXp9zUhRwDJp/qb+KFNtpQhGheZsFV6RLh8jXCsb9UnIQAcf/8hyuINopDvRjceYK2/+pwltZSzm8Z3M0Q8+IwBQCJgxdCEHcPi09iLmVAC0HgO1VEp6jVS8OS6QmbiR37wChviVlE3P2SxVOtSa8cz/pkcekzLrsjwQuytxCMU6uVeDk4yj2VKA8TeRHAc42NZA7WUb4pXPVnLHaj6ZKDFugbrBMQuiz/ZjmtzOFpw/Gl85pb6EEdeMDOd2PoxYlohXaOsctgQ5jD1SPOgiHKWu9Ha8hwz3n4KW1Jfpw6DrW8d8yco5PgdnLKq4NtbPObOZDU8GqtmZZGIvb61BzC/k3aWuNrMsEaZuWg==,iv:z8KHOgffAEys9dFmAGKWlTDGEPO9bhNlP7WaBh0aflg=,tag:qhkzc57mYQstuEFmQuDC+Q==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadnJrcUhDc3p6TGY4enVQ
            L1dRdTRXcFdyV1NJMWRJKzZWbjhSdXZWckNBCjZ4UVREcVUyUEYvTkVpT1o4aWtp
            VUlRN2FWTXZSNk45cU8vYmY5TVNmYTQKLS0tIGhMSmhVRHljWU1kSTBBUjRKcE9G
            em1FQVJiNjJnL1NzcDBJdjZMUkI3STAK5sjeS82Wj2i3EOz4TkK0T7pRb9AUrJcn
            1AZWntaOuGbJY3c0UTWOo3fiCkPta+MCdS24rQn5aQ/m71yULx9Y5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T06:12:08Z"
    mac: ENC[AES256_GCM,data:OjC8/mlWVS2jpzqHz0ttvszx1SpGmcqsM8OQKQLudxTL5wxrjYVdoE+NgZR3j90U/xgrD+4nhV7o5JHZOlOgV5l33xgyLSipu2+iexByyhFFLGyqbowOtzacYmO/h70jpwUoDVPoc216mayJCaOuhJJXoOhECL6aseKYrm4UE1A=,iv:k8ZXOZfP8wmdmbRHan7O5H+o4eNVq8ehp/qITUCHSPQ=,tag:XFV78C2U4KzUvGQhdncpjA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
