apiVersion: ENC[AES256_GCM,data:Svc=,iv:h0GXYY2Dqo75Eq2N2ikV3BWTI4oZ8DANjo0qxxlzdTM=,tag:X7REE2cIx5cQvLy4WLtm9Q==,type:str]
kind: ENC[AES256_GCM,data:ygZHZOAC,iv:RcDaavjUw/MiLJg9kN/AYGELbWqaQ/j9Def+tKoZnKc=,tag:38vLH4KUiLwfUrwsRBJqYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pJhLe1iUtWkZUkKccFAMsQ==,iv:orsI2PLJKmywMJpg1T9FRASjh2o+Db5zRD17U5MFhRs=,tag:LOkkU+3nepQeo0MidBJwbg==,type:str]
    namespace: ENC[AES256_GCM,data:EAJ1,iv:19HLRfHX2nv/lFYezaL7zxhHLD5952VigjKnQs7epBY=,tag:HgT0Stqa86XndcQSLevHMw==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:Eg==,iv:twlXMI/86vxgHSuy9N7Ep/VBKNziF50CxwVhQ6GSgU4=,tag:xYjvjP5OLouMo6Fpwcq8rg==,type:str]
type: ENC[AES256_GCM,data:gPrWHi6u,iv:/RUGPJZq/hxw1d79f2E9pl5p0jYEAwWiKkwZa9zHz2A=,tag:4PB98rYlkKDj0KBJ+2tCqA==,type:str]
stringData:
    github_settings.py: ENC[AES256_GCM,data:AdFw1r/Hhof0+80evQJ7vyrhwrJQkQAmTtJy2x9AJ5qz46MmxXpjP2DEjzhQF4HRdqH7uVa0OPQMb3eHahlZVBUae8TKe2EWEPhgLKY7zAbNrZ4xH1Hf8KAQ3x+xki3vGqHP/vS4jTfehb1uegBpx4C+h98R+9334KCb/15b0HKCF+oiW2j9yBMkW4VPWtTS0peITn1jk6n7cEQPW08PkbxL/wstTjGYaUZ+MwjCXgonRG8b77PI3e6QPmDN7HkPizgvwnBNz/CdXxfSqbASznGx4RVF1qL5bNmZX0sk6myB2R2YiYxtI/58L8argnpYlq5Zj2KUu5CbzEoWrTyZGdpIcr7BiJ8/1s0diHEc3yAXXb/QGmvw02h/xoaABcQ1DGVkxCD/Y0hBhJl7ecRCeVgnd5Oni2WBTjo6BwmFzgOU96yrTsPTPzPsGsNcq2IhRSY5LH1O64tbjPvqm2j06TmenaG06yyc19b6J8FsekvRonAhrhzBEB56mkS3BgzWSoBmlr3UpwY2t06z7Qx9hj+/dEzc50TEBui5XrLPZI637CSW8/FY5Kz1Rsa4PKiF+TnsnjsYTvdDSScil59K4399KRhDosDM8WX/Ri/l7gUSiPYrXqusoSBbd8iBkYUEK4uSMJOMSvbk6+PHclmesrQKykVmrGvHIznEFlN/XRHxnxrKcPo3rFpFrCcXWXedcZDiV7lU/bfKDelqp1E+lxUZz8VFNsENvTQ7DE7RgNG09YHqwkmjQfJ2eDMRjCpSkh4duTotUJHJmubkQF0HVR+5iXiWGL73HWIMgL9nr2F954H/AeHtmGByvYWryQk+ZZ6wEDlkeVmOYtdKavXbQqmBLfpK6J8RoVPen+affCL5Qf72+2RMBGqa1g9cCaYkE43x5WnMwxv5Ig==,iv:vLNn26qQK+Dq0c3/b8rCXuxvfYFI90tEwHPMUasw0lE=,tag:NyakuSRjeMo9DZnDXg6+nw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMU1QOERQa2Vodi9GelN3
            M3hUbVdWVkUxUHRPck5vS283OU1uWWFNOXdNCkNHMXdGSnZUR2JrQm5OdGEwZllO
            RkVWNjVzZHFNVXZMLy9ZeXRobkozaHcKLS0tIEF1dnFlOHVVcUhnN3lpbHJmOUc4
            Tnd3aWwreEllb080Wnc0a0FkSFl5eEUK0SSPLOZnhhf/UngqzDuQXp0vtN1InnrU
            hjl6CwpbBouDygA/uGWAxXZWvdOFWPaEJ0hhi9fEnCCFVwT3joyIrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T19:26:16Z"
    mac: ENC[AES256_GCM,data:YeEVX5h+Rmcavusr8uBimH3o2kN9n52SO9WbLKSS9g9zZqrUFumAomxQ9q3/4aD5mqdJU7TGLJEGubBAZQg3ipfyYLiC7Nkzu7n9xpkU4oJq8HmKEoEa1/fUKGHtT4ZEMlrGAWKqsfayoIz0/TUSN+Rd0m0iZ9lXljISy+BEXhA=,iv:APpfv0wPEnR9sUvPXZyaIGmxrtAJxYM/6fCP5Em9m5c=,tag:vtjW41zJcxZ7Tsz8r+kdjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
