apiVersion: v1
kind: Secret
metadata:
    name: makeitwork-admin-password
    namespace: awx
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
    # Base64 encoded admin password
    password: ENC[AES256_GCM,data:DRrmN4973blwK159PG2UK7Hs/JlTENCqASsGK7BWSsGAu1TYStKpDIRcCSU=,iv:md+xVTpk/GVkR9emvy+SrQLbGRuGrurXZgk8NwYl9Io=,tag:cYxe3h/emjxj+MBL4Yu8Fg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYzJ0VzRpU1FZWVp6bHp4
            MzZQSWRJTFdidWdPYitTZ29nSlNTRS9laUgwClBsaVcwV3dDTHdhelFpYVBhcTla
            SkpBci9paFdpc0xnU1BjMERUREdlcHcKLS0tIEc0NVQyNXVuWmJSRnZkYnVmd0s0
            R3JvWWdOSmlzdjhpaTBqTGNCcit5eXMK86MDa+6MBC4cq5ZBUrIROXowDYwszA+Z
            U+T/WCWSWDuXX+4+XqSXb/8RtmzvRYlai5hX8BTP8D1EXGQrRNVINg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:1utE7h8GHwRP5LYL3Coz6HVj+i9AM8J24zgo0CA/bDzOWWM/hZlPWpLTiki9TKvRd3S2l2vw5CxD6pBF2GNqClCMh5JmxVADQR6bStwYRur8ucAI8rExElepIx8OGcXfaHnRysqHQq/Y5RFY9cdo7PosTB1wNaBTJvgx1h1EwSk=,iv:hYgBnjj2hitfr8WRvgU0BRQ/VnBdpxMR7aMmmnnkqxM=,tag:0a79LLbhzBNRUABTVG7AZw==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
