apiVersion: ENC[AES256_GCM,data:XA8=,iv:mSx5ZXg4g4eCNsWIG7k+muR/bBTONDNMhe3XxRyLUAU=,tag:Qk59RXoThDPwzwgArpUTpw==,type:str]
kind: ENC[AES256_GCM,data:TGkkJG5C,iv:X3/2omssEM7FIM6JGbyfkIwXJucw5aKCgQ1T4PfB0Do=,tag:FaTLoDsC/PZHcA2mcM9pmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:phP7LCe7nJJwXFidaZNMmg==,iv:jH6sjLLY48fZ2ZzfP2qyp7o/Ce3kPJc9H/mQ4qgcTbY=,tag:Xk9k6fS9EVBd7c0xu9LyyA==,type:str]
    namespace: ENC[AES256_GCM,data:aheV,iv:LLFSuOSNcCVrfKdPutw759TH4GEPFa+b5828b6NKbT0=,tag:fHDL1uJCLnn9mHC9SwjzFw==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:hQ==,iv:kf/YIdYRLxD6q/1h5MsQLLwk2nJX9gfKCEOv4sLtiKM=,tag:+R62uHZzq0Xd1/02I1xvlg==,type:str]
type: ENC[AES256_GCM,data:yzGW8gqD,iv:x1eFwekiiY28454sSlgs6/SJ5a7km7UlJuiz1dj1S1Y=,tag:lsz7+lC/kD2JAVPu2BxsWw==,type:str]
stringData:
    github_settings.py: ENC[AES256_GCM,data:kru5K7you7KUfkDRdWiBMSLpmU9OrthDb1Ombtw6Omn3n4pwcZ8UlyRuxDbaMMH7JzZIh6u6qSyzq1IGG+QRVjGq+1xSrasVw2FqAEn5hyWdsZHvWFSoLeNmz8JWYkgj49q2/OU338jY7OAhHL7op0GsEpTBQp9fCYonqBtycVd1y9LlK8cARcf7bU2o3m+8/g2yb4dYtnjIOg4T2iaBNvf6Uuf50ek05nZi1BQrDjnLUKhxYJKtWp3vQpLECUWRfdJo8Fv+q5Gzv8sv4Zn1lyKI/SuTIbTl9tuAlN01xIvySVdUOVYPLtZTjQaBBo5jUE5LFyLjZppU6bBMdTZIkH5wz0a1EiwIHjAigsPNyK/EU2mUcqneM15NaPnR1C/J74hvExh9VIKblK5iwE2jEY5urO2UJYucZGyHO3AbhbhdVpPpF5NhGh3OLe0lATSnANvUJ7bSr5Tw7QAE3BU40uH9+1oqjXTNU3qElJ5XlChBVtLQPe/JbsbhjeZJWUXZPHqoSqMMR4S7g3zaMXLIqobI7m3zsDDdbywxkwhfFoI55jhAJiT3LNf2y+nZwbhxHrbViKaBfF/PHQeaDlqGhd+4ahEPtM42B7Cz3Kr1nJvrytgy8H9K/qvu6yzBEu6BGCVPPuK8jvKOuLfPvC40/7yAdzbqR9JE330vD3+orsAvRRasmPk9f4oze5pn++oRHfLW/IXPCmB4NNGQW2A+n5PcjbXcrkmaWU4B1PNS4hOLh89S3SpOXk+g8cv3viR4l3LfIRyA+yxvYvj5uYm/7x0F5S1Q20SVkdgbM39T5wbItjT8AvHD7AWMUS0BY52US7zpve/8uhmGYhwaQZAq0qVp8v3FSQlghFFNl78Vn7QJgqGnO6HaRPJeC0HikJ7FETYgF9g6H5iyL+RTygMzt521KZFTXBqeajmlezicQ/nap1/cjOv5fL6bhlbhEdFTHyY=,iv:kPpg5OH5xVO0vHMtwauGA8qQpC8yoH9UEfeUwdSi8po=,tag:VUaBEOYvWrjs6mHG7e8pQA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbjI3Y01BYS8vMzByT1BT
            MWJiS0lhc0Z3MTVsajIxemdjTDFJSnlkdkZvCnpEMS8zUFNIYXA1NERGUXlNOHpX
            Z1NKN0JGZ0E0Ykh6elZkQmJ2eEJMalEKLS0tIHZsTVFaQmFSVzl2TW5XK0VzTEl6
            VGFHVnQvZjBYdldrYTVsWjM1Q0RnaGMKqpAmULQgbrlLoNmm5Epz12+cz0ljKQ3z
            A+osnR17FzEWsrFYOoXNljaJjichQbxwPMLbZd8B1WfNjpJLGlODnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T00:00:22Z"
    mac: ENC[AES256_GCM,data:kDRr8YPFi6s2NfWZGW17JQ6qz8obZqUZiSM8AVkO4pUpey4X4MQ813nAnfhw9uJikfX9GMjVQzQiWB9iEjd1t66r+9XyIUibZbJoXlxvrNxdoK+D5sBawkHhD8jmEjaAG1qiGGG3wTJlqfD94Q07UWbwl5rsccwe6Pn8pmvUTaE=,iv:PIZrJeKtLQliUx2BR7x3v3fjjCldId8A+tNy4dR+iOY=,tag:Msc6mFp2uDvKXYkNUYPIGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
