apiVersion: ENC[AES256_GCM,data:o5M=,iv:6SR//TsE1j9PsofGqGTiCDdoKfqP5CgRfIRiVlBNw3M=,tag:aMBAtUDiqzAX66mux8RZ8A==,type:str]
data:
    password: ENC[AES256_GCM,data:QlWWryIiCjNgBmmqIZBaZ87FLshvm1WiB/soMGxjKZugpk3m2gD+Cw3E7Bc=,iv:HtEu0R2+SGyCX/3xhbUQTdow8Ue9RT1KHB0IU21uVaM=,tag:v0hiVeVfzsBwGAOMMBsH1g==,type:str]
kind: ENC[AES256_GCM,data:sGWtn8aZ,iv:/xAGBuvhjshPStrYszN5IKS5O0XKBQtF/jz9JllYEf0=,tag:VmXV7tFLXeGNXtcTNKw9Kw==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:Lg==,iv:XHLsJdWn8HraHgmgfmiFVcGTC8uzqVSDrR96NofaSsA=,tag:YgZ2wBEIVyBzf4bz/8vEUA==,type:str]
    name: ENC[AES256_GCM,data:maDtAuAfadUC+v5d/bNFfL+Jnle6xK6oJA==,iv:RjzxyIjDnq8StTw61TRL6qAMp8Vb41NhecQlOyhGOOo=,tag:Qp0OuTtMb3r+YJxcYd1l3Q==,type:str]
    namespace: ENC[AES256_GCM,data:NcG1,iv:RWYHDenA76PD1+nj6Q8489yTOohTJOve43jPcVrL3PU=,tag:1mzaosOsY4KObZi6W3WXYA==,type:str]
type: ENC[AES256_GCM,data:ICK1exwC,iv:AUTMm59lPyJjY1rEmM6FMVim776psKRxFd5goUiLC28=,tag:9EL+CiLQvW2FJs+NYgldFA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM2I2M0F0eU9ZYnNrdzRs
            WmtMektybFFLbnhuY1d0ZWdEZDBMMUQvcEdjCkcwZkkxdmlya3dLK08rNEdYUmVM
            UHFxc0dnTkhXd1h6ZTc2eHdFVDVCcmcKLS0tIEtMTHVwTTZlOHk5VnhjL0MwWTBY
            RkRGUWI5SkRyZXlySDdCb2UxSGRXckkK34dkxZ6Usc1hlWnVqkjuW7ZCRSlCGAqG
            saEBu73gjAV0AHf4EVHcpSHIowcLuV1cOMN0QLluD9AdAaPoZXSQMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:44:49Z"
    mac: ENC[AES256_GCM,data:tzVsaEg1ppHOZMgG/s0mMhV6c9Z8hEq+4gKNuylhKg8dhOSzZJ6jP78Rqo+fEJtcaA0E7cf4xDEX/TVxpXCgGbsS1Ogohr1avnE4Ve+Ru6esyXqknJKlzBPdCff1oCT0qaPizmBXebQMrdttoq7PtipAh05KioP+qQ+JYtVSnnU=,iv:OEgpDYgbNjVd1eUkrq8AcA7wn6UfwLLO1twtwe9D7LQ=,tag:2zqUe6H9J9O7m3vYllkZDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:R3znoA2xIffd3Kz7Q2Uf9QQxOrD4uWg=,iv:ZhWyjTQHYTxpIIMZg7UtDkO7ZfwM9u2oxZ44uyAEMwU=,tag:ogwt/IDIYlOpvVJXghgAOA==,type:str]
kind: ENC[AES256_GCM,data:eOnR,iv:n3J2powIs+YWzAJwGvD0rYD+l6PKO0N3ZkwSJzyqxCg=,tag:mxpqCxgYtS7CC1MK3TnwpQ==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:tg==,iv:5IacCkJWA6H5K2wXqb6tAhN9srYjO90USv4/Y92piEk=,tag:EnSBDjHrpYfEUF4K6rZLuw==,type:str]
    name: ENC[AES256_GCM,data:ngXY,iv:ELcz0MVdV5z7bKEYoXTM3CTLzZl07onnmJ870HHAVDs=,tag:GXXQt1RDJlVPVSv0Eo0BMQ==,type:str]
    namespace: ENC[AES256_GCM,data:u+Rm,iv:ZPEyPlcnLtbITywUNkQnoyT9HI/R0ijF/0ncWAUD/o4=,tag:3UicxqY9HwYnLFswSUPksA==,type:str]
spec:
    admin_password_secret: ENC[AES256_GCM,data:bQb8VpkEiMUeSBib7U8nezW3IOPHHWoPZw==,iv:swC5aaDLXMTNds37HX/mmQpGeVT+NdoeG55LW8dYKtM=,tag:VzSARKoStteiKgcZMWSoUw==,type:str]
    ingress_type: ENC[AES256_GCM,data:ezUWsEM=,iv:/QHVTQTM5BFKKq1lBxEjMPUwfDhCPOlk3OziLSW/FWs=,tag:/TD0yoE7kd47s7S/g/Zl7g==,type:str]
    route_host: ENC[AES256_GCM,data:ZBX/nSo1j7SBaylfNUJwoiSv79boiDnT,iv:57FcWg1WCWRKoZyO1ZvoIpdz+aCk52nZEqSzDeJqJbg=,tag:vS7aSYETwJ5VAVfX1vrdLA==,type:str]
    extra_settings_files:
        secrets:
            - name: ENC[AES256_GCM,data:Ikm4smSCCDpO9AsWvqKGoA==,iv:kp1hLbUvYXByEKCRylghtkOfJKtkW7U5FyRD3g1zcYE=,tag:5qVsy9Zeh86TzSG8U8QTDQ==,type:str]
              key: ENC[AES256_GCM,data:QRXMRu/VZYJvcnHbqehQJhTP,iv:kJ/L6gGxT/y+gDIaMCz4oySddqoBBhnvRGp2sCdREQ8=,tag:lVunHtVPy1+m24RSH83DAg==,type:str]
    extra_volumes: ENC[AES256_GCM,data:4nnHeLvBms9XOXqzFP8tDvtYyQSo+nm5iQGK9I1bHCaOhbx5Knwzsp9qcWkvGw2MGK73FFVyvCHtsEAxvl1Hyiw47x2BnPwoQBCsSp2aRoG2RsxJ0feHhP6mgMIhdkCaHrkNNOjdr0G4z6NfNZ6lRYVv65l0wvMXQ+BR8pQ9IjoGGV2qw20cKV76JY8joiuK3GGSCYUY/ZmalQXhAruf14oUWeoIc8IkH52dT5/o+qyl2DWU0WKg6PGMdRs7uPRIUmDWwkLj1+GgepMRh9XPcaNHVvIc6LV1DEwq3F6eh3AgpAWiBjJWyyUW6oAcaofbzUA1ugZUDVdBpnRFm33z8oceb0AtRlmNsx/kGqNRiGa9o8SvrcfT1wKYr5uoJhE2AMd0HUGT10Kqr55VQCvgxTrcQ9QFp5R7hWuwIZMqsydCJVt4k+GJydSYpNpQZjgT32bAv7R40diwOM+ukAWjS3HndQZSFnhYtvul20zMhmhbhyEc,iv:btc+ddJljdydOcT5cIP03VVD+Pu5wZ4pW9surPsy1wU=,tag:LAxlTPR4YcfSEsvpcbiBkw==,type:str]
    web_extra_volume_mounts: ENC[AES256_GCM,data:4+eKCyhRGyWsUuh1QU+WtqjhxSvgjfwJ2ylBOm2E+blJN+Mat53ifdlD8PtkXfKP5/UnDshjNXy/hgY7bceVwRZ4aNKxpQfdyS/Zed82OApv3/cJ7c1f+OfeLgrjtfJSAqs72O1BKkLQJ9lSjeRG3hibHvk86m6GJOAHrwpcHDSsBU+r4reJduYxd1Pkzo2l4k1GWXYtZJ3icTxsjPCf4wTmeoNoKbz4kv119rsmgSGTQ+SAjRjPu4edxQy/LZOwg8W+5UPXzW1NgfDHmaWyM3o6cyu4NliLxUxODnsXri5KtmszfBeUKpY1WvmK3PevvCPokxiwKkQaHFzY5AnKNa3FIRGiNVC4GT6lsnCiZGsJYaz4VLVZNB2xUGCQdfONLLRJtGFe+hVLF0AoW3+yVkJxmvEey1H7mNKL5ahQtOa9IFn/+ZOLgMKLbSbO,iv:NJ6z5Pi4nuAgSsT1YUqFQMlu/wBSN5QlhLPSV38W8qs=,tag:VUsPmdUSuiitlwdSY9YzTQ==,type:str]
    postgres_data_volume_init: ENC[AES256_GCM,data:Z0LN7g==,iv:gm60EfjmskquselYLg4WmfXP2YZx6cffsHdP5c1nMqA=,tag:mpPkpWXJNZQqkOe39EbGag==,type:bool]
    postgres_security_context_settings:
        runAsUser: ENC[AES256_GCM,data:0ek=,iv:H1IFFxsuCqcsAdpUzpYV/Qw0aUBovE3SHqtrrHzSxP4=,tag:Z2sHJUSoFNep/qf4PTfQTQ==,type:int]
        fsGroup: ENC[AES256_GCM,data:3wk=,iv:ncbzroNvY78gcb2j397LMumwb/FVCZUTagFc5zY7v9Y=,tag:amolNevPU+B4BVx0Qj301Q==,type:int]
    security_context_settings:
        runAsUser: ENC[AES256_GCM,data:UPs=,iv:1dF0VRT3VqJmUzNdiWF/tbGMDuWmNte/vaxe65U8Wy8=,tag:rvr4inL18FSqVBmOz8c/dQ==,type:int]
        fsGroup: ENC[AES256_GCM,data:XJQ=,iv:NO/ImnVvJ4wfc2no6B6oMFax7l0PmTAQjI0CQ7UM/cY=,tag:6qYcpPEbflP2JIgd0dWTag==,type:int]
    postgres_init_container_commands: ENC[AES256_GCM,data:n1QzNRs58CqMBhBne5TyAXskiGbgymsUoGAbJQ4LNi24qfCoVFU4PR7+pRrnUUaTpDK8sT9vXh9pFbcTbLGUNgbrt8eVZaox1gLikxKmvuqcyCiJEsEdJya/meGc5C4iLaVTWEKZbxGcjWDPD+PL4rkKtn0k7VI81sVCryrEUstCCZFZPBZ5/7xedavrhwAWqZ+6o8lO9lJmwqXt0bRfCK2Iaw==,iv:W9UsH+uFZe+n8QzAN9uzLdaka4Qd35RDrrRcBDb+FEg=,tag:U27udfUTZ4NrbDEsiKNAUg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM2I2M0F0eU9ZYnNrdzRs
            WmtMektybFFLbnhuY1d0ZWdEZDBMMUQvcEdjCkcwZkkxdmlya3dLK08rNEdYUmVM
            UHFxc0dnTkhXd1h6ZTc2eHdFVDVCcmcKLS0tIEtMTHVwTTZlOHk5VnhjL0MwWTBY
            RkRGUWI5SkRyZXlySDdCb2UxSGRXckkK34dkxZ6Usc1hlWnVqkjuW7ZCRSlCGAqG
            saEBu73gjAV0AHf4EVHcpSHIowcLuV1cOMN0QLluD9AdAaPoZXSQMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:44:49Z"
    mac: ENC[AES256_GCM,data:tzVsaEg1ppHOZMgG/s0mMhV6c9Z8hEq+4gKNuylhKg8dhOSzZJ6jP78Rqo+fEJtcaA0E7cf4xDEX/TVxpXCgGbsS1Ogohr1avnE4Ve+Ru6esyXqknJKlzBPdCff1oCT0qaPizmBXebQMrdttoq7PtipAh05KioP+qQ+JYtVSnnU=,iv:OEgpDYgbNjVd1eUkrq8AcA7wn6UfwLLO1twtwe9D7LQ=,tag:2zqUe6H9J9O7m3vYllkZDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
