apiVersion: ENC[AES256_GCM,data:Cqo=,iv:rY4Xb1cMuRurTSmJmf+/VCqVC8gYgsaFan1SBmo7LdY=,tag:wCgLeD8UkfNMZS33Rwp5IA==,type:str]
data:
    password: ENC[AES256_GCM,data:VfImk8m/1JPTJ4NU16Erg5gYdppAX0y40mFxDpsWJQ4PN6i3FRYSR03O6nE=,iv:JF6nWSXS1N1q1r+LojaRqBjR/K+ioohqJg4/A8muMKM=,tag:ruqNipg88178Dpro/9ybCw==,type:str]
kind: ENC[AES256_GCM,data:CS3/roTr,iv:Ox7eLANNHhGVb5b17IjvkDMUYhrhf2qvimNcIKEfuXU=,tag:gqu7wcJNp0v5TvCdMkV8wA==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:Bg==,iv:1oMIeshLBPDUs0I9Lj5foXK062mDgxoZiyqBTQ3cA8w=,tag:uNC1zGE7bVs2EFyNSEbbow==,type:str]
    name: ENC[AES256_GCM,data:gursz66ESEKccOON2jbkrOQsOZX+SxMhIg==,iv:pP1jW37CVRIMjlbmA2+7V8X6Bxs2KT3li1UWLoHLTIo=,tag:8G69ANIDZK84jDeBeTxQEw==,type:str]
    namespace: ENC[AES256_GCM,data:DMb8,iv:nH56ftLEiwBJRofkmz2KCQ1QSZP3jhv4m+kkBvPGyvM=,tag:FZ37gcqN4fJp3IihqDbqRA==,type:str]
type: ENC[AES256_GCM,data:eZDpJFNz,iv:A1yYSFrOxZH+2iqtI89CXCF1vfNb64amIEOU4d4mRbk=,tag:MazKS+v/HeDUtdzc4YiE2w==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVTVFZ0Jpd0h1Qi9vcURm
            NU9CelVEQ3k5a2pCZ2xnVy9YZ1hpeGtZVVZzCkpmTDBHaHVhcWNOOHA5Mm96bGNs
            ekxUTmFWdXJscHQwS2Q2M3BUcFo0OUkKLS0tIHd4S082cjY0c1JMZXRBL1d5ZVFG
            NTI1OXhJS0Q4WnJ1ekRrNzlnQ2g2d2cKcY8uhbbrwExKqD4Ynnx9kiFFAlCx20vS
            zRNUnXbbsMPckHnWTCsLqyrA8qSIHis+TlNXZdklC4xer1d2+RU6TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:10:58Z"
    mac: ENC[AES256_GCM,data:VNKJheDt9o3lCqHZNOHYJmKw9zZ4tShEIVlx/QOqp6atuTl11kxxaXO2BO0Ld9oVjSiILxDvpcmnUIiX+hLu2kdnRJJsDeKV2PWL1YIEoXOyoCAoXm1ko2H54wK6jOO1iB+C1Oe8anKN+Zt6TJDcjfRY3q5Cd+g0gHlqyJKy7J8=,iv:M2+synyXrxT8eb5me1aiV6GiTr+6P6e92xLb3+aHHhc=,tag:jbyrcGPKHMuXWeiNQ+5bCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:lNLmAeEyRTv0JB5jI1uph9NQFZXAkbA=,iv:x+JjRwce6QDxa4BCZyotjwrf5YQqjlhy/JA0Buxxac0=,tag:VfecmxhY38ciNn8OiHmyeA==,type:str]
kind: ENC[AES256_GCM,data:o36Z,iv:keV0QuDhkkft8FpJr4DbvJwIIz5uFX9g0KXZP3GUjno=,tag:GRX1rl17F4IhHr21ldmCxQ==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:rA==,iv:sm3lObNxoYC28f651UOyyAtmwSo4M6mrx3I8xiI530k=,tag:e0jDFmzrYS3yaTTM2RNsfQ==,type:str]
    name: ENC[AES256_GCM,data:OXEW,iv:sGeml60IvntTfKExx+J0opZpJt2g/GXJ4zUHpHIGnwY=,tag:ApZUCTGYA4jR8TzdN1wK1A==,type:str]
    namespace: ENC[AES256_GCM,data:9uw+,iv:IF4h2q/7/aSp49t/bGOVX+y67YDP1FEh2OE5yxy3nGo=,tag:e6VnrOiVAJCWqrGW+UPZ2A==,type:str]
spec:
    admin_password_secret: ENC[AES256_GCM,data:0WGH+dRLqM0DxmisOFtcnpcPE5RknBnqtw==,iv:OC5jStyoywxJmmdju8BGYCSSaGiTUyaSBmaOeXWqAOY=,tag:tkIE891ZUKzoEinFGfD8OA==,type:str]
    ingress_type: ENC[AES256_GCM,data:yIYFMdA=,iv:+EZDEidwQI4/6WfJ7/HAzKZNamnuwzd3eP2EO0iLM5s=,tag:LCoL2lWFVYinv/IKmF9dXw==,type:str]
    route_host: ENC[AES256_GCM,data:HYmuOw/u60He/44khyKwi5h9H7wbEPRf,iv:oPq9q7GHF6MnvRHpfeWu7tRmAje6t4G89Ltp3zNsJvs=,tag:fkhvI74Xe/4F5+fqL5wSdQ==,type:str]
    extra_settings_files:
        secrets:
            - name: ENC[AES256_GCM,data:vhKbQ9r4uuWtfu+hNTbbGw==,iv:pZmMX31fO8+gzdnl1Dp2dH7afvx48MPX0wwKcpVKzgw=,tag:NxSzcKi/xhnHqzXtCKBEAA==,type:str]
              key: ENC[AES256_GCM,data:csYrgaCjq+blNED4fpQ/dYT2,iv:vijaR5RyAV89SWJYDvJNgJ1kV6xM55HblONCukp31b8=,tag:RtL2FCff0LPidfRLZgO9GA==,type:str]
    extra_volumes: ENC[AES256_GCM,data:saoWwWnF4sK3xk+CFmiD36Hfsm1V/GEIiv7+7Fa2mPVnIS9kj1xGfdW4+1t0tRaTz0zQnHuM9JUrjjkpttqDf4iCWjPdrJsSStIu2f6ZMoJUyblKaRttaf46DKq9jDfYEd6MT7CfH5DgMSJxHtBVNh7Ux2t5YBoL7LdYqWm3SxRDUHkJDj6bZ0eSMSZA/yX2pUHwpda87v7SsdvKqCxVYj+6dmX6GApVTxxHwd1FGgvyX6WRyuftppkSe3Bmzli+LY0Q/Ua4oxLG5FvkQ3DQnQHcyiNBsxmamrrUGySdJ1TFWLH44EYETSG/S1bCuojDYsBHPzLq21Xy/ymqx5el6dMiwPDrjkg8hOCwYM9rfqk4njsg41/JjV7EY1zThB20YeLZvXF7subMTgCXk2soHEdDmpTLPqGyj6h45z7Y707aykXmpuvFoLjtOHTduPqntE29VyzFyOx8ZEJ5pMHIBhiYLfLHrWI+1xbCR+3HMxWMZxR3,iv:tmbaCRd6RO1zm7M7QtwRHCUOK/brPxuYu3Jvwh0NVsQ=,tag:Zke1pCkyyM2i4b4UY6ILGQ==,type:str]
    web_extra_volume_mounts: ENC[AES256_GCM,data:cSeHZ0ZMid2P0zTBZu6emwJQsnaCFrOeJ/VgQFKn1/gbSunR3T189hQ4otEcD2MSL+7pGdtdgjeoLYvrDovwN1x+bqzSI5DUmS5F3dSUWatSRv6UTXSuvn0KsYLMwITufpyhe4du1ViZ9dh3xxTQr2ThnSrGu+28xAtiwycZ3cpfCDsGZD/PCwSQz5vIApGgi0fuqu3IKzIuMM7Bmf1dD6/476QYPkdQjK5i7ms+nW1gAwyKHlt9wn2mEPJMBwLURn78ANRlfmWw0U6F9zDJWusXbF4jMvJX5goAA8/zir3MQOgPZVYP0pOPbdhu7pAl++jhkygIB+1aUZhOECSVson0OHZA9ygBL5Mbaoqy4FdvAOkYea4MAZbGNXh6j9ne94JtwG2Z0ZWhIO/nkmd3lakJoei0r+nRLBvAfrl+dMr1ee4pr65rf0NOef5B,iv:0xDR7UROb3QRqpUt0Q7tKDAHW1jMnRfNTrSSchuTg4Y=,tag:Rm1Y+jXp6K2mMrSh8zZtXg==,type:str]
    postgres_data_volume_init: ENC[AES256_GCM,data:P/Cgjg==,iv:YRJNJUGDGsScBKipIOslLqZVN9JSe4DVzdPo233Epnw=,tag:8VJ1Fdy3kds7KTGcrEC4hg==,type:bool]
    postgres_security_context_settings:
        runAsUser: ENC[AES256_GCM,data:cg==,iv:UweQk4LitsK9kgkqBqxMjZ6i6bYfhIwmnodsQn4AcDU=,tag:YEmVYwMp+w6ZZ9J2zeEpaQ==,type:int]
        fsGroup: ENC[AES256_GCM,data:yw==,iv:Xs2tL2fXuOpovlTRntkVuqrn50Q42bSveopawniZc1Y=,tag:Obhrop+/h0Kg51iLWQdtCw==,type:int]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVTVFZ0Jpd0h1Qi9vcURm
            NU9CelVEQ3k5a2pCZ2xnVy9YZ1hpeGtZVVZzCkpmTDBHaHVhcWNOOHA5Mm96bGNs
            ekxUTmFWdXJscHQwS2Q2M3BUcFo0OUkKLS0tIHd4S082cjY0c1JMZXRBL1d5ZVFG
            NTI1OXhJS0Q4WnJ1ekRrNzlnQ2g2d2cKcY8uhbbrwExKqD4Ynnx9kiFFAlCx20vS
            zRNUnXbbsMPckHnWTCsLqyrA8qSIHis+TlNXZdklC4xer1d2+RU6TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:10:58Z"
    mac: ENC[AES256_GCM,data:VNKJheDt9o3lCqHZNOHYJmKw9zZ4tShEIVlx/QOqp6atuTl11kxxaXO2BO0Ld9oVjSiILxDvpcmnUIiX+hLu2kdnRJJsDeKV2PWL1YIEoXOyoCAoXm1ko2H54wK6jOO1iB+C1Oe8anKN+Zt6TJDcjfRY3q5Cd+g0gHlqyJKy7J8=,iv:M2+synyXrxT8eb5me1aiV6GiTr+6P6e92xLb3+aHHhc=,tag:jbyrcGPKHMuXWeiNQ+5bCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
