apiVersion: v1
data:
    password: ENC[AES256_GCM,data:wN7XoLZ8r8wRcWuP3FmWDdKo1++kPrBGNt49xclP2jZzW0sbIw+3nb6m3wA=,iv:hMXsgqMTdz/MIRGr93iU3UMVf/AW7pAaFwjixbawqh0=,tag:mD+X6uSFCg7hAZjGuAGEAg==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kustomize.config.k8s.io/behavior: replace
    name: makeitwork-admin-password
    namespace: awx
type: Opaque
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ2pEMUVQRWwvSXVLUXh6
            MVNqVWsyQXFETUJaR29TbVVrZTRNUjNDZkFVCktRaUp4ME83a09Ia0JKTk92bW9K
            L1Vydjd3WDlMcDgraVdNcDZrWGdqY1UKLS0tIEk1d2M2a2g5Q051aGZha2E5WEdq
            d0RpQXllSlF2Yi9lWXQrWHFmemEzWWcKYLWzisbEsYDWe6C/oNNHB4nXgxU82Ibp
            I6DD5z1UnnODxooeFPNrUl9aVwlwTNGngBD4s+Uu3UrGYdDK0nscNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T23:42:09Z"
    mac: ENC[AES256_GCM,data:nDbXu2VoHwpk1wbDoGLK90wbYiz+MqUSVa/j3/21c2B4a99Y/37IVPIrlPm3NpqEfZ4y3h81a4neWAkNmGr0mR/bT133vNEuK3PtjSV/CrnZlOEEFuXYdm+9uv8gXBzTR8O8h9+OhU3Pvi8hiUmowpVTNpPK0UhP9jWzIYiG+Bc=,iv:SbJpF/nVOiJtLeeHwuFEpYzW1dLD1EQ7zGI4J1sAQ8Q=,tag:QOyn6vZZ3D3PxbbP5DhWkQ==,type:str]
    encrypted_regex: ^(password)$
    version: 3.10.2
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        kustomize.config.k8s.io/behavior: merge
    name: awx
    namespace: awx
spec:
    admin_password_secret: makeitwork-admin-password
    ingress_type: Route
    route_host: ansible.makeitwork.cloud
    route_tls_secret: makeitwork-tls
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ2pEMUVQRWwvSXVLUXh6
            MVNqVWsyQXFETUJaR29TbVVrZTRNUjNDZkFVCktRaUp4ME83a09Ia0JKTk92bW9K
            L1Vydjd3WDlMcDgraVdNcDZrWGdqY1UKLS0tIEk1d2M2a2g5Q051aGZha2E5WEdq
            d0RpQXllSlF2Yi9lWXQrWHFmemEzWWcKYLWzisbEsYDWe6C/oNNHB4nXgxU82Ibp
            I6DD5z1UnnODxooeFPNrUl9aVwlwTNGngBD4s+Uu3UrGYdDK0nscNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T23:42:09Z"
    mac: ENC[AES256_GCM,data:nDbXu2VoHwpk1wbDoGLK90wbYiz+MqUSVa/j3/21c2B4a99Y/37IVPIrlPm3NpqEfZ4y3h81a4neWAkNmGr0mR/bT133vNEuK3PtjSV/CrnZlOEEFuXYdm+9uv8gXBzTR8O8h9+OhU3Pvi8hiUmowpVTNpPK0UhP9jWzIYiG+Bc=,iv:SbJpF/nVOiJtLeeHwuFEpYzW1dLD1EQ7zGI4J1sAQ8Q=,tag:QOyn6vZZ3D3PxbbP5DhWkQ==,type:str]
    encrypted_regex: ^(password)$
    version: 3.10.2
