apiVersion: ENC[AES256_GCM,data:sOM=,iv:irxHBODXiJ25kRtl17tZRh0SauXIV7Py4FcnRJL+Grs=,tag:yr7jvgktcQ9eTY9sSp73LQ==,type:str]
kind: ENC[AES256_GCM,data:xbHOYkQF,iv:weHdV4sXmlZ2Tc08HwXPrc1Lp8LhJtwK7toD1G25jns=,tag:solSipu2JnmTxfo0/HMRWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DQd5QFbYCrICy2w8K4dR4ZfzJ8GXw4E=,iv:MOu516VL/DvEZ4n+U73hiWr48Kc6OwPg+W72CtDM6QI=,tag:dJ2jys+xMYRok8urXtMqgA==,type:str]
    namespace: ENC[AES256_GCM,data:CryV,iv:nvK1FUZUtpsWIgtsdbEFxy+YtY7ZtHSKhVMHsupor1s=,tag:gLeuLtscbhBkpbxy2ivJWA==,type:str]
type: ENC[AES256_GCM,data:lxxZDwFF,iv:yD/EgbGArtJEWdjlUuLWQGQ5NHrH+nUz1PolKP4t1GM=,tag:gwlsrt8W3qgHJEzXOZa+Vg==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:C9XtudAdrFmBd6R59WqmHUyR2feEu2JG1pwTCnj1DrHwDNr4njlLH1SAJYRTMDyHzv5OijV5T4i8kHTNp5ESH7qUgRDGYGaGdMmS0z+APQ2lyDuHbrNnGL0Z5Je8ByJbKpb8taU6ttNqAXt48b5TDROq1oWmMrXY9M0wivG/MQDR4l5wj9ID8k9zfmm/DYcUExdbLNC/B10rTubfga0WgxJ6,iv:d770f1HGzvwf5WIE62kWtNfw2xGyeWfrO/2KFD1T06c=,tag:h6t+Jri0szLHoQc2i+txDw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVjdzNGkyT2Q2Z3hqdnc4
            MkNpWVlFQkkwNUliM0R5eG15TWFCYXQ5RFVRCmhOeHFsWWNWKzFkbkNlNzY5UkE1
            VlJRKzhNS3FYb1FxazB3bHZld3NjSU0KLS0tIDJYazM4SlFwMkRXdXdHbmRCY2xF
            cENkNEFEVkhtVnVNVWZzdDVKUnRrY2MKU6gSWntb24AWfQ0OMuXyx7U64wSSDtTO
            5ChOyt0hr4Wtw+szt3jxovTTVoPoBTBB4Gsij9vC7a+MHIO8NP1bXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:28:16Z"
    mac: ENC[AES256_GCM,data:cU+hJbgNbhsF8ygK3jZjhMVswubYfcVY4BGS/fXU+iCwsOKiGcIkeaRB4eOwY/5/rOV7fuDve94PlYKQOreZJM6a0w394LfLaourApmg4lzmybkPh8GtYXGobx8FsLOKgvmZ5ZiIk/qhe2sfj168gl/FIYpzb/mKRwhy2GbfJJ8=,iv:iaXpReBJRk3ZelS5s+Lbr6xgfR60SkiSlq+Y7TGdYxU=,tag:rW+I+8RlwILppaI/yUVO1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
