apiVersion: ENC[AES256_GCM,data:RfY=,iv:SsENPyjZY2R/ZIug97DZBZcu/QODTeEGxGd/rzH5kLg=,tag:NHd2jhS7aH7gkcj6lr8fWA==,type:str]
kind: ENC[AES256_GCM,data:PRI/F28o,iv:mjENf4L+Lq+679yxA8Y8DLYiYKNNGe5v7SljWDTG1Jc=,tag:V9L9s9x3gP0oW0LKkVV3QQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FlMTs5+maiL96Yxv8+/rdzc7WoKZC1c=,iv:M75AL42i7mZcpbvdf4Pgp3l4ywzDyA/RJtnp+6yOZKU=,tag:/i7KXvsSg/FaeYe6ZH8PcQ==,type:str]
    namespace: ENC[AES256_GCM,data:lyQj,iv:GFdK91a8dnvirMxXZWM68ldyrAnPmOTyCfZooGBKq6Y=,tag:FyVqlCxutYVrmCm759I1Jg==,type:str]
type: ENC[AES256_GCM,data:5JDq5oNw,iv:yBiR1Avwhen/Aa/InTeHiJh55b5q8BrU1qe5XsmsEbc=,tag:N3Jcn0JQPxAv9wGkywMbgg==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:8jQfKBMzjThHXR00PimKaviLS1ihCHW8JcZochUaH2TzjshdETGic4fSM4VkZGMF0dLrcjeaq3pXk6eq2680J6ddh4rxza6Dnhxfnoi0/wubMKPyxrsaWFsgYSQ3CBCvDg83mn0+1QLwsVv0ZEHOgnPX/Qc879ShvC8qteoO2nXYsfFVkkXH4MRo65RQY1+e4agNIVvOodocxaeOFKXbtxg7,iv:WXNV11co7RqbB+2O8skZWJGDJI1oVU1IcSfjyfLWvyo=,tag:vCj0JAS/mkiD+6E7DYhsZg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucEtWRXlPdGF4QlhXWXVH
            WGZxL3B2R2FWQUVCbGZpVFZtdVZZMjdtbDNrClNjMkNYbWduQ0JtZVBnWXo5R3pw
            N2U3d2prWTY1eDV5NVRjbEFpZjhyUXcKLS0tIFNKSUU4d3FvbWxRMFN5ZjFIUFFI
            dTZkY0FYdGdmd0ErZG8zZCtjKzF5Z0EK5WoQp5cQJIpwAEslWhb3oi86noE6htG1
            YU1KpAZXyaN+nSRGzc01owAMS8pHg9iNCOqgTjviu7nmAA8C8DXuOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:17:57Z"
    mac: ENC[AES256_GCM,data:h4YgQpy8J/NqJDUh9Z+6srORzHSVhYYcGKZ3AgGnPxbQ0bg9/qcn4RKV799rshC3lRslRk264Qt5kFvst4/zXdy0YAqKuTcw+vTYFEv4NNAsUgX/fbhiEaub479cZJmwt+SRlWd5UhE75qBmR5lkh9nupTgRgmUpgpeAkCKeaEI=,iv:uwnjPL9CRhkYIgRccOY9+dOLr0P45Z1raZ2DxdOk45Y=,tag:q+vpJtgDcoJScis4GX/mxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
