apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-ansible-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - awx-admin-password-secret.yaml
  - awx-github-oauth-secret.yaml
  - tor-proxy-key-secret.yaml
