apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-awx-github-oauth
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - awx-github-oauth-secret.yaml
