---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - awx-logo-configmap.yaml
  - awx.yaml
  - onion-service.yaml
  - tunnel-binding.yaml
generators:
  - ksops-ansible-secrets.yaml
