---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tor-proxy
  namespace: awx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tor-proxy-privileged
  namespace: awx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: tor-proxy
    namespace: awx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-hidden-service-keys
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-proxy
  namespace: awx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor-proxy
  template:
    metadata:
      labels:
        app: tor-proxy
    spec:
      serviceAccountName: tor-proxy
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: tor
          image: goldy/tor-hidden-service:v0.4.7.12-54c0e54
          securityContext:
            runAsUser: 0
          env:
            - name: AWX_TOR_SERVICE_HOSTS
              value: "80:awx-service:80"
          volumeMounts:
            - name: tor-keys
              mountPath: /var/lib/tor/hidden_service
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: tor-keys
          persistentVolumeClaim:
            claimName: tor-hidden-service-keys
