apiVersion: ENC[AES256_GCM,data:eE0=,iv:Jm5Xu7jXSfbRkgIH76AOT2j7gbm+GODuu/oEhep5lOo=,tag:RhafMz3h/tNhFI2GXQDG7A==,type:str]
kind: ENC[AES256_GCM,data:VzxdnxCN,iv:vAX7Jlqd+0J3VPlSMg2rG1hs4dEl+rWASLnJVqR98g4=,tag:hWXxJIDC1euX1sivQHEu8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pkS3gHtjvF8vEex1Tw==,iv:pOCSpzV96MYd0Ux8YF8O83Vsb8FTwak59xt+GEl32KI=,tag:ll6e6D1McD54HKiY2MkXjg==,type:str]
    namespace: ENC[AES256_GCM,data:+NiO,iv:hZB4mv71hdVm4u80W1J2t2cngYF8c6twPsTc31hhS7s=,tag:25nnhjUsPSynSKErpPoluA==,type:str]
type: ENC[AES256_GCM,data:onNfhFvb,iv:dj6HwyoN1Vit8vXLp/yLEHEGnr2YTMsk5BiAw+jAdRs=,tag:K2xJERGaa7emU/TT7f6ApQ==,type:str]
data:
    AWX_TOR_SERVICE_KEY: ENC[AES256_GCM,data:Ag/0YDYfaghhGUwLxnLzHJ62Swg+zLdOLXVzbRReTtu8EUbtIV6gGjkSMueL+3lFwrgLCrjZ0g/0vN/ePKp41tpML3kCZTAg+4jfhKNOWqJ/H5l6adQnHYlbMJ7noc44cS7A+DovZLNgS6J4Oq4+eX7ArocuQ5vRlffI7N9J4m4=,iv:0+H5+USiGRII/pYb8hnxrKyz9lpEuxhYT/aCG86fD98=,tag:+m6mU2RZg44Xx/nifzTwkw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMis0N0VVclBPK0VWcDZh
            THNiN1lQRmVjdXlsQUVHRGVPZmRFZnVUNFJVCnlMR2xOUHdHcXpyK2tudjNPVStU
            MC9XanNyL1hyNzlQWlZrdjByWjdybEkKLS0tICttYU85anlkNWR4ZjVsVjRXaURU
            QWc0cmRLaXFoM2dlZjVXNFVRZEQ4UWcK8ZN9bOKrTcyU6CHE0f/pHm0mfvqNOiGQ
            J6Swex5xfaG4mbg/wVV2stXWWf1f/XEX1b9drGOvkrtwP/JAMW+CGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T19:24:23Z"
    mac: ENC[AES256_GCM,data:fs85zvXVihNm7fLiuMoKfO9Elck269MxN5entBPFDiBKLAoaF3kC0i1vH5CVmfUY8HN5LxLrrbnaEuo6gQiFjSCK3ymwJRir2Z42GR3P80szOpiitgKS4bj7x6s7Z2m/4iD/pv4DSuAc/ISakunpsY0Lwm4f8j0pTqDksEcP7Rw=,iv:XHtidSqfCA8VAX//bHbJvbOe6sQ2tgRGvS8rcKR2aug=,tag:IuR/amUYYTZ1jlbyLGbcWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
