apiVersion: ENC[AES256_GCM,data:Iq4=,iv:CDHskcAfs7fTOiUWbq8488UObRYxmxBHWSl+ZuyZAPY=,tag:pr9apeOEWJgV0+2Ela9Vlg==,type:str]
kind: ENC[AES256_GCM,data:cuRds2MQ,iv:ndPB+cIda6+Ebuav052qNcSJZ/8T522E6Lxj/vrBAZM=,tag:aeCQmApXJAhLbqmLfbbc6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H7veZmnApyIONKqNmw==,iv:NGW/kN6Hq3XkorjMB73D25cmT5TXLjlRkrtUgIZKBqY=,tag:ELs/5tENvMch2LMlc1SrpQ==,type:str]
    namespace: ENC[AES256_GCM,data:C6+l,iv:Y0otwnJsKUEZcy1fCGWp0cg/cP1wx1JWxDL1dQZHFWY=,tag:l6KY9VQhb2EzIi1cNZUFUw==,type:str]
type: ENC[AES256_GCM,data:4xReMm+s,iv:myLeT5kWnQ0yOTw84gXO0CFXCDK8Dp1GQNk7kZeVHOU=,tag:QcMb8lenDMWAX9p13IIDBg==,type:str]
stringData:
    AWX_TOR_SERVICE_KEY: ENC[AES256_GCM,data:HOtBDTedkF1VrfacILxcD+aHIcSJLCt1QJZRTPCA/BzdcuIO+9xh3LKd1TPQ9p2nHP6pYVdWyfveg81SOgwMmcpOHWgb8ANLbIAu+kuWaZLE/Psq+SLyYOPVLs1QCSdLlug01bpqBK4rn+QkMfBpj3CbNhDuEC6pWIY6FGZ8oNcv,iv:3SgLvGfqK2KrLFBOCgStXs+auV/Hk6vdSppbR8Nf0/Y=,tag:SXP5pZ/mX2DQkOSoxgiGKQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRDZoUnhZeDV6QTEyVE5O
            dTl2cE0vYUZveVZXcGl0dnc3QUhmMnhFV2tvCmtwYlZ5aCthTXFGRWMzVjdlNHhH
            Qi9RRUtzMlluTkxuT2x5ejJFdTdLenMKLS0tIDdpSStKeWduKzc0WVZUUVc5NTJw
            ZS9YdTg3Z1M1TWcrSHkzSW9HS2pGVWMKGZKuCw7AlJ61BBmm+/AZaDQbr2Ejdb8F
            siqteK2/bQtKZtynpnhtrU7y+reppwrPyJB7Ils8SWGytKhplF6iEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T08:42:47Z"
    mac: ENC[AES256_GCM,data:pzUpsSJSuSq5bfq8I4xmO+Krj4TMeQjYjyH1oDkfmSlPuW8hItOfbLsuI7diupCw0eymXwF7xyfOQX14His9XIo7yX9aPGq7Se823g4T08hRa7UD3DDx2VNXZ06/2OZI97f3TNuVQT74powqEgN4iKCYYdshuaYmxMwKfiOzgJg=,iv:Jnun2naawY5EardCi7CFhLtCXvypYBiX/kEvRKuIxx0=,tag:NCVszU+c9ORRZnPXX2JXVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
