apiVersion: v1
kind: Secret
metadata:
    name: tor-proxy-key
    namespace: awx
type: Opaque
data:
    # Tor key for AWX .onion service - base64 encoded raw binary
    AWX_TOR_SERVICE_KEY: ENC[AES256_GCM,data:lWNpqlB07oOEAbfyuYg2HvvlHg3WCkDAUsBZDdZlKf3QtMFV5NmQHY3NU/VVQm1SLqGwUOhtZTQJL9SQhH8xj57/tVSLKmCrQx77X0WomUZv1ID3N7SDnaqCGHO4Q0lCZ8FOU9A1mpjGjtJjWV1VC/kG+ARbiD2JbfFDyAX8w3M=,iv:bQ1tXpCDOZKa7FVBijMKl/iz6KduPlqwb8bviJNJL5o=,tag:tYim0VIXYhq535H852H0gA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQkh5cTFqYmtPSzFUV29s
            UVJYaERNZ1RrSXJzTGV4d29RdFFNemIwNG1rCmIwUjhsellyZkRTTVU0WlpGeWU4
            VHZ4Tkg4dml0ZVA5M2pscVdneHF0R3MKLS0tIHBUNmdzMnR1cXBpVk1aemdLZ1B5
            a1hKRno1cXlkcUM5SWlrMjRlWmFBSE0K4D00A7OD+OBsusa1+gxsNcMQDgcTgIxs
            CEv9bhPLGD0uRaxdJGf5vKvZ7ioghJZ/GsFfomkyzyqiHB7GQe9LTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:lNWby9JjRHJnBE9/qAqFJuc0zg/ieqt2IJb2ILXfa60h3hn5WeGBlLsFxIyC9psMwvWo1PpYia0zrmS0rZBcSGX5dZMqAIRo2EtrP6GpDwTRiT0Ap12We59CugiJa9dTaObbnWAlSUXoiIPkfAn1VbvaQEgkGRa17DnEEDD0xDY=,iv:cQtCH1FxwysfGs7swbOl1uuo6BU4fXHuSHW/dv5qJNE=,tag:9gCCh4oZGrQv3xDFq5UZpQ==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
