---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: ansible
  namespace: awx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - name: awx-service
    spec:
      fqdn: ansible.makeitwork.cloud
      target: http://awx-service.awx.svc:80
tunnelRef:
  kind: ClusterTunnel
  name: cluster-apps
