apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-makeitwork-proxy-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - tor-proxy-key-secret.yaml
