apiVersion: ENC[AES256_GCM,data:Wrc=,iv:rSvgM4ktb3ge3ZJViTKghE4NSzS9JOFnNJU/r7Yh5tc=,tag:cq8HHfYBSSGi2kZTp4oNvA==,type:str]
kind: ENC[AES256_GCM,data:RJxVtgAu,iv:cG1JlumQRE2m2O1CQqX+Xb7+VK8zr7NgJJsx/TrvwwU=,tag:KLuFv1HsSUoveEIBF7mxvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7odkwG3mTq/Ud79qIQ==,iv:5za7E9sVVo5kMdHVpYZdwbrM+MuLvi/u51C3bhJcFEc=,tag:uxw0bjIqcRtZWI8QSTdm8g==,type:str]
    namespace: ENC[AES256_GCM,data:8MN/N4wDYy4ZAFu3uPhkUQ==,iv:b7rfuU8e9X4mtGP5Niw+DOckUjFj73OAwQyoGY48uIU=,tag:lZb+TDzH5GXLop3d/W6JRA==,type:str]
type: ENC[AES256_GCM,data:21gLahGP,iv:+PLrreXKjDXbJSDkh2DF+9v+YfNsNgQkk87o60H4qOw=,tag:g9eba+Zdj4dI9DYJwmkDcw==,type:str]
data:
    WWW_TOR_SERVICE_KEY: ENC[AES256_GCM,data:7I/Y6aRbVVCtAX1W3gVAkkshCuCmgeMN07AlYLOc3RVWiV+L781lzUWsPP7Ji5Ddpvqgp8AqwGxvXnK+lGUwdZ/a18L7fvr1u3hfbBdgc/kx/DUu3Rz3mIEUcDTHOSI4/5L4Z9Lzvef/yzqMlEhL0XZykt0Gf/lZtXQ7wleMsOk=,iv:Cr8zGpbq996i5gvzuAiDctjHKPosuKKkgMUIMj4JEMM=,tag:WSHoUQm2q0U7Bb/PGcS4GA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMC8rc3ZQRWxDVlpPOHdG
            eGpTakM5ZzVxOXo0d0ppUWsvZUNTRXg3aGpNCnkyd3FLcEVER1JLQTd6TktZd3Zm
            SWJRbXlLZ2FTQ3p2bldHTjFRWitmM00KLS0tICt6NnVzVG5SRFpoa3lkbGFDNjVQ
            TXRzbGoyLzRjR2Y4QnFRb25VN3R4UGMKv6FHNsoyq9tUgvzYcPMF/3WRuXfF05p9
            UgaTLsmru0SvRxo1RRh7ef5DyVAV9wFeiVhtdGPr6sQlUM814kwLZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T19:24:23Z"
    mac: ENC[AES256_GCM,data:DxLN3qwg6LRk8ovgW6UGsRRfZhZtip0bNuX5TzWX1G5LqYXwe2fnamz0Xf2esU2KuVmBjAdUo5KywTFH0IZEvCYIED05okclFvmlJYpUhtUqvekKUZDiGp4ApqFPB4IXG1X8La5Ly7vmEgRhOfGtX3zJHdjWAvQd1o0WAl7oX/4=,iv:1E9R4xgorEPxTA/ea/Sl2ajlf9usICnTrw0lzgexfYE=,tag:0OyevcWGyCMCsQdmFVki5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
