apiVersion: ENC[AES256_GCM,data:pXw=,iv:CCWLbANhh98mact7uAMsoSZNgH/WGCrEyQRIF42DuC0=,tag:2RoU18fp2ypRva9L5zdNpA==,type:str]
kind: ENC[AES256_GCM,data:lbziUNWg,iv:YcecLkqAEALJj+tdQ1OWB321PP0O4k0y0nRc3Gc+oMc=,tag:Mc0bclF/pZf2hcsyuFh4gQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:STaIhQnmTu0GW6ZIdQ==,iv:hMfl15tJ/sZzo1FqacHeA5ntNpzAHhbXCyDKuD99xpA=,tag:dPGoS+lbSWJs0oMMfvj2Kg==,type:str]
    namespace: ENC[AES256_GCM,data:Cir1NLl8tqlWqAayeysv/w==,iv:NssWJeW6QbPM2roF5IXfOwurtdQYFeYVKRbUargInEk=,tag:hZREMN0xD6LQLBixDhVGHg==,type:str]
type: ENC[AES256_GCM,data:yBUsp813,iv:/r9FmCDb9ErajChVg10WAGXBzBM0PkMeNvvkcRZlrW8=,tag:z0M3jBXvnjBuRQ7mhw+TVA==,type:str]
stringData:
    WWW_TOR_SERVICE_KEY: ENC[AES256_GCM,data:RnmdeNbAEBu/NgSM9dib805QV+WGD6IH0V0KEA6rX/Z3XRDCgbJmoUst3BnZp1kxVD3LhdDqWkEUQb67v9QU20sqoUUZa2WkIDe2uHFAV8G7bylAlYK08Y9isAlFfGdnZFywbAS1/WMA5dz2ohDPz5qNjgw8VedMMKyoNrRAjWKH,iv:7PoH7382lyYV+WqEhgBzk0dunIC2w8fvIEoEUNuVnRI=,tag:/oHnl+dnVFc7FhNgDERMhw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUGcrTDE1eDAxaGhUc0lr
            OXJIQXNianI3cHFuQ0V2cFI1RVM3THdkRzJNCkxwdVFUMjlMaGhpNnh1WVJhR3lW
            THJoSEltd29vRDYraElCR0I2YzFxcXcKLS0tIDJ1MmsxU2o0V0lkZU45TmhwTzVI
            YTdUV010eXBlejllS05qK1ZhRm5EK0EK+BAJU7eoHkPdf/+LTRzVYgJcKoDaFepf
            oan0yr1ZAuAxolBmgjiqqWO8GJ5gJ/UQAWUlDBGULacRjE+099D2hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T08:42:04Z"
    mac: ENC[AES256_GCM,data:JSuFPDpeZ64DbjXN5R33m/uVUN9/fx383Ei97/pmmmSciSREQ/4uRjGPd4mlsOmVv2Uj8yBT4M/zlDo+TIPj7KfW4S78Nxs1CmAWyFeHeofXJYsZATQ/y2m/mngtqrFvJpYKUUK+WBXL6OqjTnUGwXrz8uBoVIsvSPX8S9Barx4=,iv:nuiIR9/tYKeAkEoQtuXLGzVC95MMtif0Sf8mHqOfhMk=,tag:MH5cp6QrO5O9ZKRi2XmJ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
