apiVersion: v1
kind: Secret
metadata:
    name: tor-proxy-key
    namespace: makeitwork-proxy
type: Opaque
data:
    # Tor key for www .onion service - base64 encoded raw binary
    WWW_TOR_SERVICE_KEY: ENC[AES256_GCM,data:qMY5MRaH1LKB4Eiq158ziMTydBu/0pQpFwj8qSKXdnDzdlllNfQ1KEPfhJ8RNda81Ty6MYqR9YEmne+ukJu+an3FCSohJ2emfFSqhDepo9B+16RY91avFInnU5UB7rHvJDTtz1N75Y/SsHVo3ypjP0InIpgWePpGsEAEwqKYVEw=,iv:btEbAjgV9xszPFQm64mHVjhY4BZm0Ilyj2OpeZPMZyQ=,tag:DEjDGduPKh56cv/rog/7mw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNS9DVllwcEJnejEwZ0pS
            RTVXWXUrS1lOS01NV2JBQ1M3ZlZvWmNqM0FBCmZFL1AwYU1tcmZwbjdib1Q2T1FQ
            MFR3U2JDUCtRQ0tvbVRBVjArYTFIdFUKLS0tIFYvYTJDcS9jbStHTnc2SlNVdTh4
            Ukg0SlYyUTRhRXo0RkVyeGFkZXl0MlkKVXJhRVb9evjRd+3XJd9caWwKscaaq0xc
            vkrdybw8S8/nGSCvYMxsMHHFOiGqssmHYHuKUIXpwbZ4ly6GnPEXcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:+eS7HUmmoOBk2q2KlOUVUtRH/eI7DOzVZnzf/4KRnk6Aw0eJuVgUMKnvl1rz8LoUtZZGQikSNBdM98Yf/l4GZ4+czGBaQo1EBqSd0bCILKLIf761Tl1UTsLwV/Wc0vMWn6odVz4OQmWnmbqDsnbXKpocCHVR3n0lKGG4kU1dyyU=,iv:Ek5zF+poXFBPHATeNNnJVxotO1kI/Xhv0w4neOkcub8=,tag:p2v+PfN5U7QuNNk3AUYCUg==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
