apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:fXtZzHTDrJLttcCY5ivtN0Y66P5epOsc64vO+qQiW9bOKmOYMjGRHUx2Gu5pQOYsGVdVeraN8JiYujuGBMdHJnFZL/vQdZ0HNvTwd4MAO0nPkpFnBZBl79+L9JWtKrqhVZn411rvwIt5RX7gW4FXdBi7XpytW8/u/xB/kuei7yqfDwo/g7h/PP2b7oXdaibyrpkVtrg97i9G7xOEj48YH6LApFcgkx4g447F8gXkap/x1SjKIInxRfj29LbPe4AtQrzCdFWt49UfQlx8kvYYo9OESjQqu5RoO5Gu8Y50wKKos+PnXPR1S7c32Jx4Daixu4jcr78v+OPRADvu4Sq+epLhiBUqbho1eMKPWUmaROauvkUf041CvysbSvyU+bXsOCXdDmvlzfzLCSPFkxgZJh/79+gsyh3H9itTG9LS0/Hfp2b3r510OC63CxaJXiTxeIXJo4SmPtxPz9Gro0CEPmZrPuRn6ifm7Zdh2BTWjhERBASm09YsQdwcHaw4,iv:flBMSEDeDzC3lZlSOUgRFvgnu9P5drPkuFp7AUXs2DM=,tag:E5JW93x9g9kG4VOvgko0Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbzRaVjZJR1Z0N3JaWndP
            alhVTWJsV1ljQ0hVT3plRnlvZWpxZyt6b3hJCi81UU1iclNUbXZWbHk4OTdMNWJL
            anB5Z1NreGtxbnkrYVp6M2hzWnc0amMKLS0tIGYyMDl4emZxbngzVEtZLzZ0dXgw
            dk5HVGdZcGZneVhlbFg2V3ZBeHloc1UKSKub5cEbfwggnQE4H6rSKOk4gzPTCIxx
            R2xSSIcgMSLl7/oSpUQPFDzwS3C7QhgkFf1I+bNG6HSbrM08ccplog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(alertmanager\.yaml)$
    lastmodified: "2026-08-24T22:00:51Z"
    mac: ENC[AES256_GCM,data:yh2y63DasfrMSGxwMEUSVjdJXtjkf+IrV+tryaPYmWl6GH7zMfjSfLPO6iqi6cpjd72xq8dPedNTAbztxSboiykjddcu8YKSHHtnUtKtsjwaBnMoD7xcS2fnFg3FWWvc+b02vFrJk2FpSu2UFdwRE6oDdMH28Tb4laZ1Uo6TqH4=,iv:J//W28h8Aj7AY7l44kgRnIFVHJzJKVY4Ge4FPM75UK8=,tag:ICOp67Jnv1Xyy2eevGiNMw==,type:str]
    version: 3.13.3
