apiVersion: v1
kind: Secret
metadata:
    name: makeitwork-admin-password
    namespace: awx
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    password: ENC[AES256_GCM,data:9CMjnNKU96N4GZTjmNVqpdWWV/oRpoZBrbsQ8n1OZ9w=,iv:gD+vRyU/yF2gtjNOReqDj01muFuRoYSnjRZJf1Iynyk=,tag:RPwyz7bBZCFlZTLi3LRlyg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK25WRGE5czJBTFYvNDhr
            UDFKeTNlWTN0MUllR3drdjFGYUFMTnQ5MlJNCktROFd5M1VFZHJTT1A1WThuaHM1
            VklkbkZuY0tscHY5Y09sNkFEZTNQZWsKLS0tIDJ6aWUxSHR6K2RkVWNzRlJmLzR0
            WENSaTE0ck5pSFpsd3BPdERreFpndUEKUarJvMHr6BwHcutwMxryHY+9diADtgqb
            OQieidE4PilPlG/mSQBL+Q4oTTEdFbRINjtOjAMs2+qt+XrrQADwIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T19:54:28Z"
    mac: ENC[AES256_GCM,data:COAJD3HJUno1NPBqj2m8KOVNFfL1KP1IIjbiZZTM8oY8PsCNIxzcSAKgMVTFLaR3jTSqpTQKvAdYWcE3bh8ywqz1vdBUf0vm+T1YmAFefEWUEVZNQ4NCXoaLMNiNmqCp7pQ5ipO6Gstp95aJLh+z0i1PHDm+mbF04CQQziPobg4=,iv:f0Rs2Eysnan/rSuPvvaU/Ow5xxhzlIIPlU7d/7WFzGI=,tag:78mW9RNomghRJPXT0A/3bA==,type:str]
    encrypted_regex: ^(password)$
    version: 3.10.2
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
    name: awx
    namespace: awx
    annotations:
        argocd.argoproj.io/sync-wave: "1"
        kustomize.config.k8s.io/behavior: merge
spec:
    ingress_type: Route
    route_host: ansible.makeitwork.cloud
    route_tls_secret: makeitwork-tls
    admin_password_secret: makeitwork-admin-password
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK25WRGE5czJBTFYvNDhr
            UDFKeTNlWTN0MUllR3drdjFGYUFMTnQ5MlJNCktROFd5M1VFZHJTT1A1WThuaHM1
            VklkbkZuY0tscHY5Y09sNkFEZTNQZWsKLS0tIDJ6aWUxSHR6K2RkVWNzRlJmLzR0
            WENSaTE0ck5pSFpsd3BPdERreFpndUEKUarJvMHr6BwHcutwMxryHY+9diADtgqb
            OQieidE4PilPlG/mSQBL+Q4oTTEdFbRINjtOjAMs2+qt+XrrQADwIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T19:54:28Z"
    mac: ENC[AES256_GCM,data:COAJD3HJUno1NPBqj2m8KOVNFfL1KP1IIjbiZZTM8oY8PsCNIxzcSAKgMVTFLaR3jTSqpTQKvAdYWcE3bh8ywqz1vdBUf0vm+T1YmAFefEWUEVZNQ4NCXoaLMNiNmqCp7pQ5ipO6Gstp95aJLh+z0i1PHDm+mbF04CQQziPobg4=,iv:f0Rs2Eysnan/rSuPvvaU/Ow5xxhzlIIPlU7d/7WFzGI=,tag:78mW9RNomghRJPXT0A/3bA==,type:str]
    encrypted_regex: ^(password)$
    version: 3.10.2
