apiVersion: ENC[AES256_GCM,data:pds=,iv:S1ofnvh29XVVe9o/97PbBRQ2aQTRhHQRkHAQsYvwQGc=,tag:ZIcqPGnjEvp8YB4ejIKWqg==,type:str]
kind: ENC[AES256_GCM,data:nkIMKlzC,iv:UGhVcH3d2lVpkbrFa9iLwM7rzFF8zzSXKmqGzMxS+/M=,tag:pmbVY2V41C+bm9Hb0mQxCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:O3rDjDGvAw/oDFkBlonUmtG2jXP5xXI=,iv:JfM3oyba8JICboEFQiYTeLHJpD/porRu6hjF5CnRUbI=,tag:kAyGEhJaz4Ak1oq9DcToOg==,type:str]
    namespace: ENC[AES256_GCM,data:ho5PbZhP7A==,iv:NSajqzD9S6knlPvN/V1yGamnm3wyi8M1kIzg3Bv+lnk=,tag:FM9hOsfzqb/lDm2SxCTLUA==,type:str]
type: ENC[AES256_GCM,data:c5VGWME4,iv:8szLjUkgne5SAN/fDCrBVqfdL+ZTpIFDpr/2+06OyWc=,tag:p/ue88Hg88uEEs1wIEug1A==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:w3bnkuhYtu3VIKp7llBjSeM3yflJGF5lCkE7k/0uZQtjL36i698c13OCLRfCyq2WPGvIFUb2fjTHa9u6tdqBuW55mXNVXhYNkMBLVO+gp8lfWy8wDX36sl7eUP+UXLs6js++1eQF8SZvgFrRkOipNc1/ekoc1T+vsWJRxZlt7ERfF0llFRjQsqW7pIT51cJZ2YlfobUB/MnunJu7ZCc82J7f,iv:Fg0VdqGv0wmAoMEnOSvrgW9lEYE/05OhsqQNVuJ5UrY=,tag:xPsrY451aLWpS1vXhCbtyA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaW9LaWE3VmdDWURaRVMx
            SnpPWm9IQjlsdEF4Y2p0SU1TbzJBMmJ1WWtJCkljTWdBc3I2N1J1bDYzQTRJOERT
            UnRKcUtpRjVNbjRrRXN5RXp6ME9mUGsKLS0tIGRrYlROL1BSZkQxVHBSN3FlNkFq
            YkxsMWFON2RnNFBXMlUrM1RlSWdPcWcK5vxnHhdPlBinLaQQG96MKekOJ7LodCsg
            hmigc1MbyatpTHLFNjnO6yDThZxN+GFUPac6/98fbv3TB7s6KX2hmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:16:32Z"
    mac: ENC[AES256_GCM,data:KHUkdkeFch7PdgAHGyMwmCGn6Br1bpU5xMSwCMHj+zbSixzjozFlm1GOT06yuTxlQqCudjy6ZrI+gRJUZzA9EL2/5UT4xUkJFIc+2+Gw97PKzAX7DIEEW/LaBbJ9T138pKow/K8tVCBM52YnJitd8JI2HyH3XvIt0MQk9rl1SkQ=,iv:mgGtS8JIyV6/tIeU6CnRE6BuyExp5pFPcr5sE1TlQaw=,tag:C+bHTYS3cNIvpPyCVf+4rg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
