apiVersion: ENC[AES256_GCM,data:Akc=,iv:Ok9FlnvpaUmeC2a90xDRCxkLkTijavkWXrYWbDE1smU=,tag:sp6nm1dqx6yKH37BydKI3w==,type:str]
kind: ENC[AES256_GCM,data:eFNzLVrO,iv:tzlKnhZdL8+CczauI+eR9DFJrQM/YEYqsUbxu14eKPM=,tag:Hz2GZ8rg8JDSWiiJtSpYJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Mcdu/slWhRekk7/R1mDSsXD45pvwPJA=,iv:5t3VCnurZ7+n6Ewn1dKzDdN+A6b4dNZXsErNdkxjmro=,tag:kYoKLl+yQcEJUJZHVCbGYw==,type:str]
    namespace: ENC[AES256_GCM,data:rmS9EDGI0Q==,iv:wUJeZGDHIRvhnDrTFFAkuruVCL2D3YT9q5dmiMrOHSg=,tag:9epMpN8EtWeXcoawR/CLcw==,type:str]
type: ENC[AES256_GCM,data:E8FG9k//,iv:GhAls1yXahu0AiUPDeYIJcviiLvdik7g4qm1vUzBu/Q=,tag:YLD1/CAwJT5Cf6f1PmHGeQ==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:aUy1G/JEWBj2dWvSlsdZcJG2NWaJhS9RpcDDCpJ4cC5OyMQ3vxdh5ZEOihM/2mYJo5muCIwGFl2AtDT5mfwagw1ELe3mnWK7XLGPTrn2q7vNcFjZprD1GSvBnE0xAUMAF6zYjzHQzDBIQe3jqjhpwaAep44f9tdYXdLgJsl5Ms4e8rBY/JJ7YI1lNm4U8P/N120ThMdrArFcEt17GHj8LSwD,iv:lclUqU0oebOGEeHjGueuCmm+va3i0rBYzpJvTjBp09Y=,tag:e5gA3TNF2/qOV0tpro8/Aw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZC9tdCtBWTRqMFI0MkE1
            emlhcFV2RXZSMnY2VU93eHI2WE5jVVkrTEVRCmM5enBsM0dxc2wrV25kNGo0SWF1
            bTg4MXI0TDlLOUhTN0g4aUY2RnU5ekEKLS0tIDY4N0dLb0ZWT0toZVZRbzByUlpV
            UXYzMTdIZGUwTU0yQzNrazRyVWd4SmcKG2P1r1S0jm5Y6BT4hB45ct7pKt0cz8aY
            00T+9o0DoNf3e7YcP599B51IAj+KJks6Xv2d6ZgJEfUfgZj2U8JrTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:27:52Z"
    mac: ENC[AES256_GCM,data:Bogiy9P9bUHVYiu+moj2XWYezYTGOXZGD8+2fjbVGxChrZNi6OmVIjJfzgXkJpQkPLA2lYJ+lHHcUSXURhmMiH3djTSQ6ALdbemmX45iftGGdkEfdz2A+HMBU5B9ytFFPLe87cSHw1qUnkO5HVaYWPaSz8a/9tASeMNBKG5zLyU=,iv:wxpIoUrybM6eG9ExuISq83iVPToNbMh9YhU0yG5HNis=,tag:xKw5PSex/mNR2FQbpLo74w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
