apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: grafana
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:7w8tG69qBRKl4UsyQnN8Z01LIh0+8RZUXaAvkYTO57bsrMoZaTnyMjoNeVW6uwHktn07RmbDAdDKl3onybISrbz53tbfTcin9aoiY8P3Ws+LqLZ9u+Yuq16XiF/7kaoIA0DL1+eIH2bBsRU/0raXiDSTGRChCvE+gg==,iv:Z+cnDpurGZc48lRtnYfwRAw0oCZRdEeysFfeWpVFvrk=,tag:gMovfS79Ur6S/HBYnCW6jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWF2ZEdIbHdwVXJLNUpO
            cWNqRWNINW1PeWFVK0N1OWlJbzhRUDdCTEhJCkZTVUVUaWJQMFpiKyt1S2MrbDBM
            emlUVnIwVDZJNWdsMkpvd2wxMnljMHMKLS0tIFVZTHdRVUZWejJ6NTVTVlhUU1ZV
            NjFkeTRiWXArNjFRZG5rUVZreVR4RUEKIyPS+SqZb7znZrJUiuVK5pdmlV4ahbAo
            wp4CxTvSgfU4JFs7hRQOoN3vAq2Tn3DT7O0EgifdQrFowh2bQDy0aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-21T22:47:00Z"
    mac: ENC[AES256_GCM,data:ZUNRFkzK9Wx2T6+laukS1AKNIxlpsSI8nz6UjauitJX2eQPKPIzxtno5uPpU0Hk61+/0RwFbldmUbOdHw//k6qOuF6QdkHk//LGwx0TvT6vudpP4zhsRwM3cKYZ4ac+rwJy4TikbdCx1RQ4IOVL2n49hQfdqycb1Yav2l6OEjF0=,iv:datmr6NftdtUxx1o4oiIIO35qEY+nqTV8lQK7eEDmxk=,tag:TlISxX+RRLcgy97SjG1HDQ==,type:str]
    version: 3.13.3
