apiVersion: v1
data:
    password: ENC[AES256_GCM,data:DGAPRt+qoJkuxOIjFhbao0iNqD6yaCbHV6bPq5qHjGE=,iv:CjbBS2CSu77aZwiJw+l9la2TjiGMfTvb+C3Io64oRv8=,tag:LpRUbqXRDM05qTYlcV7GsQ==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kustomize.config.k8s.io/behavior: replace
    name: grafana-admin-password
    namespace: grafana
type: Opaque
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRG9rZTA2dlNLZTdVSjZj
            YmN5U1puZyszTkZ1L0dKcC91TWNQcGRkQlFrCmpZb0xsa2NseVYwN2NvdnRuSTUw
            dlo4dHBDMTJWWHlBYnZvd1E5YWpnUW8KLS0tIGdZUVhQTC9oSXVJeDY3TDlnTlY1
            YjFONlBhaTVsb281WmdaUVFub1JBM0UKHD/GQd5LdDBMUw/FqmAsyr2aUTjE73YG
            +8ZzipmA3q4H0S4Oo4IRo7512zfSdoL/RZvciyCWFFtRWR5MOBJMiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:57:35Z"
    mac: ENC[AES256_GCM,data:PsOqVCOjm+fytDEHu5bNbClfYXil0Pjss576ZWpdUAT2pAW6QY4gdtXWvCzF5mzvN7Ap7pMZAHwft7ed3K+ZxTMg8iBrOHyztn49zGTdnjxDvg//qMr9FDv8Jb90SdrHxu3/5Xg0AxXW/7EqA+8tYOlJnaBf1MT4ejIman4wG8A=,iv:MOFZJ++AFR+Zru/WNBUt0Rkt8w8D9OCGcKUCY4D+bk0=,tag:XzEOck4yhWEKiS0jwtNZXw==,type:str]
    encrypted_regex: ^(password)$
    version: 3.10.2
