apiVersion: ENC[AES256_GCM,data:mFw=,iv:Haltu8dp4QZvC+eWOk4u99kyMNZ+OizZ3OjGzODLR9U=,tag:2zeu1I3r8xRjRSMIT8XU3g==,type:str]
kind: ENC[AES256_GCM,data:jtNDSfS7,iv:0LqUR20P+kz977jzX7wP+EKpUyPONBcG/v53vVHpL5c=,tag:Hzese+ewpphnNHOfzYjJPQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zARaGL+h5F2FwXq98OcBnKhUAH4YQw==,iv:nJuaRBEr0q6anIGG2NMHZW5xfguAc/Qvwg5+++r3GBg=,tag:lbxu0hu1XUMwwI57qsk66w==,type:str]
    namespace: ENC[AES256_GCM,data:2zl7YHKzEQ==,iv:elAXvQhdjcli23p0yf1QgqpVL2+AOLgZIZIfwcmntes=,tag:xbmYVpQS00z8E3WuvSlhPA==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:WQ==,iv:qHGzQeVRK889ioQsgPz1A2dqmy6qfTRQTA+wdxDTcF4=,tag:qbQ1PNUsRchufC3eAXb/MA==,type:str]
type: ENC[AES256_GCM,data:4tpcByha,iv:F6dDErLUQSbw8CuoGaKrxlHCv5XZaZgAlq69frHuAXE=,tag:LgJb5d3r83GyuA/JkBOfGQ==,type:str]
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:A3o6cJ0=,iv:U7cdaNNc4d5aRdnngzJfZdlAexF+gech2WE+9mtpSnE=,tag:mUA3vFiVeQbC2AwyyStXIQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Tr1y+B4nXD9Jq8uxANDjnM7xQ9ZXVnESnskxc/B+KME=,iv:iNH2+cf6ro0aywIh/rFWTiSn0AUE6yYYYUSdpBTIrxs=,tag:UHSO1aBqbupeu1Qc2OPjzw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRk1yYTR5ZTJROTF5ZkJy
            L3RvSVVrLzFhek5qNjVQMkZvZ2JkL2l5RWx3CnFZZkFod2RoQmh6TDBjTVJNcHgr
            MzhnRjZKbzFFaU11bkZxTTNZWnlDTjAKLS0tIDdSQzBjWkJGdlVrSTIvb3NjeEJw
            TEFWSUtQU1p6VHl5eTlMWUxhci9zcE0KlNe5Yma7cBzEBUl3P4zG77qoWOZWz1r7
            djxkocW3+n2oPiS5BsnKF1jbySRqaqfCPJwq/F6B2eabmMeVS6rL1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T07:34:13Z"
    mac: ENC[AES256_GCM,data:XgwNznWf8VF30H8BOcGXYAv5wiUK9vtOW+lcpt5Q2YMrfF515bZ2EdMUjkDdK8NTE2CURoADBQxM3qJU412uYmalBg75tNkIhtP3m0w+l2AhOjhAX2EzAnNna1Xz7TYeq/Dec4ktPs8akNLn9BlPXjbBndcSahLy44s5qrFMG7o=,iv:DT7jmIQ0hoercCJ2F64N3KksvBHM3C9ojXf+76hRdb4=,tag:ltTwBTAdn9ICQmsRzfO31g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
