apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
    namespace: grafana
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: admin
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:CEmstp2fOuTeIisemQgGTGvxbAvo+EW7JWftdUiRiKw=,iv:LFw3D4t6SD/AoNMANlp/VLWylo+NiqI4qcqyWA89ngw=,tag:QQeM7mobBLK8BrjRcKuXcg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEQwSlhxTUFHQ3pPQlJ5
            OHlwR044bmlzU2w1WVQwcmkweWRTMWpOMFJrCnNXVXR4VTFUYmUxQnN4TFh5Z3lv
            eXQrZnpvckdBNVptdjRIRWRUZUgyZHcKLS0tIEZYdjlBclJIV1FUTjZDNFdURjh5
            WE0za0h4Y05KUVltQ0lJM2Z6MlVzRncKpeOPAKlaH8WvmBc7KD0Uax5FDp38Dj4X
            00pSAUye0S4/zgTDwzgl0YQ+hjijl7i4OV5cgH0UN5/qedjluQyvDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:59:22Z"
    mac: ENC[AES256_GCM,data:7J08oW2th6BExb4jK6qE5v356WjDAdXnkV2lKiGThjFkRW1tszfMfM9EWcN1sMAk2wjzxaV31PlRUmGBWUe4vKN0D7TEV1N0BcUv+IgbBy0rSUEuFluE+T0+NpskTLwZRCFibdHqirPvnGcE5L894Ao766u1MggeoAdJJI3PGvU=,iv:e9xypRrmqBe8H20Fh9FXinYSrEOuiepUf47x+25XqVA=,tag:gdOl1i/Qxq8xYpGjIElmQg==,type:str]
    encrypted_regex: ^(GF_SECURITY_ADMIN_PASSWORD)$
    version: 3.10.2
