apiVersion: v1
kind: Secret
metadata:
    name: grafana-github-oauth
    namespace: grafana
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    GF_AUTH_GITHUB_CLIENT_ID: Ov23liI2Cr1ur3xnZdlj
    GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:kTzH9AHBM96uFsCny+UsIbugL0fpkeUDHmZ99CdEZOC94odaSP1L3w==,iv:aNcTHLrMtWUtbvVqWVShXuiafBxY23QwEwgChkmYjdo=,tag:TYPD9om8T6kK6eZkSSCLJg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdlk4ekZvYlhSQjFLZU1q
            UE1kM0xaOG5jRVBsYklvbUhMWU9OK2tRZ2dNCjFnYm9pTkdVbTlqVWpMQ1ZNdytG
            K0ZtQjBIRGExamRPQS8wSUtDK0IrejAKLS0tIHh5eTBTalc3SmRiK20zYk5FTXNh
            YnZORG9PcHBEYWFvMGpYTlVZTk51eDQK9Kc1uDN1KIS4RSaFNI2XWfYIKar1wKPd
            4sFpixAYOyf3bkeeEOCQAw7AJrwoSPOnhw76I2R5i3N719O20TOrYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:5AZ50X6BJ29mzJezg2LK889/gsnW5PJRAeab/OXzQZOsLHASv61/IP9HWgHM+a7SKkmTBeL46btuQF2X343XrMYsebJJaUEIlsYuyqg9CjL1j1p/89/7Fnxv0tGHs7ATYCUYvqRVT3A6vp3rIbBaEaMS0KF79uahTt0k+xKkiH8=,iv:LLNFFIxt/cuQS5da40ceh+dpq8gwE48BUzmpwjy1IkQ=,tag:/l716Ralevn75Qjho+dNog==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
