apiVersion: v1
kind: Secret
metadata:
    name: grafana-github-oauth
    namespace: grafana
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    GF_AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:aEHCuZUleuDn7XC3M+fqq3hHPOM=,iv:L5PMI7F+o3+G0WDodKtvl3zMC4Db90dnB22C0r6eWBo=,tag:s8PUgE9nkt0rdIDruiluWA==,type:str]
    GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:br+4VEZwhAwymbZZhkTz/Iv572NtLoPJ+Dnog8PTgbsJn/H79PuRuw==,iv:/h0yG5euyXHcfFLUUgin9+oqz8rHCM5vKbZBJSdtrdU=,tag:+/Y5GMZeurgrtmxT9lRhaA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM3owRGMrbllKUVNBU1Vt
            UUtRUk1xRWtxUkZtSFUyTmRwd2VlRnhFakRRCmRIcjMyNDZvVFVoYXl5SnR3VS84
            a0FETFhDSEFLaHFmZ0F6TmVBeHdvdUkKLS0tIEhMZ3dPY2x3UEdYNElpSnpNamtj
            bktLbU03dUVrdjRLRm11RkxvWGhXOUkKgR+XIZdOQqEOTZo4ORbUiodt3pTnQx9+
            lyyXRfEFNVlHjpI4XrMVO4NV3knKpEKj+ZZMIWw/E/ZExXS66eJ2pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T22:31:57Z"
    mac: ENC[AES256_GCM,data:rViGKeu9x5fEOSVUzezrMgIqnwlMK3lrVicA9jdkHbsAPIQOFkOJ/RTW05FbaZ+eP8EnCyywfZj0wGgXMt3aOcrW00HH2Z/cloyrH0Y+gFYGc82W70JHb0dX4S4JLU8RSQNa5dQ9B31G9CRJEK+i4T5jDqoLXm5pPiB9PczUN9w=,iv:sNKTZakMMUb/z1/nVT0kwheqnKvRQkm1RhmzApyjK+g=,tag:1BWwnCGHinWGL2eMSOoVyQ==,type:str]
    encrypted_regex: ^(GF_AUTH_GITHUB_CLIENT_ID|GF_AUTH_GITHUB_CLIENT_SECRET)$
    version: 3.10.2
