apiVersion: ENC[AES256_GCM,data:Dbw=,iv:rVOT26/xZozyMkJFvQs8egOk6nDcScXL17AQr9TqDDc=,tag:YUJKw7TJ4RR06LuNaoytlQ==,type:str]
kind: ENC[AES256_GCM,data:r2QF1VtO,iv:xTbYA0BiCaNgr4C4tLVBJI33MNSSJTtgM+wJbiyDMek=,tag:aL3Q/nkqPzD9AcEc0T+pFA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qVFdr6RoWcaJkFBeJupMBvemkoY=,iv:5JVkGOTcINCMFgJiaAo0nYl36XX5k8QWrb5XA+duzc8=,tag:pS7boYS1CBU/PHbK3kHXFA==,type:str]
    namespace: ENC[AES256_GCM,data:WJ+D6AVg1Q==,iv:zn5wIP8DbvHSviqCvccWoCNaifM/NsIjHq7eoYqIE54=,tag:lgQvr1TojC8eaCCY2N9/dg==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:Rw==,iv:vrTeShXX0yqFCCVZ2p56N1X+S52TTWd/UWaCwiHXmzo=,tag:E2cStXKdvEIbTWMxktymhA==,type:str]
type: ENC[AES256_GCM,data:aIvOSLyl,iv:7syYVlduido3PDtGj/43Omq2BMVyELqzTJ8ptJc87OM=,tag:ARTLGzSPZI46j8y8n0JgPw==,type:str]
stringData:
    GF_AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:2rhe5eLkYXyA+PrjqJJ/dr8Dj4g=,iv:Md1+Y8QEInu5j29lPmM1oko7zIOBmjrSBBQOOowvSFA=,tag:YMegwG7PREJnvNpGwP4S4A==,type:str]
    GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:I70aEpsH2j02lH8UqjM+ThjolOQKMF+gCdPEf66kN+vQBJNC6daXNA==,iv:rVArDP9k0bjplMniaW7uneFYjkEdB2/gH28wxM7YfcU=,tag:GDyXMYFgVJtrX64VA/nKdg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYU53S1RnMk1CTmRBS0hh
            L2k0MWNZU1FaTWptQ3I2RXNqUytvTG1mQlFBCnVMK216c2c3MDNwM3YzSEpYUGFR
            dW1XSTQ3T0I1RzJ4SW8xRyt2VG1oME0KLS0tIFEvUXFsT2pjblI1RVlqYXBTYlZo
            RStJWndnNDF1TEtoUWE4c0VyVW1SYnMKwd7mtsSw5kkHIP+uDgh5L6pF/sHzXz/w
            a0nLOHi6WJJxeTorUnGUqF6FAYubFz0OF9j3goyuk0Dsor7hCtzBng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T07:34:43Z"
    mac: ENC[AES256_GCM,data:+PZzTfqM7Fy0S2M1sN68QDV/bff5BgBgUy6J7pz7PlxbY+axLxDTXIH8eWmuK9Lvg/0MIlb9MJGnoz+7ZcR6mZvnfpUrDLjO3u8i0dPflBhYOfcaDG6zrcFUmUalBXdDRQtMcEBq6Q7/KrG89Ofx9kKlCpZFxxQnVUFZiJ2NHDk=,iv:k9RCKwSWFuFbcNlQfsNCjkaWgsRASN/2b5uBEe8FYKI=,tag:yaaqwJSDGyl9lxhogk7KDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
