---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "grafana"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  config:
    log:
      mode: "console"
  admin:
    credentialsSecret:
      name: grafana-admin-password
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  route:
    spec:
      host: grafana.makeitwork.cloud
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: grafana-service
        weight: 100
