apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-grafana-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - grafana-admin-secret.yaml
  - grafana-oidc-secret.yaml
  - tor-proxy-key-secret.yaml
  - status-tor-proxy-key-secret.yaml
  - discord-webhook-secret.yaml
