---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - datasource.yaml
  - status-grafana.yaml
  - status-monitoring.yaml
  - status-datasource.yaml
  - status-dashboard.yaml
  - onion-service.yaml
  - tunnel-binding.yaml
generators:
  - ksops-grafana-secrets.yaml
