---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafana-status-prometheus
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana-status"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
    jsonData:
      timeInterval: 30s
