apiVersion: v1
kind: Secret
metadata:
    name: status-tor-proxy-key
    namespace: grafana
type: Opaque
data:
    # Tor key for status .onion service - base64 encoded raw binary
    STATUS_TOR_SERVICE_KEY: ENC[AES256_GCM,data:pSzHyfRfqGPDXVtyt47MCjBlKwKksZVHVZn0Wm7IxwjcCFHA+DWAPb5LJbRAcgQxi9IaPc+DhlmyvKHMzc0XIbqmwmNmr25Qikgq+Fri4dYwkDniSbafKm3Ka/RIasQcXBKtqr2NmVTPKqTm7I2Kz6ybdNab1fz1pFFQvHjtLUo=,iv:xVysw6DO5cET34se3cy9ybWKQCiJIJ1eZeiKYQoPZGg=,tag:PeZGb51bJVPxNOwE+nOytQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYlVaNjk3Tk9tRG1BYm1F
            Q2hTci9EVVRRam9vTk4vTXZIdTNrUzQ5aVMwCjVvSU9UdDdHRDk2SGxBZWRXLzFR
            NE0rSlY0Ti9lTjdYK0lua25wU0RDZEkKLS0tIFN0azhYQmJMb2FuaEN6ZE1GU3BN
            d3JnbFRzSFcvTkhKbG9qKzM3RjA5NUkKHBIfyRImMXll33g5+ISBe+oZXp+063Zw
            aIWU1eOOxNIVoaPDJz4xXpEwIgltJCQu6CMPDhbmBZ4pwJjCyyHIGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:8e1gSQLMXFjxYYMCirWSyQUs5jac3dq/YRuKRs0p6ClR3JiWu4IrwTsnrZq0td5CSOE7FZTRsJzhU6UmRizEOayjsMbvMNVlArXMwcp2p5kdNLnmK/EVtnQSM18WQ6m2QGiZ8l0xZlhfJLELBGLcMZVkbjQHixFd9GB59iPqiog=,iv:zRKnQU0W8huczX1ARt2e8ujA8CKOGFrAoLMPSfEU/do=,tag:+rXqRlk2nwDwdGJHVXdsYQ==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
