---
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: status
  namespace: grafana
spec:
  version: 3
  privateKeySecret:
    name: status-tor-proxy-key
    key: STATUS_TOR_SERVICE_KEY
  rules:
    - port:
        number: 80
      backend:
        service:
          name: grafana-status-service
          port:
            number: 3000
