---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafana-status-prometheus
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana-status"
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: https://thanos-querier.openshift-monitoring.svc:9091
    jsonData:
      tlsSkipVerify: true
      timeInterval: 30s
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Bearer ${token}
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: grafana-status-metrics-reader-token
          key: token
