apiVersion: ENC[AES256_GCM,data:sgY=,iv:lgmx3gG6RKyAWSEWg7TMbHmEBHCI8V4he1qIBKiKDow=,tag:U/9DlcebZfzao74wkOx+TA==,type:str]
kind: ENC[AES256_GCM,data:FwZ4IVmV,iv:4w09/b5Mdh4otjgWpvag48mwhJzg94KaIjPoFZ6IwBw=,tag:Bz97FKTzTfZ9BJEtFZvJfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h9NdfacANkdoKIjryQ==,iv:bEeqEBM9nV4ZmctHexSLiD43LHdlih+ZQ9txrWQKIgk=,tag:xVGxvpLdVIu0HhKlocbTxQ==,type:str]
    namespace: ENC[AES256_GCM,data:pV52N58XYw==,iv:H/EwmY3oir5k4KVwVkT/MwJtBe+mP9gN2Jw7qHkJUyU=,tag:67kB4Xs4cQTD+siTAKFVpQ==,type:str]
type: ENC[AES256_GCM,data:7hX2Pw2L,iv:zmVFIegRL0DwvLvPggfliHdIvL9qY6d1BWjntZPh1HI=,tag:I6NAGagRuZm4rBMjpvXLtQ==,type:str]
stringData:
    GRAFANA_TOR_SERVICE_KEY: ENC[AES256_GCM,data:kFE0nXedgYuTRvuSyeaUO4J4ixZX5EokVfZMdVBKmmw2M7YILgo5LHJrtLWXtpUGRCLU+2YxxUP2+cwIi40W6IxCy7cf8dCzynhic8Ita6P/SOFz9eXpxYJphPpvymRCuPiwS8XTy/1kl6a0+WaqMNNXD/SX2fwp8TBqoP0YvqzC,iv:qWwB4nbRDCL58WUBLKpSg8vMobcX0qJgehWJaYfzf2g=,tag:1lZk0WSG7L2I35IePW8MCQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbDBYdWNCc01RSXF4ZnF2
            cFBIM0MwWjZoSmJaMVE1a3hBNW1JeEdHT2s0ClU3OTd2YVNOYThTMWxBTVZYajJh
            aHZpcTEydmFWNzhXMFZCQkJsa1ppelkKLS0tIFZML25paHVXRHdvTEdlZ0ZqZ00v
            SUp0YVppWHhxcmZvam9DeVhFaXVIa00KYtCMsWhhzGRdrwIZa5QQZIYAb5thflks
            RuB1t+0ptFP7n2eytrqAMKb4zhq04iEw4YvT3nyCuv9QTyfGcjkTBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T08:42:48Z"
    mac: ENC[AES256_GCM,data:6OGnn7vO0ACO09ubZ24Ns1JZHsGUGFF/txFDyBiwTWCMcRDax7mCn23VFtTUj/4AsSTtJFpqjO//lrgZWNSVB+dFDYZtLfmtjwuNnwX4Xl3kjrHqw+HXoD0Sc1SUXMQeamO+UmmoOQFGQ7do++0oanybIew322wacXQmb3eIaaY=,iv:z1HcCIU32A7V3HIlnhLFffghw6SS8E08Z1UmFMAxeEM=,tag:5GfhnqvVxL5v6fy0hBu6IA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
