apiVersion: v1
kind: Secret
metadata:
    name: tor-proxy-key
    namespace: grafana
type: Opaque
data:
    # Tor key for Grafana .onion service - base64 encoded raw binary
    GRAFANA_TOR_SERVICE_KEY: ENC[AES256_GCM,data:+2eLk4EX3w6c68h1H6VjiFKLWEvJZPz+RhCVuz9VlV7yGbgD8i+IkNOxph4U/dpk00EUUo33CmRFeyHANNSLzvsrX/fc2uH6RBSYh2KvqQPinWSHfWG2x0BdJcayGMmsAnJKef6uMIkmt+A1pdIIR3UtIGgeCXa1QG81mbk0O4I=,iv:rNjQepzqHofmxvVV9+Mmej28U/NbyBqQXoh8RxIgm4o=,tag:4nsiUNmf2CrzzcfI0OebUA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWVYxTkFVOHNwSVBCQ2tl
            VW5jNHdrSC8rbmJvK0ZxZi9lREtSd0ZzMENBCmd2Vm1Eajh5UVVsdFpiNzhDM21E
            anhxRXlrUFRzVHJpSkI5NGxtTitHWGcKLS0tIDdQNFEzdjhvZjlYcFZtaHdrS2Ft
            UWlXdk1hVy9VbmxLRjllem8ySEpZaHMKkYuymU7buIJa4t45f6ykBpK0StFHIMhT
            MXQEQotIw+rm96BiX+XRkrv0edPwKVYVjFbR2s33VQZNVbYKFBPXYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:38:08Z"
    mac: ENC[AES256_GCM,data:ToE902PXKHGpTJ5h0bRJQH1zXmBhnT+zGllSov/LuxT+nVg5PpF+CLYHMETpF9wSgVBW4W5kMnlhwWqdZV0M4biWAmuDOKsLjcMrRFcjUUTf72CPvmEVqOEobD9R+3oShMZtG84uNZ219oDHXTd+wKLIjfrOSwdJpvHZFj2BPSc=,iv:yp5sKZR2Gs/BbHLqdaQ79PTsgYKgYdv6+znsu0Mfu0w=,tag:FJIsUvEOObIuubioSApZkw==,type:str]
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|credentials\.json|.*_SERVICE_KEY|GF_AUTH_GITHUB_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.github\.clientID|dex\.github\.clientSecret)$
    version: 3.12.1
