apiVersion: ENC[AES256_GCM,data:V60=,iv:fBkzBJSkd60OoVkhNojtLARjBN0PpyF6qqugPkX4JeA=,tag:Oi4GAOwUBTtFrllM6tf8Ig==,type:str]
kind: ENC[AES256_GCM,data:HHGKV+OX,iv:/RZaUcypbTEO4ED9t7CRHhXo86UBIlroGkJFYKjT0oM=,tag:eX0JHFaW5spLjw9ONC3YWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EOb1TYKmL+h6MAIfog==,iv:4A9/tnpOA5z9CFyNT7GHczpfMc/v64xdWl0ijgWTrhA=,tag:jd4O9wg647+gI4DPrAZcdg==,type:str]
    namespace: ENC[AES256_GCM,data:1vC8SKI8nQ==,iv:LhCRPl6HvOzDNdj8KRCxj1hH9xBr7XjpZ4pE8lfzbZQ=,tag:i95edrYBa0ScOHJSoVC8Ww==,type:str]
type: ENC[AES256_GCM,data:vM5pkrK2,iv:HexPV9KhC0WvigX8+1v/Is1OcEFIzAPXLJ4xZe0RS88=,tag:a25v0pCsZIPFQCEKjIUuPA==,type:str]
data:
    GRAFANA_TOR_SERVICE_KEY: ENC[AES256_GCM,data:ai+uHmG+w6YJ7Qnxtnk+wCsADU0XRPDB3ciinPIT67yNRvlhhgMoZj19jWckd5LeryA6eWZ8efxs6knJEZod2uowBDBQZMqe3Q6PcyXK8YMs8xHgvPIDIvuBQvvviGZbtmstC51zMXBl8udKADV06cvarhEKaWgAYH/ZTaGIolM=,iv:xezlEJ5rALfKxqv2HD+OMFwcVGHv8zdX3NU5WoBWKW8=,tag:hNfwRFaGM+sTGrCXu8RD/A==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MTZRNnBzYmM2Uzk1dVpm
            NTI3TWxKMUJ2cGJ0dDNKZXA4SDNiK2NZWHlvCmpnSzlSaUtOa1RoN2VSTVo0ZEdF
            eHBtOC9NbjRGRG0rT2xKL3VvSTJadk0KLS0tIGp3bkxUa2hPTjVndklmTHVlN3gv
            cTdrMTErR3lXWWV1a09jN1laUFhVRDAKYyLGV3rek28XMHc1z/WTgHpfXo4hbJYp
            1twWxSoIHJ1Q2oWSJtb6Uj2akqXzJC+gJw7BEvZzn/RzaSzV8SEPmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T19:24:12Z"
    mac: ENC[AES256_GCM,data:EamteWkzUOY4ybGj+ykrnJnSMpuvlz7lg1p4Pa94wSRlY9vJWD3kI5qIVGbnPWL+f7BsilVW5dOY0CqT2VnUjhz2NFY/G450sCB1Lmbxz6HcNIyVXDyx7J67PqyFkopHR5aWsAWdm2T7E10tF7E4ylKV9klQekC1tEYAGXHNchI=,iv:m04FPTnahXgtHQnfjNUium26sKs4PTwRUOfH/hyEGpg=,tag:ToyGPEkTCFgQ5oTqteWguw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
