---
# Operators - install CRDs before workloads
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ansible
  - arc
  - cloudflare
  - grafana
generators:
  - generator/ksops-generator.yaml
