apiVersion: v1
kind: Secret
metadata:
    name: opencode-sms-bridge-routing
    namespace: opencode
type: Opaque
stringData:
    routing.json: ENC[AES256_GCM,data:/CZE0Sic710/nYTxoBgCSfq9nQU3FldgbXyW11f//cO13nBmB8FnJZgIaOTYftemiUj2EUoJbr7uZ7fzP4PQcYOn75h3qmD7Y0Zb0WlYxIX7ckzTpgYGBOUCmkQwmJcEmyr5gDQIFMQwzKWFmvjQOiRWfKZpvxnD7aCxTgZPsURNQ4BDilYsIsKjSn+9T6DLymZGc6RtzieZTIWCq8NF8GriNih3ZCVMtQqjv9D2eOhM1p5kegUnIRZA40BaZQRGuUjDWg26HeD8TF/hVtIAVBRc7dK9pXEpI+UrOiTjiTUKR9Xf1twPpfmnR1Tc8paVwhfT08j22YuLmTiV9HFjyMbGvwTCwZSt1FB+7Q24EAEHBaW6U4Gt5mlqmPzRQFxDeUwrw2AuRBLF9SCc,iv:+qugp/RcIYB4E0SAAHZMX5ujgwQVJwCVFUnuYyAjCes=,tag:39cTezmxQO3ay9rYZ85PzQ==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbTdkNTYwUDFnMGFwTEV6
            TkUybzVOUWZGL2cvQkhWMlhpVFh1VGV1RmxVCjhmeEVpbnM1THlXdHJ2N0JkeEs0
            TnU1OS9uZmR5TXFFQjFwVkVnSitVaDAKLS0tIEdrNU8xNlNndnhMdmFQbWpLQlRt
            S2h5ajBtRWpjd0tPVjJ3MU82QTVLbjAKqWXryFoPWFZIfzBKjK3m6lZdLXjSUxgx
            TM9e9cXDiRomz4k+Ud6yMvDuKviO2NGcCYaLifxq1aSQdKmVz7Ltdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T20:20:49Z"
    mac: ENC[AES256_GCM,data:2bYWqY+ypU/l599CbCKX3gZKC9De1mP0Fln9qWP9PClYbgBW47Yo3G2cVBJzaquiroQVVZTarIpKJHKjl2rUB560oOCYLrc1J9bc8TVGL9hfdKIK7e1OgLkKuFOGzobcTIUCAKFzOoScwmf4QUhcf28dIr7blr985dRBEjdU3Ho=,iv:vz/fhkmktHWmyWD+kSaL7eWNhSeZbQFK2NFlfuAlzHs=,tag:hWcP2pa9fYxetBm1h79Mcw==,type:str]
    encrypted_regex: ^(routing\.json|state-encryption-key|sender-hash-key|twilio-auth-token|twilio-api-key-sid|twilio-api-key-secret)$
    version: 3.10.2
