apiVersion: v1
kind: Secret
metadata:
    name: opencode-sms-bridge-worker
    namespace: opencode
type: Opaque
stringData:
    twilio-api-key-sid: ENC[AES256_GCM,data:cc5E11emvJWTMx8VEA65nLIZ6X1F7V6SS3hu7wxqjd5aOQ==,iv:vqBfbi40tXopIDQkhaL1XTLY7ZAWvFvYopMiLwCAfoY=,tag:2AdQ2s1nH51leAUax+skjg==,type:str]
    twilio-api-key-secret: ENC[AES256_GCM,data:2w3Y9r3YJpVlSucCWpNQTQRw6MYJU2IsMUcRG/b+fak=,iv:COOygttRj8S92ZZTmPpf1N9HZz+tpiNnvmbmfUCqhdM=,tag:tSy3NIpil1c/YsfDANH0+A==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2lZMTRUTCtxamlPVFdv
            WnIwYTNPbWhyNkl1VTB2blBEeVJ0bUgxZUdBCjRJclhoSmtoZzNYWE1ZSzI5Tm1x
            ZlFwc0kwSUZaMDBQYVNnYkxyQWoyM3MKLS0tIGFiQkhsMlorbTd4cFh6eEpyanU0
            c2dTNjZEUmFFdWg0VjgyelNwejhZZlEKg4GwWvaQGovOB00fini/14zErxVLleds
            TUSALuYujlopJawBnYF2RBzTz1a3d8zqmlODw8uujswDPybkmht/JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T20:20:01Z"
    mac: ENC[AES256_GCM,data:JvXrf3T6jRAl9UDEinVwrgEgih6o0G+QV7dIhpU8VQkU/gbEqbHGOI6jYTUdh6VH7Wjq0asfbol1u3VBGxDrcWxWmh+sycBA8sInq/ZpipyfAIU6ao8n0/AeS0IIk6ILZlPlrYZYxSJUkLFSSFVf9KRV7t9reeqQz+6OESzNb5Y=,iv:FjBRvxm2QEE/Y4G+cqyA0Z5zRnsSzT0jdSooCh0+lVw=,tag:vU+iRWv6AGHw5KexX+VV2Q==,type:str]
    encrypted_regex: ^(routing\.json|state-encryption-key|sender-hash-key|twilio-auth-token|twilio-api-key-sid|twilio-api-key-secret)$
    version: 3.10.2
