apiVersion: v1
kind: Secret
metadata:
    name: opencode-sms-bridge-shared
    namespace: opencode
type: Opaque
stringData:
    state-encryption-key: ENC[AES256_GCM,data:mFEUIqIlTUV+sU44jba/PHRvzdqvOmzTnw4K3hIxJbp/KcuK1mDYxGxE+YA=,iv:Pd65WZJxOQ9x0Q5sJpINvCwQk3YlCB+5oWR7O+Sz4pM=,tag:brFWkYfEdbaZ21BB3UsX4Q==,type:str]
    sender-hash-key: ENC[AES256_GCM,data:T9Ota375C2r7+QLozDlmt9s0Kzi+DfcssqNw8aONNUdW/CypnoFwnC6Cqhrtr12orapoujH8xSTCEEKeiJCoJA==,iv:LfVT0TLjlV2MujW35ETG0JmdTwKaWfrOgzoJyuFavq4=,tag:+IQKF4oGIistd9w2EdNCUQ==,type:str]
    twilio-auth-token: ENC[AES256_GCM,data:mc/cpv2rWdRtUhAGF+Bmk8+NGeJKhzJXuRAompqUHFE=,iv:SnhA9u+dV84pfvWR6ciqrv1+q+JXpbDxYlRtKrMrgPY=,tag:HL6ooWWl1HOtiwpF9+6IfA==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITStvVU84MWo0aWlpVmxs
            eUlUMlcvUmppV0RnaDFISHlweFp5d25LWEZJClgzNDZLWVV6aGZvWmFmZUx1R0Fk
            QzR0VW5ybjVxVjlNVGo1VEU5ZXVaSzQKLS0tIFA1MFUvRHFSV1Vidi9SUG9iRFdR
            SExIcEJzMURaMmJuNldaZDBpWW1KZzgK6K6Yh+PbTsck4TH/JxTuLGh6ZbJvTAnB
            qjunZdZzbtESPnTaOBE39lnGkHp9dn2YZIzS8ixrtd07dtexD8AaHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T20:19:50Z"
    mac: ENC[AES256_GCM,data:k/HHlnv3/XNWsTD78JUT+r5HrV9YXCp5cYYtXIdVZaoD5VJE8DAFEJbxyh++HVbBKzHa3qtKR6NHaeWs7LZb/4e3a1upwpOu/G+56lk6RUAB3ZvdOpMX7q1S/9kG4kckcugV4KG6ZfwJ3m0oj6iNBmbV+xmo1VxaIHnQ9Eq19IE=,iv:ed3oLgNTFN+VKdgl66bMNh4GDAd84CM2gfBUE1YPAKk=,tag:noRlq4DSOlacFIePfb7kWA==,type:str]
    encrypted_regex: ^(routing\.json|state-encryption-key|sender-hash-key|twilio-auth-token|twilio-api-key-sid|twilio-api-key-secret)$
    version: 3.10.2
