apiVersion: ENC[AES256_GCM,data:ung=,iv:VJD020RCZ7eI39U1fSvrx1xUqvcmVNBDx+qx9krwDC0=,tag:Il7tA1JPHwVzJmxJyRe8RQ==,type:str]
kind: ENC[AES256_GCM,data:cRa7v5gS,iv:d7myihL6b4mIMbAJtc+g/+6N+BQ5UBoO0tGX4Khw90Y=,tag:wBx48sKRjzv+R9zQQKRZEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZEZiFYumQ+Sjqf7RLXCGp22hMpASb3I=,iv:XKhS6TkmR5Tc9dhjlyt3NaujDri9a9h0PT2UHmpArYc=,tag:/WhAQVg8oIBBAJflbztl+Q==,type:str]
    namespace: ENC[AES256_GCM,data:efP8j6I7L3XwzFc=,iv:aWZR7ls2TkN8aoFY3MN5soQotF+0Ps8Pv5NciSA+07E=,tag:E4+PKlvedIM5txrTvBQ6yQ==,type:str]
type: ENC[AES256_GCM,data:KlYONPnr,iv:m75+GdRmEw8puLZMm4SnIFGNLlvWwJVn0iMFDUVPCOA=,tag:8PxrOuvsAMrOQTZiTUqRUg==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:3XQduvUxDNbadWKWeBdfyLKNePAWPcnaqklBwuBIZTh4U1oJtsxF3bIdVTpyON+DN1bJuxmHXLLL2QM5dGiSJH/0rBmPti9BXC/puWZBo3H+TtNp/7JTLo/PowoJviaCDCUXVMjLbnCEVZTp0igMBqQ//L1GV1iEsrT0q78Lp49nrX9SaclrxaisTl+n+TQcDkxSYEAdjZh5F+M0zPs6Eeg9,iv:WWJxMKCmNz9phCGbNplTxy8bSBALnqZqda++KSSbsd0=,tag:IzLjAcogaUclAxdmw/aIPw==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bFUzMEdEcWdjTnZQaUk4
            ZTVldW9BSlVNK2FRemJ1SVFEZTdSS0NEdkMwCk1xM21saDA5Y2dOSE93ZWtFdDNl
            cCsweHVWUVAxQjZxRmVqeEhDQktZMVkKLS0tIFNFbXcvK1N5NFZGM1VBSkZlTnlF
            alQrMXZHL3VydXpFaGVPaXpVa0h5MjAKhIWmhx6RS19edX9QhvQnyQohKcuKyKCC
            4sUwjOdsPt6Bd0LpjGjZ700aa7du0IHc/OKQ7cTiGog6dnjXdW/sJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:27:58Z"
    mac: ENC[AES256_GCM,data:Zfy0jAGzWeBmunAba7OK/Nn08R8xx+Q8hQ8EoJeVOoGckPeqjO7/i/pQNQhtBd3pgiPqI+pM3YYZkXFis2CkO5RcgEGwdCk4dyktfsEJLkypvftpK8oXXlRiqaPnb4BGSYszYtAsDxLdqYLeYqe7sZNRxkdiqowgcGvL4DhO4sg=,iv:iEsMqBWhka7jtVxSabssog7dj+MTi63U50E2uJyqYR4=,tag:ZE4XK9vqkM8XrrBUpJCYXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
