apiVersion: ENC[AES256_GCM,data:ucc=,iv:OlZB7qrEDFncLdeoY14s6ZoYvuLj//VsCzZTFuTP8A4=,tag:Ag7gYEeyEE+ZTypW+dc7ww==,type:str]
kind: ENC[AES256_GCM,data:P/FqKeRF,iv:LoVHFz5c9CzrBFVZHtWyJY+ZsjGMyN0YIgV9R288g6E=,tag:tPrza55ysHeTyEM9ycK2xA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IThkymXCOg6h0QPp6wZTtg33srVSUSU=,iv:aMw/fV4ZAXYZb6BWr+sh/XR5042+DfinMwHGnsmaLJY=,tag:lbML7CIb5yqGQctpFeTZ6Q==,type:str]
    namespace: ENC[AES256_GCM,data:OsXITfRwdTUuxkA=,iv:ZEFJhYmj7pGF8s8ZjIaIxy5LLIPdG2xRvKRY0hft7xg=,tag:wgsKebH66x1kSXgbXQhCzg==,type:str]
type: ENC[AES256_GCM,data:OiUqTQm2,iv:/Yrym5uFOB7ITMKjTJbiQop45164Bb3Ur3uGJAdGR2w=,tag:m+wVANASNgf+W84189nfFw==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:B5d6/44MmDRAnLGSgW3/5qfRWhRhzWOufNb4hpuCEDYs4ZwOgI/NDMV3glwldruTEZD4osTUievAkiLMgCOG6uN5yPd+IWycc8nrm3zurtd71vwuCAhLc6JsPPJuiL4LiBXtZl48p5ZYMbevGHKn+oUGXsKW5JqcMbmsWN56rBcd35CdwCwpRJRMblLMGNy4jz0jzstZ6UIoSTjZ2KOBz/1A,iv:Du65t8IH2A0YPzYNDeziQYytWh4uGpKnGC1KJGPpYBM=,tag:y/PNSIZH3uAf329+pe992g==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXlNUjVkemE4amhCUWdM
            cUNLV1lKRHZSdWdPNWdOUE96bmlKaTkweXpBCjhIQlZSWWovcXpmMXdDOWVHNlVI
            MmhnTmpGcFpIcDdJcHJaNk9JckFoV2cKLS0tIEo1VmNtYzlKcHRXTTNycmN4aWhj
            b2lOMEdZZHhUUzZzVnpMS2pramV2NGMK4OStpdQTLmhJI+0xql2VeCK+N9Xa/pV8
            esHrkK4VvoKLz5CeR58wUUbw2WwfZCqhKOGPW+i84S9JUXvcQgHKpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:17:07Z"
    mac: ENC[AES256_GCM,data:vdV/im7vzgezbR0Zgu+w7SNfDLPXFZfc25nVaMnCfj90iI/TsrJM/nbB6rNpcy0NQesPT1skMLPURIU+EX4xkBDnHPfX8IJLSgGFOA9tz+ZkFL3lQxNySO1lesfVJl/cApch6ZejdVoXk/3RUI6nU0P3+SXXrrUVXpYLJr7QPB8=,iv:p9nIgqb6GG3JkjXeHYgdibUgg/gBQTcx6kP9a4Orw8Y=,tag:78QQlkqgx1piYGe5EoKTOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
