apiVersion: ENC[AES256_GCM,data:Cyw=,iv:tMxa2ZuR2wQflYRk5MUXCZUvo0gzG7slxSoBw5VWjvM=,tag:T1VbecJ3ylRepgy9VwUiJA==,type:str]
kind: ENC[AES256_GCM,data:1tyUepwn,iv:WlYV0LIdokwVAOYT6KE2hRxWVJjIuiabALS72azEZj8=,tag:OKml5NIV3+qtYGUePLIynA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KeGzDP6P5lZPxq2MkQ==,iv:acHoaNQtbk3QYa5jLheRm/P9zLDjyUqhfaww0mDOZos=,tag:EQ1VP4SvihZm7kTuKnKKxw==,type:str]
    namespace: ENC[AES256_GCM,data:rjeIHYadQZA4wMc=,iv:Z8C/oboMkf9vo6Ek/C8uEt0ssgkSbE7hxHVnYdCOKO8=,tag:6MZLEq57BMOzcw01kI7AvQ==,type:str]
type: ENC[AES256_GCM,data:MloApS8R,iv:Ekr/qfa4QYXxYQ1d8q75nO6hWrnRyUBWPgtOjRHfh3s=,tag:Q2FVT0sGAUDuFdiDhyTvlQ==,type:str]
stringData:
    STATUS_TOR_SERVICE_KEY: ENC[AES256_GCM,data:5OwRKi1E/Tiiui/LkS9EjWjkBXkO6pkrbX4ogy/VDjmG4J1iwfDGACRqqG3vn5lqIgGLhxxFGM8Nv7LzLfL8S754UPnpG6ZW9R089rN47peYgqWNcij444CjFCkwtRfFP9tmB4BQRa1rW+fLpdVr3vx/03Ev4biakbPW+8sc1v6s,iv:djsRngwUDzgy90ckOw9VC0yZkCPBNzecSPZ+bz6RqMs=,tag:66aJOW/0qAF9RMHEaGhYlg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSWhrdzNjN2wzUklNUnZV
            NlVjZ3FrV2REblhrMmcwZ3Riamp2b1d6dGdzCldNUUpTY1doVVN4WDI5S0grSUkx
            bC8zOFJxNTdhcTJsODZkalRmbjZuSWMKLS0tIFJsdXV4c3gvWlJKaTZQdTNOR3Zt
            UitGOXM3c1ZDRXhZcGR4MUJmMldNbDAK/Nt9o8RnursUNfy4RvrcO5qfNKTE2kb7
            HGZUX/T5/GJdK6vBLyJ0cpEHkjALTjo4TF4PKH8/PbIljfIIXOlTIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T08:42:06Z"
    mac: ENC[AES256_GCM,data:jNLew4EbYIw/iHGKMc19zJdud/mStUVkAeJtX14Ow6Iop0uVp+17W01ZcCeZdv+UkVx5KU9bVfC6z6d6uXzy+pOX/DVE1dYxViJHbnIfdBAZKGCILtzIzg3ClSASPkQ+srXEkAUdXDzqMVEnroA3r5NyAdvx0E3GT3My7zUXOl8=,iv:D0HhGd3NagcfQMODUA2vjGyEeCVutexMfva1QZXul74=,tag:uSm8qzBenDVj9lfQnbQ5jA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
