apiVersion: ENC[AES256_GCM,data:5Ck=,iv:WiKSd4OvqwOZtJxKxc5Wz3mY7YhNrQBtX6LAzgUzHnQ=,tag:z18nE3C7jlxettlubCY05g==,type:str]
kind: ENC[AES256_GCM,data:FftSh2Mm,iv:lzfeLSwj/eePdo9lrFH0Giljw9VPX5yKtwamy47jrZ4=,tag:GLofpq8HdBOdwjx3eta1cQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:srJGbSvoZbEmBuCI9A==,iv:is/gY33BkZuzlNxd/IxPzwdmhi1Y+0fAJ52zShK2hAg=,tag:lgAPGlBLu+iKnxgyp2+lRg==,type:str]
    namespace: ENC[AES256_GCM,data:Qxdcm8/I42osr+0=,iv:D2L6/nf36T0Eb3E0s+OWnhdoz6cjP5sjIOgDIUwad8E=,tag:dW63zcGsN3I3l+ghimFT3w==,type:str]
type: ENC[AES256_GCM,data:731todVl,iv:YFX2Gtz4GQGYomB0tb4aMczXF4B07G215XtmfQ/uc5s=,tag:JwpTVvG2d/g1C/XQlZRerw==,type:str]
data:
    STATUS_TOR_SERVICE_KEY: ENC[AES256_GCM,data:3YGJAxmxpT8YNplFCZpmPKRLR7KVO+vaignnt5lBW37Tp6f7wsEtwS3BD0/3KtpVDP288D9CQhTaA4/c4cbdLwvT7XrIhIShrClK5AfEaPKgHbeATrNwvckF7opfHaI0xfd45I6ehpVZUb/prOiTLLDrAVwyyeWmyS3Qay/ZTLk=,iv:cVE3kAJmW9zLMiwpiwHiuUGu11RrP6EFLhR+c0W1f2Y=,tag:b6DjFOTj9a5x40h8wqq6yg==,type:str]
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cVdDYU9YaWoyZ0hUU2g5
            dmhrQWFwc1F4WVd2QXhlUk5kaGtnM1haaWdBCnY5bENsOVMzamcyVW9KYUlOSmgw
            eGJHRi9HMk5YUDFFVTRxUlp1VXEraDQKLS0tIHNsVndNR1VDU0wzRmptTTlDRG1s
            WEJMa3d3QkhiUmRXSVRVZWYwT3RlSmcKQFSrRVatDZKJpovPdxbArd0euRc8X/mo
            ZYNYWYqoF0vKpEV720YUtezfT+nAb4mguFVONHVhfmJrLp/uBb/8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T19:24:23Z"
    mac: ENC[AES256_GCM,data:DXE/BFE7pDR1aucaRt1tyuBxEmD8lDSx5R08WN/3xjwOwLTyY7pbSIlKmR2JdADyHIvOWECiQAfhebFW1ZP55KTBRi5Zmq13T8uufoDT2Qn4V8fG4aCKnmx/hEWjtvAHyJc7lMNyndjoyErpIYXSE0HRSuQ0r/Ese72HFfR9qD4=,iv:O1y0+7Tg/Hu9rfORTDQI6soatFWEQlOL5OMfQnBJArg=,tag:J5osrvv4Y2xSc/H9SldWig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
