---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - name: uptime-kuma
    spec:
      fqdn: status.makeitwork.cloud
      target: http://uptime-kuma.uptime-kuma.svc:3001
tunnelRef:
  kind: ClusterTunnel
  name: cluster-apps
