---
apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  namespace: uptime-kuma
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uptime-kuma-anyuid
  namespace: uptime-kuma
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: uptime-kuma
    namespace: uptime-kuma
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: uptime-kuma
    repoURL: https://helm.irsigler.cloud
    targetRevision: 2.24.0
    helm:
      releaseName: uptime-kuma
      valuesObject:
        serviceAccount:
          create: true
          name: uptime-kuma
        podSecurityContext:
          runAsUser: 0
          fsGroup: 0
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        volume:
          enabled: true
          existingClaim: uptime-kuma-data
  destination:
    server: "https://kubernetes.default.svc"
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: status.makeitwork.cloud
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: uptime-kuma
    weight: 100
  port:
    targetPort: 3001
