---
apiVersion: v1
kind: Config
preferences: {}
clusters:
  - name: makeitworkcloud-k3s
    cluster:
      server: https://api.makeitwork.cloud
users:
  - name: makeitworkcloud-oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        command: kubectl
        interactiveMode: IfAvailable
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://argocd.makeitwork.cloud/api/dex
          - --oidc-client-id=kubectl
          - --oidc-extra-scope=email
          - --oidc-extra-scope=groups
          - --oidc-pkce-method=S256
          - --token-cache-storage=keyring
contexts:
  - name: makeitworkcloud-k3s
    context:
      cluster: makeitworkcloud-k3s
      user: makeitworkcloud-oidc
current-context: makeitworkcloud-k3s
