---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-opencode-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - opencode-kimi-secret.yaml
  - opencode-server-auth-secret.yaml
