---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
  - tunnel-binding.yaml
generators:
  - ksops-opencode-secrets.yaml
