---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - artifacts-persistent-volume-claim.yaml
  - agent-pipe-uploader-alert.yaml
  - service.yaml
  - tunnel-binding.yaml
  - session-metrics.yaml
generators:
  - ksops-opencode-secrets.yaml
