apiVersion: v1
kind: Secret
metadata:
    name: opencode-server-auth
    namespace: opencode
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Cf57hhKdx/bUintB6mMvKhAar6uDyAHYc3OALN7rUpHQGW+WFsaesVl8UIH41oeZHhqHf0Thu441rr0Ul2Z+0Q==,iv:jU/c4CDPsZ7rlW6ZOowDITIXIIC6qtqA958RrcO7gPQ=,tag:o5jx/Db6crc10GRjwUI0Aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVllzRFVlNXhzVFkvVUZz
            bUlLWSs2MnVKaVFwL0xsRHgvMjhySGhPc2xFCkVHeUJITzI5MmRZNDBPdXgrRUQ5
            M3U0d1Q1bFdCNlREc3FkZEV4TmcycmMKLS0tIFBGaEhVY3ZsdWxIYjZ5YzdHMDdD
            ZTV1RklJMHhzQXZ4aTlKN1dqdXB1NVEKA6WPnMcNhxiZnpM2ohgnQ2Oi6zDpFo8H
            39cDCqRpwgsAF2GkzIGdI/xghaFxnRUVEDCOsP6xZ0ICK2/lc5b9ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|credentials\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-26T01:35:59Z"
    mac: ENC[AES256_GCM,data:HWuQqVIG/ooLdvlmxwSZZu1ArVGCPHi/GWY6OhBKeZujL6k+RvvXAAVLte79DozSQpMuzrZeYLSpHZYAMItoH2Cxg6FetQu1YPM8Lf1dlxIfTELc6NfkIbFekjrLG2XbkSNeK+tSg2UhTSEbT9BkDyyck38g8ZHgaw9TZ5Ym1Rw=,iv:bKNxEBogBB7LwQrd/np+JjI1klf1yrhy8WAB6jcFPCg=,tag:xCejRRjrwy4rRs1xi5schw==,type:str]
    version: 3.13.3
