apiVersion: v1
kind: Secret
metadata:
    name: opencode-minimax
    namespace: opencode
type: Opaque
stringData:
    MINIMAX_API_KEY: ENC[AES256_GCM,data:0eNGx9K6tdPV/1Ac5vZqvVLyO5djndc8J3ltlUdY/5Mm8EITBhKtr3O9LXUw9C4/mS5voNOzE8eFJpjD/eOn4HJrqYhZ1d49zesVvcyR6gFl8yU4eCdzrmWyJJT6+sjoPMwrEmGkbR898xBWdh1Pus+H1c3r5bNK5eqQ82U=,iv:43efVzF5ggkOdj/dooFCN9HCz4DS0OfX0cOYwgahD2w=,tag:yrmXNLB9cKw3nKUn6OtcVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TVZDeVJ5ZUxGUnZRWkZN
            THVMWDdIQzlOMlI4UzBEQVgwTllTaTV5VTM0CkpuUFBLajlZNisxYUo2WkVzWU1S
            M1I3bm9BSldqYVNOUUxRZ21OSEV4emcKLS0tIFNTK0dWc29sWWxFNzJHc3ptY0FJ
            a3VXVEo3MkVXMytTelJ6dVdpUlAralEKzHMQZpvCHa1gim17VU78I+b2D8H/22QY
            rLX4wVN1T6p6VkBHk1tfcLWLKtBan8xqpBJblm+yU5hfjq5hnrdqqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|authorization|github_token|ARGOCD_API_TOKEN|GRAFANA_SERVICE_ACCOUNT_TOKEN|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|MINIMAX_API_KEY|ZHIPU_API_KEY|credentials\.json|auth\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-26T21:48:05Z"
    mac: ENC[AES256_GCM,data:18UmZfsB51sG+ixzsbr6oxFk3O9t32RRhz801X2fF3wtFJavjsgAnXeUbDaskn/NjI+Eu8YRdz3tZ5FRTqGpmaftwD4JSx4aVcjEJ/Lh4PQFhMfEdEtmZojgg7QiW+o62NV+aZkINVxIRdKkdBudSF3Fmsn2s13SSfRU9VmqhL8=,iv:nllpQjYTIqwh5Zqsts01MKxWKxYzllp3mHOqp/wFRtU=,tag:sHtg4ouykoHw8Ux51iHpMg==,type:str]
    version: 3.13.3
