apiVersion: v1
kind: Secret
metadata:
    name: opencode-kimi
    namespace: opencode
    annotations:
        argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
    KIMI_API_KEY: ENC[AES256_GCM,data:8ZHAA83Byigmz1HvHnfEV6eJS7/gApTIIlBmoEYWapItixLQ+EoX+i8iDgdpI3LGpHsUXlnRa+4ym57cWoBBnS2UiQYBgDmh,iv:vlCl2IGgHSgqyxWkiMP8+y3htiDS5+eAGIKCxOkuZ8s=,tag:dqcz/65MfPST4id/ULNXag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UlZ0OXVKWnBoZlM4UzRV
            YkZ5TXp4QTZqT1dMWmpzMWtxMTAxc1lDMERVCktuUU5uVlBOdHZiMXpCdERuZUpJ
            eWQ5T2xjUFBPRWJDQmhNWkQ1MkdmbEkKLS0tIHExa09xRHJOb0xBN3Ewck54WWRu
            eTlXSzkyYi8zZFNPY0UyWExkOEJLYjgK0+1e54TgXEz2YcEtFxiVYI6s/gyUQTx8
            xH+clXtZpicdnLNx2tMgEQRUlHES/cFAFF6unsFQmq1Dc7vxZm3ULQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
    encrypted_regex: ^(token|api-token|apiToken|clientID|clientSecret|client_id|client_secret|password|secret|github_token|CLOUDFLARE_API_TOKEN|KIMI_API_KEY|credentials\.json|.*_SERVICE_KEY|GF_AUTH_(GITHUB|GENERIC_OAUTH)_CLIENT_SECRET|GF_SECURITY_ADMIN_PASSWORD|dex\.[a-z]+\.clientID|dex\.[a-z]+\.clientSecret|OIDC_CLIENT_(ID|SECRET))$
    lastmodified: "2026-08-26T00:30:05Z"
    mac: ENC[AES256_GCM,data:oQS9LpDYreHuHlj6UoOhoDbXHJwLMj0roxRcprInvuRfDzbM6hWbOgDYau0aBmELvIwP/5Abfbuo+GL/X5vD+9vDtHhphBsBbIPEq7KT3sgS9LesYElp4aqNBGIG/KldXwztaOgyuDiOb+fzbb5U0tbnAMeYADiyafM1Zo5qLyg=,iv:9qdOclVeXvLZQRZ7cFFXiLjmWd/8ZN+sTiBLJJGrjcc=,tag:VDRsD9nB7cxq3h+S3eN4HA==,type:str]
    version: 3.13.3
